#!/usr/bin/env bun

import fs from "node:fs/promises";
import path from "node:path";
import { glob } from "node:fs/promises";
import { scanLeanFile } from "./exported_imported_lean_rust_fns/lib";

const rootDir = path.resolve(path.join(import.meta.dir, ".."));
const leanhPath = path.join(rootDir, "src/rust/lean_runtime/src/leanh.rs");
const outputPath = path.join(rootDir, "src/Lean/Compiler/LCNF/EmitRust/LeanhGenerated.lean");

const source = await fs.readFile(leanhPath, "utf8");
const names = new Set<string>();
const leanImportsFromRustNames = new Set<string>();
const rustShouldImportFromLeanNames = new Set<string>();

for await (const file of glob("**/*.lean", { cwd: path.join(rootDir, "src") })) {
  const leanSource = await fs.readFile(path.join(rootDir, "src", file), "utf8");
  for (const occurrence of scanLeanFile(leanSource)) {
    if (occurrence.type === "extern") {
      leanImportsFromRustNames.add(occurrence.symbolName);
    } else {
      rustShouldImportFromLeanNames.add(occurrence.symbolName);
    }
  }
}

const leanDeclaredNames = new Set([...leanImportsFromRustNames, ...rustShouldImportFromLeanNames]);
for (const match of source.matchAll(/^\s*pub\s+(?:unsafe\s+)?fn\s+(lean_[A-Za-z0-9_]+)\s*\(/gm)) {
  const name = match[1]!;
  if (!leanDeclaredNames.has(name)) {
    names.add(name);
  }
}

const renderArray = (names: string[]) => {
  if (names.length === 0) {
    return "(#[] : Array String)";
  }
  const rendered = names.map((name) => `  ${JSON.stringify(name)}`).join(",\n");
  return `#[\n${rendered}\n]`;
};

const sortedLeanhNames = [...names].sort((a, b) => a.localeCompare(b));
const sortedLeanImportsFromRustNames = [...leanImportsFromRustNames].sort((a, b) => a.localeCompare(b));
const sortedRustShouldImportFromLeanNames = [...rustShouldImportFromLeanNames].sort((a, b) => a.localeCompare(b));
const content = [
  "/-",
  "Copyright (c) 2026 Lean FRO, LLC. All rights reserved.",
  "Released under Apache 2.0 license as described in the file LICENSE.",
  "-/",
  "module",
  "",
  "public import Init.Prelude",
  "",
  "namespace Lean.Compiler.LCNF",
  "",
  "-- Generated by srghmascripts/generate_leanh_extern_names.ts from src/rust/lean_runtime/src/leanh.rs.",
  "-- Do not edit by hand.",
  "",
  "-- Symbols mentioned in Lean as @[extern] / attribute [extern].",
  "-- Generated Rust should import these from crate::lean_imports_rs.",
  "public def leanImportsFromRust : Array String :=",
  renderArray(sortedLeanImportsFromRustNames),
  "",
  "-- Symbols mentioned in Lean as @[export] / attribute [export].",
  "-- Generated Rust should import these from crate::r#gen.",
  "public def rustShouldImportFromLean : Array String :=",
  renderArray(sortedRustShouldImportFromLeanNames),
  "",
  "end Lean.Compiler.LCNF",
  "",
].join("\n");

const existing = await fs.readFile(outputPath, "utf8").catch(() => "");
if (existing !== content) {
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, content);
}

console.log(`wrote ${path.relative(rootDir, outputPath)}`);
console.log(`Lean imports from Rust: ${sortedLeanImportsFromRustNames.length} names`);
console.log(`Rust should import from Lean: ${sortedRustShouldImportFromLeanNames.length} names`);
console.log(`leanh-only names: ${sortedLeanhNames.length} names`);
