#!/usr/bin/env bun

import fs from "node:fs/promises";
import path from "node:path";

const rootDir = path.resolve(path.join(import.meta.dir, ".."));
const rustDir = path.join(rootDir, "src/rust");
const autogenBanner =
  "// This file is autogenerated by srghmascripts/regenerate_flat_mod_rs.ts. Do not edit manually.";

const rawIdentifiers = new Set(["gen", "loop", "type"]);

const sanitizeModuleName = (name: string) =>
  rawIdentifiers.has(name) ? `r#${name}` : name;

const cmpBytewise = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);

async function* walkDirs(dir: string): AsyncGenerator<string> {
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const abs = path.join(dir, entry.name);
    yield abs;
    yield* walkDirs(abs);
  }
}

const fileExists = async (file: string) =>
  fs
    .stat(file)
    .then((st) => st.isFile())
    .catch(() => false);

const renderModRs = async (dir: string) => {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const fileModules = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".rs") && entry.name !== "mod.rs")
    .map((entry) => entry.name.replace(/\.rs$/, ""))
    .sort(cmpBytewise);

  const dirModules = (
    await Promise.all(
      entries
        .filter((entry) => entry.isDirectory())
        .map(async (entry) => ({
          name: entry.name,
          hasModRs: await fileExists(path.join(dir, entry.name, "mod.rs")),
        })),
    )
  )
    .filter((entry) => entry.hasModRs)
    .map((entry) => entry.name)
    .sort(cmpBytewise);

  const lines: string[] = [autogenBanner, ""];
  const allModules = [...dirModules, ...fileModules].sort(cmpBytewise);

  for (const moduleName of allModules) {
    lines.push(`pub mod ${sanitizeModuleName(moduleName)};`);
  }

  lines.push("");
  return `${lines.join("\n")}`;
};

const main = async () => {
  const modRsFiles = [path.join(rustDir, "mod.rs")];
  for await (const dir of walkDirs(rustDir)) {
    const modRs = path.join(dir, "mod.rs");
    if (await fileExists(modRs)) modRsFiles.push(modRs);
  }

  const existingModRsFiles = (
    await Promise.all(
      modRsFiles.map(async (file) => ((await fileExists(file)) ? file : null)),
    )
  ).filter((file): file is string => file !== null);

  let updated = 0;
  for (const modRs of existingModRsFiles.sort(cmpBytewise)) {
    const content = await renderModRs(path.dirname(modRs));
    const current = await fs.readFile(modRs, "utf8").catch(() => "");
    if (current === content) continue;
    await fs.writeFile(modRs, content);
    updated += 1;
    console.error(`updated ${path.relative(rootDir, modRs)}`);
  }

  console.error(`done: ${updated} mod.rs file(s) updated`);
};

main().catch((err) => {
  console.error(String(err?.stack ?? err));
  process.exit(1);
});
