#!/usr/bin/env bun

import fs from "node:fs/promises";
import path from "node:path";
import {
  ffiCrateForLeanCrate,
  leanSplitCrateForRel,
  leanSplitCrates,
type LeanSplitCrate,
} from "./gen_lean_split_common";

const rootDir = path.resolve(path.join(import.meta.dir, ".."));
const rustDir = path.join(rootDir, "src/rust");
type StubFile = {
  rel: string;
  content: string;
};

async function* walkFiles(dir: string): AsyncGenerator<string> {
  for (const entry of await fs.readdir(dir, { withFileTypes: true }).catch(() => [])) {
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walkFiles(abs);
    } else if (entry.isFile()) {
      yield abs;
    }
  }
}

const collect = async <T>(items: AsyncIterable<T>) => {
  const out: T[] = [];
  for await (const item of items) out.push(item);
  return out;
};

const moduleNameForRel = (rel: string) =>
  `ffi_${rel.replace(/\.rs$/, "").replace(/[^A-Za-z0-9_]/g, "_")}`;

const writeFfiCrate = async (crate: LeanSplitCrate, files: StubFile[]) => {
  const ffiCrate = ffiCrateForLeanCrate(crate);
  const crateDir = path.join(rustDir, ffiCrate);
  await fs.rm(crateDir, { recursive: true, force: true });
  await fs.mkdir(path.join(crateDir, "src"), { recursive: true });

  await fs.writeFile(
    path.join(crateDir, "Cargo.toml"),
    [
      "[package]",
      `name = ${JSON.stringify(ffiCrate)}`,
      'version = "0.1.0"',
      'edition = "2024"',
      "publish = false",
      "",
      "[dependencies]",
      'leanh = { path = "../leanh" }',
      'runtime = { path = "../runtime" }',
      'gen_init_ffi = { path = "../gen_init_ffi" }',
      'gen_std_ffi = { path = "../gen_std_ffi" }',
      "",
    ].join("\n"),
  );

  const libLines = [
    "#![allow(non_snake_case, non_upper_case_globals)]",
    "",
    `// Auto-generated by srghmascripts/split_gen_lean_ffi.ts for ${crate}.`,
    "",
  ];

  for (const { rel, content } of files.sort((a, b) => a.rel.localeCompare(b.rel))) {
    const dest = path.join(crateDir, "src/ffi", rel);
    await fs.mkdir(path.dirname(dest), { recursive: true });
    await fs.writeFile(dest, content);
    const modName = moduleNameForRel(rel);
    libLines.push(`#[path = ${JSON.stringify(path.join("ffi", rel).replaceAll(path.sep, "/"))}]`);
    libLines.push(`mod ${modName};`);
    libLines.push(`pub use ${modName}::*;`);
    libLines.push("");
  }

  await fs.writeFile(path.join(crateDir, "src/lib.rs"), libLines.join("\n"));
};

const updateWorkspaceMembers = async (ffiCrates: string[]) => {
  const cargoToml = path.join(rustDir, "Cargo.toml");
  let src = await fs.readFile(cargoToml, "utf8");
  const allMembers = [...ffiCrates].sort();
  src = src.replace(/  "gen_lean_ffi",\n/, "");
  for (const member of allMembers) {
    if (src.includes(`"${member}"`)) continue;
    src = src.replace(/(  "gen_std",\n)/, `$1  "${member}",\n`);
  }
  await fs.writeFile(cargoToml, src);
};

const collectStubsFromRoot = async (root: string) => {
  const stubs: StubFile[] = [];
  for (const file of await collect(walkFiles(root))) {
    if (!file.endsWith(".rs")) continue;
    const rel = path.relative(root, file).replaceAll(path.sep, "/");
    stubs.push({ rel, content: await fs.readFile(file, "utf8") });
  }
  return stubs;
};

const collectSourceStubs = async () => {
  const stubs: StubFile[] = [];
  for (const crate of leanSplitCrates) {
    const root = path.join(rustDir, ffiCrateForLeanCrate(crate), "src/ffi");
    stubs.push(...await collectStubsFromRoot(root));
  }
  return stubs;
};

const filesByCrate = new Map<LeanSplitCrate, StubFile[]>();
for (const crate of leanSplitCrates) filesByCrate.set(crate, []);

for (const stub of await collectSourceStubs()) {
  const rel = stub.rel;
  const crate = leanSplitCrateForRel(rel);
  filesByCrate.get(crate)!.push(stub);
}

const ffiCrates: string[] = [];
for (const [crate, files] of filesByCrate) {
  if (files.length === 0) continue;
  await writeFfiCrate(crate, files);
  ffiCrates.push(ffiCrateForLeanCrate(crate));
}

await updateWorkspaceMembers(ffiCrates);

console.error(`updated ${ffiCrates.length} split Lean FFI crates: ${ffiCrates.join(", ")}`);
