[package]
name = "gen_lean"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
gen_lean_part_1 = { path = "../gen_lean_part_1" }
gen_lean_part_2 = { path = "../gen_lean_part_2" }
gen_lean_part_3 = { path = "../gen_lean_part_3" }
gen_lean_part_4 = { path = "../gen_lean_part_4" }
gen_lean_part_5 = { path = "../gen_lean_part_5" }
