# Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
# Released under Apache 2.0 license as described in the file LICENSE.

[package]
name = "lean_runtime"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = ["std"]
std = []
export-runtime-ffi = []
small_allocator = []
default-max-heartbeat = []
default-max-memory = []
use_gmp = []
lsan = []

[build-dependencies]
pkg-config = "0.3"

[dependencies]
libc = "0.2"
libuv-sys2 = "1.52.2"


[lib]
crate-type = ["rlib", "staticlib"]
