# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake

# The command to remove a file.
RM = /nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/srghma/projects/lean4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/srghma/projects/lean4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/srghma/projects/lean4/CMakeFiles /home/srghma/projects/lean4//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/srghma/projects/lean4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mimalloc

# Build rule for target.
mimalloc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc
.PHONY : mimalloc

# fast build rule for target.
mimalloc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mimalloc.dir/build.make CMakeFiles/mimalloc.dir/build
.PHONY : mimalloc/fast

#=============================================================================
# Target rules for targets named stage0

# Build rule for target.
stage0: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stage0
.PHONY : stage0

# fast build rule for target.
stage0/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stage0.dir/build.make CMakeFiles/stage0.dir/build
.PHONY : stage0/fast

#=============================================================================
# Target rules for targets named stage1

# Build rule for target.
stage1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stage1
.PHONY : stage1

# fast build rule for target.
stage1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stage1.dir/build.make CMakeFiles/stage1.dir/build
.PHONY : stage1/fast

#=============================================================================
# Target rules for targets named stage1-configure

# Build rule for target.
stage1-configure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stage1-configure
.PHONY : stage1-configure

# fast build rule for target.
stage1-configure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stage1-configure.dir/build.make CMakeFiles/stage1-configure.dir/build
.PHONY : stage1-configure/fast

#=============================================================================
# Target rules for targets named stage2

# Build rule for target.
stage2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stage2
.PHONY : stage2

# fast build rule for target.
stage2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stage2.dir/build.make CMakeFiles/stage2.dir/build
.PHONY : stage2/fast

#=============================================================================
# Target rules for targets named stage2-configure

# Build rule for target.
stage2-configure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stage2-configure
.PHONY : stage2-configure

# fast build rule for target.
stage2-configure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stage2-configure.dir/build.make CMakeFiles/stage2-configure.dir/build
.PHONY : stage2-configure/fast

#=============================================================================
# Target rules for targets named stage3

# Build rule for target.
stage3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stage3
.PHONY : stage3

# fast build rule for target.
stage3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stage3.dir/build.make CMakeFiles/stage3.dir/build
.PHONY : stage3/fast

#=============================================================================
# Target rules for targets named update-stage0

# Build rule for target.
update-stage0: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update-stage0
.PHONY : update-stage0

# fast build rule for target.
update-stage0/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/update-stage0.dir/build.make CMakeFiles/update-stage0.dir/build
.PHONY : update-stage0/fast

#=============================================================================
# Target rules for targets named update-stage0-commit

# Build rule for target.
update-stage0-commit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update-stage0-commit
.PHONY : update-stage0-commit

# fast build rule for target.
update-stage0-commit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/update-stage0-commit.dir/build.make CMakeFiles/update-stage0-commit.dir/build
.PHONY : update-stage0-commit/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named check-stage3

# Build rule for target.
check-stage3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check-stage3
.PHONY : check-stage3

# fast build rule for target.
check-stage3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check-stage3.dir/build.make CMakeFiles/check-stage3.dir/build
.PHONY : check-stage3/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... check-stage3"
	@echo "... mimalloc"
	@echo "... stage0"
	@echo "... stage1"
	@echo "... stage1-configure"
	@echo "... stage2"
	@echo "... stage2-configure"
	@echo "... stage3"
	@echo "... test"
	@echo "... update-stage0"
	@echo "... update-stage0-commit"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

