# Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
# Released under Apache 2.0 license as described in the file LICENSE.

[workspace]
members = [
  "leanh",
  "runtime",
  "gen_init",
  "gen_std",
  "gen_lean",
  "lake",
  "lean_checker",
  "lean_ir",
  "lean_shell",
  "leanc",
]
resolver = "2"

[profile.dev]
panic = "abort"
codegen-units = 1
lto = false

[profile.release]
panic = "abort"
debug = true
codegen-units = 1
lto = false
