# Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
# Released under Apache 2.0 license as described in the file LICENSE.

[workspace]
members = [
  "leanh_l1",
  "leanh_l1_initializers",
  "gen_init_ffi",
  # "leanh_l2",
  # "runtime",
  # "gen_init",
  # "gen_std_ffi",
  # "gen_std",
  # "gen_lean_ffi",
  # "gen_lean_part_1",
  # "gen_lean_part_2",
  # "gen_lean_part_3",
  # "gen_lean_part_4",
  # "gen_lean_part_5",
  # "gen_lean",
  # "lake_ffi",
  # "lake",
  # "lean_checker",
  # "lean_ir",
  # "leanc",
  # "lean_shell",
]
resolver = "2"

[profile.dev]
panic = "abort"
codegen-units = 1
lto = false

[profile.release]
panic = "abort"
debug = true
codegen-units = 1
lto = false
