[package]
name = "leanh_l1"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
# llvm-sys = "191"
# libc-stdhandle = "0.1"
libc = "0.2"
# libm = "0.2"
libloading = "0.9"
libmimalloc-sys = { version = "0.1", features = ["extended"] }
gmp-mpfr-sys = { version = "1.7", default-features = false }
# libuv-sys2 = "1.52.2"
# sysinfo = "0.39.5"
# thread-id = "5"

[lints.clippy]
missing_safety_doc = "allow"
