# Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
# Released under Apache 2.0 license as described in the file LICENSE.

[package]
name = "runtime"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = ["std"]
std = []
default-max-heartbeat = []
default-max-memory = []
# gen-init = []
# gen-std = []
# gen-lean = []
# gen-lake = []
# gen-tools = []

[dependencies]
leanh = { path = "../leanh" }
llvm-sys = "191"
libc-stdhandle = "0.1"
libc = "0.2"
libm = "0.2"
libloading = "0.9"
libmimalloc-sys = { version = "0.1", features = ["extended"] }
gmp-mpfr-sys = { version = "1.7", default-features = false }
libuv-sys2 = "1.52.2"
sysinfo = "0.39.5"
thread-id = "5"

[target.'cfg(target_os = "macos")'.dependencies]
mach2 = "0.6"

[lib]
crate-type = ["rlib"]

[lints.rust]
unused_imports = "warn"    # Or "deny" to break the build on unused imports
redundant_imports = "warn" # Or "deny" to break on redundant imports

[lints.clippy]
missing_safety_doc = "allow"
wildcard_imports = "deny"
enum_glob_use = "deny"
