#ifndef LEAN_H
#define LEAN_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
/* ── LEAN_EXPORT: visibility for symbols in EmitC.lean-generated C files ─── */
#if defined(_WIN32)
#  define LEAN_EXPORT __declspec(dllexport)
#elif defined(__GNUC__) || defined(__clang__)
#  define LEAN_EXPORT __attribute__((visibility("default")))
#else
#  define LEAN_EXPORT
#endif

#if defined(_MSC_VER)
#  define LEAN_NORETURN __declspec(noreturn)
#elif defined(__GNUC__) || defined(__clang__)
#  define LEAN_NORETURN __attribute__((noreturn))
#else
#  define LEAN_NORETURN
#endif


typedef uintptr_t Size;

typedef struct lean_object {
  int32_t m_rc;
  uint16_t m_cs_sz;
  uint8_t m_other;
  uint8_t m_tag;
} lean_object;

typedef struct lean_external_class {
  void (*m_finalize)(void*);
  void (*m_foreach)(void*, struct lean_object*);
} lean_external_class;

/* ── LeanMpzRepr: conditional GMP bignum representation ─────────────────── */
#ifdef LEAN_USE_GMP
typedef struct LeanMpzGmp LeanMpzRepr[1];
#else
typedef struct LeanMpzNonGmp LeanMpzRepr;
#endif

uint8_t lean_is_scalar(struct lean_object *obj);
struct lean_object *lean_box(Size value);
struct lean_object *lean_alloc_ctor(unsigned int tag, unsigned int num_objs, unsigned int scalar_sz);
void lean_dec_ref(struct lean_object *obj);
Size lean_unbox(const struct lean_object *obj);
bool lean_io_result_is_ok(struct lean_object *obj);
void lean_io_result_show_error(struct lean_object *r);
void lean_io_mark_end_initialization(void);
void lean_mark_persistent(struct lean_object *o);
struct lean_object *lean_cstr_to_nat(const char *n);
void *lean_sys_alloc(Size size);
void lean_sys_free_sized(void *ptr, Size size);
void lean_init_task_manager(void);
void lean_init_task_manager_using(unsigned int num_workers);
void lean_finalize_task_manager(void);
struct lean_object *lean_run_main(struct lean_object *(*main_fn)(int, char **), int argc, char **argv);
struct lean_object *lean_apply_1(struct lean_object *f, struct lean_object *a1);
struct lean_object *lean_apply_2(struct lean_object *f, struct lean_object *a1, struct lean_object *a2);
struct lean_object *lean_apply_3(struct lean_object *f, struct lean_object *a1, struct lean_object *a2, struct lean_object *a3);
struct lean_object *lean_apply_4(struct lean_object *f, struct lean_object *a1, struct lean_object *a2, struct lean_object *a3, struct lean_object *a4);
struct lean_object *lean_apply_5(struct lean_object *f, struct lean_object *a1, struct lean_object *a2, struct lean_object *a3, struct lean_object *a4, struct lean_object *a5);
struct lean_object *lean_apply_6(struct lean_object *f, struct lean_object *a1, struct lean_object *a2, struct lean_object *a3, struct lean_object *a4, struct lean_object *a5, struct lean_object *a6);
struct lean_object *lean_apply_7(struct lean_object *f, struct lean_object *a1, struct lean_object *a2, struct lean_object *a3, struct lean_object *a4, struct lean_object *a5, struct lean_object *a6, struct lean_object *a7);
struct lean_object *lean_apply_8(struct lean_object *f, struct lean_object *a1, struct lean_object *a2, struct lean_object *a3, struct lean_object *a4, struct lean_object *a5, struct lean_object *a6, struct lean_object *a7, struct lean_object *a8);
struct lean_object *lean_apply_9(struct lean_object *f, struct lean_object *a1, struct lean_object *a2, struct lean_object *a3, struct lean_object *a4, struct lean_object *a5, struct lean_object *a6, struct lean_object *a7, struct lean_object *a8, struct lean_object *a9);
struct lean_object *lean_apply_10(struct lean_object *f, struct lean_object *a1, struct lean_object *a2, struct lean_object *a3, struct lean_object *a4, struct lean_object *a5, struct lean_object *a6, struct lean_object *a7, struct lean_object *a8, struct lean_object *a9, struct lean_object *a10);
struct lean_object *lean_apply_11(struct lean_object *f, struct lean_object *a1, struct lean_object *a2, struct lean_object *a3, struct lean_object *a4, struct lean_object *a5, struct lean_object *a6, struct lean_object *a7, struct lean_object *a8, struct lean_object *a9, struct lean_object *a10, struct lean_object *a11);
struct lean_object *lean_apply_12(struct lean_object *f, struct lean_object *a1, struct lean_object *a2, struct lean_object *a3, struct lean_object *a4, struct lean_object *a5, struct lean_object *a6, struct lean_object *a7, struct lean_object *a8, struct lean_object *a9, struct lean_object *a10, struct lean_object *a11, struct lean_object *a12);
struct lean_object *lean_apply_13(struct lean_object *f, struct lean_object *a1, struct lean_object *a2, struct lean_object *a3, struct lean_object *a4, struct lean_object *a5, struct lean_object *a6, struct lean_object *a7, struct lean_object *a8, struct lean_object *a9, struct lean_object *a10, struct lean_object *a11, struct lean_object *a12, struct lean_object *a13);
struct lean_object *lean_apply_14(struct lean_object *f, struct lean_object *a1, struct lean_object *a2, struct lean_object *a3, struct lean_object *a4, struct lean_object *a5, struct lean_object *a6, struct lean_object *a7, struct lean_object *a8, struct lean_object *a9, struct lean_object *a10, struct lean_object *a11, struct lean_object *a12, struct lean_object *a13, struct lean_object *a14);
struct lean_object *lean_apply_15(struct lean_object *f, struct lean_object *a1, struct lean_object *a2, struct lean_object *a3, struct lean_object *a4, struct lean_object *a5, struct lean_object *a6, struct lean_object *a7, struct lean_object *a8, struct lean_object *a9, struct lean_object *a10, struct lean_object *a11, struct lean_object *a12, struct lean_object *a13, struct lean_object *a14, struct lean_object *a15);
struct lean_object *lean_apply_16(struct lean_object *f, struct lean_object *a1, struct lean_object *a2, struct lean_object *a3, struct lean_object *a4, struct lean_object *a5, struct lean_object *a6, struct lean_object *a7, struct lean_object *a8, struct lean_object *a9, struct lean_object *a10, struct lean_object *a11, struct lean_object *a12, struct lean_object *a13, struct lean_object *a14, struct lean_object *a15, struct lean_object *a16);

typedef struct {
_Atomic(int) state;
_Atomic(int) lock;
} lean_once_cell_t;

#define LEAN_ONCE_CELL_INITIALIZER { .state = 0, .lock = 0 }

typedef struct {
lean_object m_header;
lean_object * m_objs[];
} lean_ctor_object;
#define LEAN_SCALAR_PTR_LITERAL(b1, b2, b3, b4, b5, b6, b7, b8) (lean_object*)((uint64_t)b1 | ((uint64_t)b2 << 8) | ((uint64_t)b3 << 16) | ((uint64_t)b4 << 24) | ((uint64_t)b5 << 32) | ((uint64_t)b6 << 40) | ((uint64_t)b7 << 48) | ((uint64_t)b8 << 56))

static inline unsigned lean_obj_tag(lean_object * o) {
if (lean_is_scalar(o)) {
return (unsigned)((size_t)(o) >> 1);
} else {
return o->m_tag;
}
}

static inline lean_object * lean_unsigned_to_nat(unsigned n) {
return lean_box((size_t)n);
}

LEAN_EXPORT lean_object* lean_obj_once_cold(lean_object** loc, lean_once_cell_t* tok, lean_object* (*init)(void));

static inline lean_object* lean_obj_once(lean_object** loc, lean_once_cell_t* tok, lean_object* (*init)(void)) {
if (tok->state == 1) {
return *loc;
} else {
return lean_obj_once_cold(loc, tok, init);
}
}
LEAN_EXPORT uint8_t lean_uint8_once_cold(uint8_t* loc, lean_once_cell_t* tok, uint8_t (*init)(void));
LEAN_EXPORT uint16_t lean_uint16_once_cold(uint16_t* loc, lean_once_cell_t* tok, uint16_t (*init)(void));
LEAN_EXPORT uint32_t lean_uint32_once_cold(uint32_t* loc, lean_once_cell_t* tok, uint32_t (*init)(void));
LEAN_EXPORT uint64_t lean_uint64_once_cold(uint64_t* loc, lean_once_cell_t* tok, uint64_t (*init)(void));
LEAN_EXPORT uintptr_t lean_usize_once_cold(uintptr_t* loc, lean_once_cell_t* tok, uintptr_t (*init)(void));
LEAN_EXPORT float lean_float32_once_cold(float* loc, lean_once_cell_t* tok, float (*init)(void));
LEAN_EXPORT double lean_float_once_cold(double* loc, lean_once_cell_t* tok, double (*init)(void));

static inline uint8_t lean_uint8_once(uint8_t* loc, lean_once_cell_t* tok, uint8_t (*init)(void)) {
if (tok->state == 1) {
return *loc;
} else {
return lean_uint8_once_cold(loc, tok, init);
}
}

static inline uint16_t lean_uint16_once(uint16_t* loc, lean_once_cell_t* tok, uint16_t (*init)(void)) {
if (tok->state == 1) {
return *loc;
} else {
return lean_uint16_once_cold(loc, tok, init);
}
}

static inline uint32_t lean_uint32_once(uint32_t* loc, lean_once_cell_t* tok, uint32_t (*init)(void)) {
if (tok->state == 1) {
return *loc;
} else {
return lean_uint32_once_cold(loc, tok, init);
}
}

static inline uint64_t lean_uint64_once(uint64_t* loc, lean_once_cell_t* tok, uint64_t (*init)(void)) {
if (tok->state == 1) {
return *loc;
} else {
return lean_uint64_once_cold(loc, tok, init);
}
}

static inline uintptr_t lean_usize_once(uintptr_t* loc, lean_once_cell_t* tok, uintptr_t (*init)(void)) {
if (tok->state == 1) {
return *loc;
} else {
return lean_usize_once_cold(loc, tok, init);
}
}

static inline float lean_float32_once(float* loc, lean_once_cell_t* tok, float (*init)(void)) {
if (tok->state == 1) {
return *loc;
} else {
return lean_float32_once_cold(loc, tok, init);
}
}

static inline double lean_float_once(double* loc, lean_once_cell_t* tok, double (*init)(void)) {
if (tok->state == 1) {
return *loc;
} else {
return lean_float_once_cold(loc, tok, init);
}
}

static inline void lean_inc_ref(lean_object *obj) {
if (obj->m_rc > 0) {
obj->m_rc += 1;
} else if (obj->m_rc < 0) {
__atomic_fetch_add(&obj->m_rc, 1, __ATOMIC_RELAXED);
}
}

static inline void lean_inc_ref_n(lean_object *obj, uintptr_t n) {
for (uintptr_t i = 0; i < n; ++i) {
lean_inc_ref(obj);
}
}

static inline void lean_dec_ref_known(lean_object *obj, uintptr_t n) {
for (uintptr_t i = 0; i < n; ++i) {
lean_dec_ref(obj);
}
}

static inline void lean_del_object(lean_object *obj) {
lean_dec_ref(obj);
}

static inline void lean_ctor_set_tag(lean_object *o, uint8_t tag) {
o->m_tag = tag;
}

static inline uint8_t lean_ctor_get_uint8(lean_object *obj, uintptr_t offset) {
return *((uint8_t *)((uint8_t *)(obj + 1) + offset));
}

static inline uint16_t lean_ctor_get_uint16(lean_object *obj, uintptr_t offset) {
return *((uint16_t *)((uint8_t *)(obj + 1) + offset));
}

static inline uint32_t lean_ctor_get_uint32(lean_object *obj, uintptr_t offset) {
return *((uint32_t *)((uint8_t *)(obj + 1) + offset));
}

static inline uint64_t lean_ctor_get_uint64(lean_object *obj, uintptr_t offset) {
return *((uint64_t *)((uint8_t *)(obj + 1) + offset));
}

static inline uintptr_t lean_ctor_get_usize(lean_object *obj, uintptr_t offset) {
return *((uintptr_t *)((uint8_t *)(obj + 1) + offset));
}

static inline float lean_ctor_get_float32(lean_object *obj, uintptr_t offset) {
return *((float *)((uint8_t *)(obj + 1) + offset));
}

static inline double lean_ctor_get_float(lean_object *obj, uintptr_t offset) {
return *((double *)((uint8_t *)(obj + 1) + offset));
}

static inline void lean_ctor_set_uint8(lean_object *obj, uintptr_t offset, uint8_t value) {
*((uint8_t *)((uint8_t *)(obj + 1) + offset)) = value;
}

static inline void lean_ctor_set_uint16(lean_object *obj, uintptr_t offset, uint16_t value) {
*((uint16_t *)((uint8_t *)(obj + 1) + offset)) = value;
}

static inline void lean_ctor_set_uint32(lean_object *obj, uintptr_t offset, uint32_t value) {
*((uint32_t *)((uint8_t *)(obj + 1) + offset)) = value;
}

static inline void lean_ctor_set_uint64(lean_object *obj, uintptr_t offset, uint64_t value) {
*((uint64_t *)((uint8_t *)(obj + 1) + offset)) = value;
}

static inline void lean_ctor_set_usize(lean_object *obj, uintptr_t offset, uintptr_t value) {
*((uintptr_t *)((uint8_t *)(obj + 1) + offset)) = value;
}

static inline void lean_ctor_set_float32(lean_object *obj, uintptr_t offset, float value) {
*((float *)((uint8_t *)(obj + 1) + offset)) = value;
}

static inline void lean_ctor_set_float(lean_object *obj, uintptr_t offset, double value) {
*((double *)((uint8_t *)(obj + 1) + offset)) = value;
}

static inline struct lean_object *lean_box_uint64(uint64_t v) {
struct lean_object *r = lean_alloc_ctor(0, 0, sizeof(uint64_t));
lean_ctor_set_uint64(r, 0, v);
return r;
}

static inline uint64_t lean_unbox_uint64(struct lean_object *obj) {
return lean_ctor_get_uint64(obj, 0);
}

static inline struct lean_object *lean_box_usize(uintptr_t v) {
return lean_box((Size)v);
}

static inline uintptr_t lean_unbox_usize(struct lean_object *obj) {
return lean_unbox(obj);
}

static inline bool lean_io_result_is_error(struct lean_object *obj) {
return !lean_io_result_is_ok(obj);
}

typedef struct lean_external_object {
  struct lean_object m_header;
  struct lean_external_class *m_class;
  void *m_data;
} lean_external_object;

typedef struct lean_thunk_object {
  struct lean_object m_header;
  struct lean_object *m_closure;
  struct lean_object *m_value;
} lean_thunk_object;

typedef struct lean_ref_object {
  struct lean_object m_header;
  struct lean_object *m_value;
} lean_ref_object;

typedef struct lean_promise_object {
  struct lean_object m_header;
  struct lean_object *result;
} lean_promise_object;

typedef struct lean_array_object {
  struct lean_object m_header;
  Size m_size;
  Size m_capacity;
  struct lean_object *m_data[];
} lean_array_object;

typedef struct lean_string_object {
  struct lean_object m_header;
  Size m_size;
  Size m_capacity;
  Size m_length;
  char m_data[];
} lean_string_object;

typedef struct lean_sarray_object {
  struct lean_object m_header;
  Size m_size;
  Size m_capacity;
  uint8_t m_data[];
} lean_sarray_object;

typedef struct lean_closure_object {
  struct lean_object m_header;
  void *m_fun;
  uint16_t m_arity;
  uint16_t m_num_fixed;
  struct lean_object *m_objs[];
} lean_closure_object;

extern uint8_t *lean_alloc_export(Size size);

extern void lean_dealloc_export(uint8_t *obj, Size size);

extern struct lean_object *lean_mk_string(const char *text);

extern struct lean_object *lean_name_mk_string(struct lean_object *prefix, struct lean_object *s);

extern struct lean_object *lean_mk_io_user_error(struct lean_object *msg);

extern struct lean_object *lean_mk_io_error_invalid_argument(uint32_t errnum,
                                                             struct lean_object *details);

LEAN_NORETURN void lean_internal_panic(const char *msg);
LEAN_NORETURN void lean_internal_panic_out_of_memory(void);
LEAN_NORETURN void lean_internal_panic_unreachable(void);
LEAN_NORETURN void lean_internal_panic_rc_overflow(void);
LEAN_NORETURN void lean_internal_panic_overflow(void);

extern struct lean_object *lean_alloc_object(Size size);

extern struct lean_object *lean_mk_embedded_nul_error_c(struct lean_object *str);

extern struct lean_object *lean_array_push(struct lean_object *array, struct lean_object *value);

extern struct lean_external_class *lean_register_external_class(void (*finalize)(void*),
                                                                void (*foreach)(void*,
                                                                                struct lean_object*));

extern struct lean_object *lean_runtime_alloc_external(struct lean_external_class *class_,
                                                       void *data);

extern void *lean_runtime_get_external_data(struct lean_object *obj);

extern struct lean_object *lean_runtime_alloc_ctor(unsigned int tag,
                                                   unsigned int num_objs,
                                                   unsigned int scalar_size);

extern void lean_runtime_ctor_set(struct lean_object *obj,
                                  unsigned int index,
                                  struct lean_object *value);

extern struct lean_object *lean_decode_uv_error(int errnum, struct lean_object *fname);

extern struct lean_object *lean_big_int64_to_int(int64_t n);

extern struct lean_object *lean_big_uint64_to_nat(uint64_t n);

extern uint64_t lean_uint64_of_big_nat(struct lean_object *n);

extern struct lean_object *lean_decode_io_error(int errnum, struct lean_object *fname);

extern struct lean_object *lean_io_eprintln(struct lean_object *msg);

extern struct lean_object *lean_io_wrap_handle_c(void *fp);

extern struct lean_object *lean_io_error_to_string(struct lean_object *err);

extern struct lean_object *lean_options_get_empty(struct lean_object*);

extern uint8_t lean_options_get_bool(struct lean_object *opts,
                                     struct lean_object *name,
                                     uint8_t default_value);

extern struct lean_object *lean_options_update_bool(struct lean_object *opts,
                                                    struct lean_object *name,
                                                    uint8_t value);

extern struct lean_object *lean_get_init_fn_name_for(struct lean_object *env,
                                                     struct lean_object *name);

extern uint8_t lean_get_profiler(struct lean_object *opts);

extern double lean_get_profiler_threshold(struct lean_object *opts);

extern void initialize_alloc(void);

extern void finalize_alloc(void);

extern void initialize_object(void);

extern void finalize_object(void);

extern void initialize_io(void);

extern void finalize_io(void);

extern void initialize_thread(void);

extern void finalize_thread(void);

extern void initialize_formatter(void);

extern void finalize_formatter(void);

extern void initialize_print(void);

extern void finalize_print(void);

extern void initialize_num(void);

extern void finalize_num(void);

extern void initialize_annotation(void);

extern void finalize_annotation(void);

extern void initialize_library_util(void);

extern void finalize_library_util(void);

extern void initialize_time_task(void);

extern void finalize_time_task(void);

extern void initialize_level(void);

extern void finalize_level(void);

extern void initialize_expr(void);

extern void finalize_expr(void);

extern void initialize_declaration(void);

extern void finalize_declaration(void);

extern void initialize_type_checker(void);

extern void finalize_type_checker(void);

extern void initialize_environment(void);

extern void finalize_environment(void);

extern void initialize_local_ctx(void);

extern void finalize_local_ctx(void);

extern void initialize_inductive(void);

extern void finalize_inductive(void);

extern void initialize_quot(void);

extern void finalize_quot(void);

extern void initialize_trace(void);

extern void finalize_trace(void);

extern void init_default_print_fn_impl(void);

extern struct lean_object *initialize_Init(uint8_t builtin);

extern struct lean_object *initialize_Std(uint8_t builtin);

extern struct lean_object *initialize_Lean(uint8_t builtin);

/**
 * Thin wrapper around lean_runtime_alloc_ctor (mirrors lean.h lean_alloc_ctor).
 */
struct lean_object *lean_alloc_ctor(unsigned int tag,
                                    unsigned int num_objs,
                                    unsigned int scalar_sz);

bool lean_is_exclusive(struct lean_object *o);

Size lean_sarray_size(struct lean_object *obj);

Size lean_sarray_capacity(struct lean_object *obj);

Size lean_array_capacity(struct lean_object *obj);

unsigned int lean_sarray_elem_size(struct lean_object *obj);

const uint8_t *lean_sarray_cptr(struct lean_object *obj);

uint64_t hash_str(Size len, const uint8_t *text, uint64_t seed);

uint8_t lean_is_scalar(struct lean_object *obj);

void lean_inc(struct lean_object *obj);

void lean_inc_n(struct lean_object *obj, uintptr_t n);

void lean_dec(struct lean_object *obj);

struct lean_object *lean_box_uint32(uint32_t v);

uint32_t lean_unbox_uint32(struct lean_object *obj);

struct lean_object *lean_box_float(double v);

double lean_unbox_float(struct lean_object *obj);

struct lean_object *lean_box_float32(float v);

float lean_unbox_float32(struct lean_object *obj);

struct lean_object *lean_int64_to_int(int64_t value);

struct lean_object *lean_usize_to_nat(uintptr_t value);

struct lean_object *lean_nat_add(struct lean_object *a, struct lean_object *b);

struct lean_object *lean_nat_sub(struct lean_object *a, struct lean_object *b);

uint32_t lean_char_default_value(void);

Size lean_string_capacity(struct lean_object *obj);

Size lean_array_size(struct lean_object *obj);

Size lean_string_size(struct lean_object *obj);

struct lean_object *lean_alloc_object(Size size);

struct lean_object *lean_alloc_small_object(Size size);

struct lean_object *lean_alloc_ctor_memory(Size size);

struct lean_object *lean_alloc_array(uintptr_t size, uintptr_t capacity);

struct lean_object *lean_alloc_sarray(unsigned int elem_size, uintptr_t size, uintptr_t capacity);

struct lean_object *lean_alloc_string(uintptr_t size, uintptr_t capacity, uintptr_t len);

void lean_free_small_object(struct lean_object *obj);

uintptr_t lean_small_object_size(struct lean_object *obj);

void lean_runtime_free_mpz_object(struct lean_object *obj);

bool _ZNK4lean3mpz9is_size_tEv(const LeanMpzRepr *self_);

uintptr_t _ZNK4lean3mpz10get_size_tEv(const LeanMpzRepr *self_);

struct lean_object **lean_array_cptr(struct lean_object *obj);

uintptr_t lean_array_byte_size(struct lean_object *obj);

uintptr_t lean_array_data_byte_size(struct lean_object *obj);

uintptr_t lean_sarray_byte_size(struct lean_object *obj);

uintptr_t lean_sarray_data_byte_size(struct lean_object *obj);

uintptr_t lean_string_byte_size(struct lean_object *obj);

uintptr_t lean_string_data_byte_size(struct lean_object *obj);

struct lean_object **lean_closure_arg_cptr(struct lean_object *obj);

void lean_closure_set(struct lean_object *obj, unsigned int i, struct lean_object *value);

unsigned int lean_closure_num_fixed(struct lean_object *obj);

uintptr_t lean_closure_byte_size(struct lean_object *obj);

uintptr_t lean_closure_capacity(struct lean_object *obj);

uintptr_t lean_closure_data_byte_size(struct lean_object *obj);

unsigned int lean_ctor_num_objs(struct lean_object *obj);

struct lean_object **lean_ctor_obj_cptr(struct lean_object *obj);

struct lean_object *lean_runtime_alloc_ctor(unsigned int tag,
                                            unsigned int num_objs,
                                            unsigned int scalar_size);

void lean_runtime_ctor_set(struct lean_object *obj, unsigned int index, struct lean_object *value);

void lean_set_st_header(struct lean_object *o, uint8_t tag, uint8_t other);

struct lean_object *lean_ctor_get(struct lean_object *obj, unsigned int idx);

void lean_ctor_set(struct lean_object *obj, unsigned int idx, struct lean_object *val);

void lean_dec_ref(struct lean_object *obj);

uintptr_t lean_string_len(struct lean_object *obj);

bool validate_utf8(const uint8_t *s, uintptr_t sz, uintptr_t *pos, uintptr_t *i);

bool validate_utf8_one(const uint8_t *s, uintptr_t sz, uintptr_t pos);

unsigned int push_unicode_scalar(char *dst, unsigned int code);

struct lean_object *_ZN4lean14io_wrap_handleEP8_IO_FILE(void *fp);

struct lean_object *_ZN4lean21mk_embedded_nul_errorEP11lean_object(struct lean_object *str);

struct lean_external_class *lean_register_external_class(void (*finalize)(void*),
                                                         void (*foreach)(void*, struct lean_object*));

struct lean_object *lean_runtime_alloc_external(struct lean_external_class *class_, void *data);

void *lean_runtime_get_external_data(struct lean_object *obj);

struct lean_external_object *lean_to_external(struct lean_object *obj);

struct lean_thunk_object *lean_to_thunk(struct lean_object *obj);

struct lean_ref_object *lean_to_ref(struct lean_object *obj);

struct lean_promise_object *lean_to_promise(struct lean_object *obj);

struct lean_object *lean_alloc_closure(void *fun, uint32_t arity, uint32_t num_fixed);

void free_sized(void *ptr, uintptr_t _sz);

const char *lean_string_cstr(struct lean_object *obj);

uint64_t lean_string_hash(struct lean_object *s);

uint8_t lean_name_eq(struct lean_object *n1, struct lean_object *n2);

Size lean_unbox(const struct lean_object *obj);

bool lean_io_result_is_ok(struct lean_object *obj);

struct lean_object *lean_io_result_mk_ok(struct lean_object *value);

struct lean_object *lean_io_result_mk_error(struct lean_object *error);

struct lean_object *lean_io_result_get_value(struct lean_object *obj);

struct lean_object *lean_io_result_get_error(struct lean_object *obj);

struct lean_object *lean_box(Size value);

extern intptr_t write(int32_t fd, const uint8_t *buf, uintptr_t count);

extern void abort(void);

void _ZN4lean21init_default_print_fnEv(void);

void lean_cxx_initialize_quot(void);

void lean_cxx_finalize_quot(void);

void lean_cxx_initialize_inductive(void);

void lean_cxx_finalize_inductive(void);

void lean_cxx_initialize_local_ctx(void);

void lean_cxx_finalize_local_ctx(void);

void lean_cxx_initialize_environment(void);

void lean_cxx_finalize_environment(void);

void lean_cxx_initialize_type_checker(void);

void lean_cxx_finalize_type_checker(void);

void lean_cxx_initialize_declaration(void);

void lean_cxx_finalize_declaration(void);

void lean_cxx_initialize_expr(void);

void lean_cxx_finalize_expr(void);

void lean_cxx_initialize_level(void);

void lean_cxx_finalize_level(void);

void lean_cxx_initialize_formatter(void);

void lean_cxx_finalize_formatter(void);

void lean_cxx_initialize_library_util(void);

void lean_cxx_finalize_library_util(void);

void lean_cxx_initialize_bool(void);

void lean_cxx_finalize_bool(void);

void lean_cxx_initialize_annotation(void);

void lean_cxx_finalize_annotation(void);

void lean_cxx_initialize_num(void);

void lean_cxx_finalize_num(void);

void lean_cxx_initialize_print(void);

void lean_cxx_finalize_print(void);

void lean_cxx_initialize_time_task(void);

void lean_cxx_finalize_time_task(void);

void lean_cxx_display_cumulative_profiling_times(void);

void lean_cxx_initialize_ir_interpreter(void);

void lean_cxx_finalize_ir_interpreter(void);

void _ZN4lean25initialize_ir_interpreterEv(void);

void _ZN4lean23finalize_ir_interpreterEv(void);

#endif  /* LEAN_H */
