// Generated by Lean ES6 emitter
import { lean_array_size, lean_array_uget_borrowed } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Array/Basic.js";
import { lean_usize_add, lean_usize_dec_lt } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/UInt/BasicAux.js";
import { lean_array_push } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test1$__closed__1 = lean_array_push([], "a");
export const test1$__closed__3 = lean_array_push([], "b");
export const test1$__closed__5 = lean_array_push([], "c");
export const test1$__closed__7 = lean_array_push([], "d");
export const test2 = (/* obj */ __uniq$1) => [...[...test1$__closed__1, ...[...[...[...[...[...test1$__closed__3, ...__uniq$1], ...__uniq$1], ...__uniq$1], ...__uniq$1], ...test1$__closed__5]], ...test1$__closed__7];
export const IO$print$__at__$printArray$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$printArray$spec__1 = (/* obj */ __uniq$1, /* USize */ __uniq$2, /* USize */ __uniq$3, /* UInt8 */ __uniq$4) => {
  while (true) {
    const __uniq$6 = __uniq$3 < __uniq$2;
    if (__uniq$6) {
      const __uniq$9 = lean_array_uget_borrowed(__uniq$1, __uniq$3);
      if (__uniq$4) {
        const __uniq$11 = IO$print$__at__$printArray$spec__0("\"");
        if (__uniq$11.tag === "EST$Out$ok") {
          const __uniq$12 = IO$print$__at__$printArray$spec__0(__uniq$9);
          if (__uniq$12.tag === "EST$Out$ok") {
            const __uniq$13 = IO$print$__at__$printArray$spec__0("\"");
            if (__uniq$13.tag === "EST$Out$ok") {
              const __uniq$16 = lean_usize_add(__uniq$3, 1);
              const _tmp_0 = __uniq$1;
              const _tmp_1 = __uniq$2;
              __uniq$1 = _tmp_0;
              __uniq$2 = _tmp_1;
              __uniq$3 = __uniq$16;
              __uniq$4 = 0;
              continue;
            } else if (__uniq$13.tag === "EST$Out$error") {
              return { tag: "EST$Out$error", _1: __uniq$13._1 };
            }
          } else if (__uniq$12.tag === "EST$Out$error") {
            return { tag: "EST$Out$error", _1: __uniq$12._1 };
          }
        } else if (__uniq$11.tag === "EST$Out$error") {
          return { tag: "EST$Out$error", _1: __uniq$11._1 };
        }
      } else {
        const __uniq$38 = IO$print$__at__$printArray$spec__0(", ");
        if (__uniq$38.tag === "EST$Out$ok") {
          const __uniq$11 = IO$print$__at__$printArray$spec__0("\"");
          if (__uniq$11.tag === "EST$Out$ok") {
            const __uniq$12 = IO$print$__at__$printArray$spec__0(__uniq$9);
            if (__uniq$12.tag === "EST$Out$ok") {
              const __uniq$13 = IO$print$__at__$printArray$spec__0("\"");
              if (__uniq$13.tag === "EST$Out$ok") {
                const __uniq$16 = lean_usize_add(__uniq$3, 1);
                const _tmp_0 = __uniq$1;
                const _tmp_1 = __uniq$2;
                __uniq$1 = _tmp_0;
                __uniq$2 = _tmp_1;
                __uniq$3 = __uniq$16;
                __uniq$4 = 0;
                continue;
              } else if (__uniq$13.tag === "EST$Out$error") {
                return { tag: "EST$Out$error", _1: __uniq$13._1 };
              }
            } else if (__uniq$12.tag === "EST$Out$error") {
              return { tag: "EST$Out$error", _1: __uniq$12._1 };
            }
          } else if (__uniq$11.tag === "EST$Out$error") {
            return { tag: "EST$Out$error", _1: __uniq$11._1 };
          }
        } else if (__uniq$38.tag === "EST$Out$error") {
          return { tag: "EST$Out$error", _1: __uniq$38._1 };
        }
      }
    } else {
      return { tag: "EST$Out$ok", _1: __uniq$4 };
    }
  }
};
export const test3$__closed__5 = lean_array_push([], "g");
export const IO$println$__at__$printArray$spec__2 = (/* obj */ __uniq$1) => IO$print$__at__$printArray$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main$__closed__1 = lean_array_push([], "xy");
export const test1 = (/* obj */ __uniq$1) => [...[...test1$__closed__1, ...[...test1$__closed__3, ...[...__uniq$1, ...[...__uniq$1, ...[...__uniq$1, ...[...__uniq$1, ...test1$__closed__5]]]]]], ...test1$__closed__7];
export const main$__closed__2 = test1(main$__closed__1);
export const printArray = (/* obj */ __uniq$1) => {
  const __uniq$3 = "#[";
  const __uniq$4 = IO$print$__at__$printArray$spec__0(__uniq$3);
  if (__uniq$4.tag === "EST$Out$ok") {
    const __uniq$6 = lean_array_size(__uniq$1);
    const __uniq$8 = __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$printArray$spec__1(__uniq$1, __uniq$6, 0, 1);
    if (__uniq$8.tag === "EST$Out$ok") {
      const __uniq$10 = IO$println$__at__$printArray$spec__2("]");
      return __uniq$10;
    } else if (__uniq$8.tag === "EST$Out$error") {
      return { tag: "EST$Out$error", _1: __uniq$8._1 };
    }
  } else if (__uniq$4.tag === "EST$Out$error") {
    return __uniq$4;
  }
};
export const main$__closed__3 = test2(main$__closed__1);
export const test3$__closed__1 = lean_array_push([], "e");
export const test3$__closed__3 = lean_array_push([], "f");
export const test3 = (/* obj */ __uniq$1) => [...[...[...[...test1$__closed__1, ...[...test1$__closed__3, ...[...__uniq$1, ...[...__uniq$1, ...[...__uniq$1, ...[...__uniq$1, ...test1$__closed__5]]]]]], ...test1$__closed__7], ...[...[...[...[...[...test3$__closed__1, ...__uniq$1], ...__uniq$1], ...__uniq$1], ...__uniq$1], ...test3$__closed__3]], ...test3$__closed__5];
export const main$__closed__4 = test3(main$__closed__1);
export const main = () => {
  const __uniq$2 = main$__closed__2;
  const __uniq$3 = printArray(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = printArray(main$__closed__3);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = printArray(main$__closed__4);
      return __uniq$7;
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};

main();
