// Generated by Lean ES6 emitter
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const TestEnum$baz$elim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const TestEnum$ctorIdx = (/* UInt8 */ __uniq$1) => {
  if (__uniq$1 === 0) {
    return 0;
  } else if (__uniq$1 === 1) {
    return 1;
  } else if (__uniq$1 === 2) {
    return 2;
  } else if (__uniq$1 === 3) {
    return 3;
  }
};
export const instBEqTestEnum$beq = (/* UInt8 */ __uniq$1, /* UInt8 */ __uniq$2) => TestEnum$ctorIdx(__uniq$1) === TestEnum$ctorIdx(__uniq$2);
export const test2 = (/* UInt8 */ __uniq$1) => __uniq$1 === 2;
export const instBEqTestEnum$__closed__0 = (x_1, x_2) => x_1 === x_2;
export const instBEqTestEnum = () => instBEqTestEnum$__closed__0;
export const test1 = (/* UInt8 */ __uniq$1) => 2 === __uniq$1;
export const TestEnum$bar$elim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const TestEnum$bar$elim = (/* UInt8 */ __uniq$2, /* tobj */ __uniq$4) => __uniq$4;
export const main$__closed__0 = test1(2);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* UInt8 */ __uniq$1) => {
  if (__uniq$1) {
    const __uniq$5 = "true" + String.fromCodePoint(10);
    const __uniq$6 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$5);
    return __uniq$6;
  } else {
    const __uniq$5 = "false" + String.fromCodePoint(10);
    const __uniq$6 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$5);
    return __uniq$6;
  }
};
export const main$__closed__1 = test2(0);
export const main = () => {
  const __uniq$2 = main$__closed__0;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__1);
    return __uniq$5;
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const TestEnum$ctorElim = (/* tobj */ __uniq$2, /* UInt8 */ __uniq$3, /* tobj */ __uniq$5) => __uniq$5;
export const TestEnum$qux$elim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const TestEnum$foo$elim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const TestEnum$baz$elim = (/* UInt8 */ __uniq$2, /* tobj */ __uniq$4) => __uniq$4;
export const TestEnum$foo$elim = (/* UInt8 */ __uniq$2, /* tobj */ __uniq$4) => __uniq$4;
export const TestEnum$toCtorIdx = (/* UInt8 */ __uniq$1) => TestEnum$ctorIdx(__uniq$1);
export const TestEnum$ctorElim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const TestEnum$qux$elim = (/* UInt8 */ __uniq$2, /* tobj */ __uniq$4) => __uniq$4;

main();
