// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test2 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => __uniq$1 + __uniq$3;
export const test1 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => __uniq$1 + __uniq$3;
export const test2$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1 + __uniq$2;
export const test3$__redArg$__lam__0 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1 + __uniq$2;
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main = () => {
  const __uniq$2 = 3 + 4;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$4 = IO$println$__at__$main$spec__0(__uniq$2);
    if (__uniq$4.tag === "EST$Out$ok") {
      const __uniq$5 = IO$println$__at__$main$spec__0(__uniq$2);
      return __uniq$5;
    } else if (__uniq$4.tag === "EST$Out$error") {
      return __uniq$4;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const test3 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => test3$__redArg$__lam__0.length - 1 === 0 ? () => test3$__redArg$__lam__0(__uniq$1) : test3$__redArg$__lam__0.length - 1 === 1 ? (x_1) => test3$__redArg$__lam__0(__uniq$1, x_1) : test3$__redArg$__lam__0.length - 1 === 2 ? (x_1, x_2) => test3$__redArg$__lam__0(__uniq$1, x_1, x_2) : (x_1, x_2, x_3) => test3$__redArg$__lam__0(__uniq$1, x_1, x_2, x_3);
export const test1$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1 + __uniq$2;
export const test3$__redArg = (/* tobj */ __uniq$1) => test3$__redArg$__lam__0.length - 1 === 0 ? () => test3$__redArg$__lam__0(__uniq$1) : test3$__redArg$__lam__0.length - 1 === 1 ? (x_1) => test3$__redArg$__lam__0(__uniq$1, x_1) : test3$__redArg$__lam__0.length - 1 === 2 ? (x_1, x_2) => test3$__redArg$__lam__0(__uniq$1, x_1, x_2) : (x_1, x_2, x_3) => test3$__redArg$__lam__0(__uniq$1, x_1, x_2, x_3);

main();
