// Generated by Lean ES6 emitter
import { lean_float_beq } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Float.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test1$__closed__0 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 10;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const test1$__closed__1 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 20;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const test1$__closed__2 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 30;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const test1 = (/* Float */ __uniq$1) => __uniq$1 === test1$__closed__0 ? "1" : __uniq$1 === test1$__closed__1 ? "2" : __uniq$1 === test1$__closed__2 ? "3" : "catch";
export const main$__closed__0 = test1(test1$__closed__2);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main$__closed__1 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 40;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const main$__closed__2 = test1(main$__closed__1);
export const main = () => {
  const __uniq$2 = main$__closed__0;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__2);
    return __uniq$5;
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};

main();
