// Generated by Lean ES6 emitter
import { lean_float_beq } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Float.js";
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { Repr$addAppParen } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Repr.js";
import { lean_string_length } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/String/Bootstrap.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const main$__closed__16 = { tag: "Column$two", _1: 4, _2: 5 };
export const Column$ctorElim$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1.tag === "Column$zero") {
    return __uniq$2;
  } else if (__uniq$1.tag === "Column$one") {
    const __uniq$4 = __uniq$2(__uniq$1._1);
    return __uniq$4;
  } else if (__uniq$1.tag === "Column$two") {
    const __uniq$7 = __uniq$2(__uniq$1._1, __uniq$1._2);
    return __uniq$7;
  }
};
export const Column$two$elim$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => Column$ctorElim$__redArg(__uniq$1, __uniq$2);
export const main$__closed__22 = (() => {
  const __uniq$1 = { tag: "Expr$zero" };
  const __uniq$2 = { tag: "Expr$add", _1: __uniq$1, _2: __uniq$1 };
  return __uniq$2;
})();
export const renderExpr = (/* tobj */ __uniq$1) => {
  if (__uniq$1.tag === "Expr$add") {
    const __uniq$5 = renderExpr(__uniq$1._1);
    const __uniq$9 = renderExpr(__uniq$1._2);
    return "Add(" + __uniq$5 + " " + __uniq$9 + ")";
  } else if (__uniq$1.tag === "Expr$mul") {
    const __uniq$16 = renderExpr(__uniq$1._1);
    const __uniq$20 = renderExpr(__uniq$1._2);
    return "Mul(" + __uniq$16 + " " + __uniq$20 + ")";
  } else if (__uniq$1.tag === "Expr$succ") {
    const __uniq$26 = renderExpr(__uniq$1._1);
    return "Succ(" + __uniq$26 + ")";
  } else if (__uniq$1.tag === "Expr$zero") {
    return "Zero";
  }
};
export const caseJacobs = (/* tobj */ __uniq$1) => {
  if (__uniq$1.tag === "Expr$add") {
    if (__uniq$1._1.tag === "Expr$zero") {
      if (__uniq$1._2.tag === "Expr$zero") {
        return "e1";
      } else {
        const __uniq$4 = renderExpr(__uniq$1);
        return "e7: " + __uniq$4;
      }
    } else if (__uniq$1._1.tag === "Expr$succ") {
      const __uniq$13 = renderExpr(__uniq$1._1._1);
      const __uniq$17 = renderExpr(__uniq$1._2);
      return "e3: " + __uniq$13 + " " + __uniq$17;
    } else if (__uniq$1._2.tag === "Expr$zero") {
      const __uniq$21 = renderExpr(__uniq$1._1);
      return "e6: " + __uniq$21;
    } else {
      const __uniq$4 = renderExpr(__uniq$1);
      return "e7: " + __uniq$4;
    }
  } else if (__uniq$1.tag === "Expr$mul") {
    if (__uniq$1._1.tag === "Expr$zero") {
      const __uniq$30 = renderExpr(__uniq$1._2);
      return "e2: " + __uniq$30;
    } else if (__uniq$1._1.tag === "Expr$add") {
      return __uniq$1._2.tag === "Expr$zero" ? "e4: " + renderExpr(__uniq$1._1) : "e5: " + renderExpr(__uniq$1._1._1) + " " + renderExpr(__uniq$1._1._2) + " " + renderExpr(__uniq$1._2);
    } else if (__uniq$1._2.tag === "Expr$zero") {
      const __uniq$26 = renderExpr(__uniq$1._1);
      return "e4: " + __uniq$26;
    } else {
      const __uniq$4 = renderExpr(__uniq$1);
      return "e7: " + __uniq$4;
    }
  } else {
    const __uniq$4 = renderExpr(__uniq$1);
    return "e7: " + __uniq$4;
  }
};
export const main$__closed__23 = caseJacobs(main$__closed__22);
export const Column$ctorIdx = (/* tobj */ __uniq$1) => {
  if (__uniq$1.tag === "Column$zero") {
    return 0;
  } else if (__uniq$1.tag === "Column$one") {
    return 1;
  } else if (__uniq$1.tag === "Column$two") {
    return 2;
  }
};
export const main$__closed__8 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 40;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const Column$zero$elim = (/* tobj */ __uniq$2, /* tobj */ __uniq$4) => Column$ctorElim$__redArg(__uniq$2, __uniq$4);
export const caseChar = (/* UInt32 */ __uniq$1) => __uniq$1 === 97 ? "1" : __uniq$1 === 98 ? "2" : __uniq$1 === 99 ? "3" : "catch";
export const main$__closed__24 = { tag: "Expr$succ", _1: { tag: "Expr$zero" } };
export const caseInt = (/* tobj */ __uniq$1) => __uniq$1 === 1 ? "1" : __uniq$1 === 2 ? "2" : __uniq$1 === 3 ? "3" : "catch";
export const instReprExpr$repr$__closed__1 = { tag: "Std$Format$text", _1: "Expr.zero" };
export const caseGrafting = (/* UInt8 */ __uniq$1, /* UInt8 */ __uniq$2, /* UInt8 */ __uniq$3) => __uniq$2 ? __uniq$1 ? __uniq$3 ? 4 : 3 : 2 : __uniq$3 ? 1 : 3;
export const main$__closed__11 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 0;
  const __uniq$3 = caseGrafting(__uniq$2, __uniq$1, __uniq$2);
  return __uniq$3;
})();
export const caseHeuristicPBA = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1.tag === "Column$one" ? __uniq$1._1 === 1 ? __uniq$2.tag === "Column$one" ? __uniq$2._1 === 1 ? 1 : 4 : 4 : __uniq$1._1 === 2 ? __uniq$2.tag === "Column$one" ? __uniq$2._1 === 2 ? 2 : 4 : 4 : 4 : __uniq$1.tag === "Column$two" ? __uniq$1._1 === 1 ? __uniq$2.tag === "Column$two" ? 3 : 4 : 4 : 4;
export const main$__closed__17 = caseHeuristicPBA({ tag: "Column$two", _1: 1, _2: 9 }, main$__closed__16);
export const caseNumber$__closed__2 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 30;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const instReprExpr$repr$__closed__4 = { tag: "Std$Format$append", _1: { tag: "Std$Format$text", _1: "Expr.add" }, _2: { tag: "Std$Format$line" } };
export const Expr$ctorElim$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1.tag === "Expr$succ" ? __uniq$2(__uniq$1._1) : __uniq$1.tag === "Expr$zero" ? __uniq$2 : __uniq$2(__uniq$1._1, __uniq$1._2);
export const Expr$ctorElim = (/* tobj */ __uniq$2, /* tobj */ __uniq$3, /* tobj */ __uniq$5) => Expr$ctorElim$__redArg(__uniq$3, __uniq$5);
export const caseNumber$__closed__1 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 20;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const caseNumber$__closed__0 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 10;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const caseNumber = (/* Float */ __uniq$1) => __uniq$1 === caseNumber$__closed__0 ? "1" : __uniq$1 === caseNumber$__closed__1 ? "2" : __uniq$1 === caseNumber$__closed__2 ? "3" : "catch";
export const main$__closed__9 = caseNumber(main$__closed__8);
export const instReprProduct3$repr$__redArg$__closed__5 = { tag: "Std$Format$text", _1: " := " };
export const instReprProduct3$repr$__redArg$__closed__9 = lean_string_length("{ ");
export const instReprProduct3$repr$__redArg$__closed__11 = { tag: "Std$Format$text", _1: "{ " };
export const instReprProduct3$repr$__redArg$__closed__12 = { tag: "Std$Format$text", _1: " }" };
export const instReprProduct3$repr$__redArg$__closed__14 = { tag: "Std$Format$text", _1: "c" };
export const instReprProduct3$repr$__redArg$__closed__16 = { tag: "Std$Format$text", _1: "," };
export const instReprProduct3$repr$__redArg$__closed__18 = { tag: "Std$Format$text", _1: "b" };
export const instReprProduct3$repr$__redArg = (/* obj */ __uniq$1) => {
  const __uniq$2 = __uniq$1._1;
  const __uniq$3 = __uniq$1._2;
  const __uniq$4 = __uniq$1._3;
  const __uniq$5 = instReprProduct3$repr$__redArg$__closed__5;
  const __uniq$6 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$nil" }, _2: { tag: "Std$Format$text", _1: "a" } }, _2: instReprProduct3$repr$__redArg$__closed__5 };
  const __uniq$7 = 5;
  const __uniq$65 = 0;
  const __uniq$66 = 0;
  const __uniq$67 = __uniq$2 < __uniq$66;
  if (__uniq$67) {
    const __uniq$70 = String(__uniq$2);
    const __uniq$72 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$70 }, __uniq$65);
    {
      const __uniq$47 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$72 } };
      __uniq$47._2 = 0;
      const __uniq$51 = { tag: "Std$Format$line" };
      const __uniq$55 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$6, _2: __uniq$47 }, _2: instReprProduct3$repr$__redArg$__closed__16 }, _2: __uniq$51 }, _2: instReprProduct3$repr$__redArg$__closed__18 }, _2: __uniq$5 };
      if (__uniq$3 < 0) {
        const __uniq$61 = String(__uniq$3);
        const __uniq$63 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$61 }, 0);
        {
          const __uniq$28 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$63 } };
          __uniq$28._2 = 0;
          const __uniq$34 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$55, _2: __uniq$28 }, _2: instReprProduct3$repr$__redArg$__closed__16 }, _2: __uniq$51 }, _2: instReprProduct3$repr$__redArg$__closed__14 }, _2: __uniq$5 };
          if (__uniq$4 < 0) {
            const __uniq$40 = String(__uniq$4);
            const __uniq$42 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$40 }, 0);
            {
              const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$42 } };
              __uniq$12._2 = 0;
              const __uniq$20 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprProduct3$repr$__redArg$__closed__9, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprProduct3$repr$__redArg$__closed__11, _2: { tag: "Std$Format$append", _1: __uniq$34, _2: __uniq$12 } }, _2: instReprProduct3$repr$__redArg$__closed__12 } } };
              __uniq$20._2 = 0;
              return __uniq$20;
            }
          } else {
            const __uniq$38 = String(__uniq$4);
            {
              const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$38 } } };
              __uniq$12._2 = 0;
              const __uniq$20 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprProduct3$repr$__redArg$__closed__9, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprProduct3$repr$__redArg$__closed__11, _2: { tag: "Std$Format$append", _1: __uniq$34, _2: __uniq$12 } }, _2: instReprProduct3$repr$__redArg$__closed__12 } } };
              __uniq$20._2 = 0;
              return __uniq$20;
            }
          }
        }
      } else {
        const __uniq$59 = String(__uniq$3);
        {
          const __uniq$28 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$59 } } };
          __uniq$28._2 = 0;
          const __uniq$34 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$55, _2: __uniq$28 }, _2: instReprProduct3$repr$__redArg$__closed__16 }, _2: __uniq$51 }, _2: instReprProduct3$repr$__redArg$__closed__14 }, _2: __uniq$5 };
          if (__uniq$4 < 0) {
            const __uniq$40 = String(__uniq$4);
            const __uniq$42 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$40 }, 0);
            {
              const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$42 } };
              __uniq$12._2 = 0;
              const __uniq$20 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprProduct3$repr$__redArg$__closed__9, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprProduct3$repr$__redArg$__closed__11, _2: { tag: "Std$Format$append", _1: __uniq$34, _2: __uniq$12 } }, _2: instReprProduct3$repr$__redArg$__closed__12 } } };
              __uniq$20._2 = 0;
              return __uniq$20;
            }
          } else {
            const __uniq$38 = String(__uniq$4);
            {
              const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$38 } } };
              __uniq$12._2 = 0;
              const __uniq$20 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprProduct3$repr$__redArg$__closed__9, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprProduct3$repr$__redArg$__closed__11, _2: { tag: "Std$Format$append", _1: __uniq$34, _2: __uniq$12 } }, _2: instReprProduct3$repr$__redArg$__closed__12 } } };
              __uniq$20._2 = 0;
              return __uniq$20;
            }
          }
        }
      }
    }
  } else {
    const __uniq$68 = String(__uniq$2);
    {
      const __uniq$47 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$68 } } };
      __uniq$47._2 = 0;
      const __uniq$51 = { tag: "Std$Format$line" };
      const __uniq$55 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$6, _2: __uniq$47 }, _2: instReprProduct3$repr$__redArg$__closed__16 }, _2: __uniq$51 }, _2: instReprProduct3$repr$__redArg$__closed__18 }, _2: __uniq$5 };
      if (__uniq$3 < 0) {
        const __uniq$61 = String(__uniq$3);
        const __uniq$63 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$61 }, 0);
        {
          const __uniq$28 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$63 } };
          __uniq$28._2 = 0;
          const __uniq$34 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$55, _2: __uniq$28 }, _2: instReprProduct3$repr$__redArg$__closed__16 }, _2: __uniq$51 }, _2: instReprProduct3$repr$__redArg$__closed__14 }, _2: __uniq$5 };
          if (__uniq$4 < 0) {
            const __uniq$40 = String(__uniq$4);
            const __uniq$42 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$40 }, 0);
            {
              const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$42 } };
              __uniq$12._2 = 0;
              const __uniq$20 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprProduct3$repr$__redArg$__closed__9, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprProduct3$repr$__redArg$__closed__11, _2: { tag: "Std$Format$append", _1: __uniq$34, _2: __uniq$12 } }, _2: instReprProduct3$repr$__redArg$__closed__12 } } };
              __uniq$20._2 = 0;
              return __uniq$20;
            }
          } else {
            const __uniq$38 = String(__uniq$4);
            {
              const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$38 } } };
              __uniq$12._2 = 0;
              const __uniq$20 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprProduct3$repr$__redArg$__closed__9, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprProduct3$repr$__redArg$__closed__11, _2: { tag: "Std$Format$append", _1: __uniq$34, _2: __uniq$12 } }, _2: instReprProduct3$repr$__redArg$__closed__12 } } };
              __uniq$20._2 = 0;
              return __uniq$20;
            }
          }
        }
      } else {
        const __uniq$59 = String(__uniq$3);
        {
          const __uniq$28 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$59 } } };
          __uniq$28._2 = 0;
          const __uniq$34 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$55, _2: __uniq$28 }, _2: instReprProduct3$repr$__redArg$__closed__16 }, _2: __uniq$51 }, _2: instReprProduct3$repr$__redArg$__closed__14 }, _2: __uniq$5 };
          if (__uniq$4 < 0) {
            const __uniq$40 = String(__uniq$4);
            const __uniq$42 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$40 }, 0);
            {
              const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$42 } };
              __uniq$12._2 = 0;
              const __uniq$20 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprProduct3$repr$__redArg$__closed__9, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprProduct3$repr$__redArg$__closed__11, _2: { tag: "Std$Format$append", _1: __uniq$34, _2: __uniq$12 } }, _2: instReprProduct3$repr$__redArg$__closed__12 } } };
              __uniq$20._2 = 0;
              return __uniq$20;
            }
          } else {
            const __uniq$38 = String(__uniq$4);
            {
              const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$38 } } };
              __uniq$12._2 = 0;
              const __uniq$20 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprProduct3$repr$__redArg$__closed__9, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprProduct3$repr$__redArg$__closed__11, _2: { tag: "Std$Format$append", _1: __uniq$34, _2: __uniq$12 } }, _2: instReprProduct3$repr$__redArg$__closed__12 } } };
              __uniq$20._2 = 0;
              return __uniq$20;
            }
          }
        }
      }
    }
  }
};
export const instReprProduct3$repr = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => instReprProduct3$repr$__redArg(__uniq$1);
export const instReprProduct3 = () => instReprProduct3$repr;
export const caseBoolean = (/* UInt8 */ __uniq$1) => __uniq$1 ? "1" : "2";
export const main$__closed__0 = caseBoolean(1);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main$__closed__1 = caseBoolean(0);
export const main$__closed__2 = caseChar(97);
export const main$__closed__3 = caseChar(122);
export const main$__closed__4 = caseInt(2);
export const main$__closed__6 = caseInt(9);
export const main$__closed__7 = caseNumber(caseNumber$__closed__2);
export const main$__closed__10 = (() => {
  const __uniq$1 = 0;
  const __uniq$2 = 1;
  const __uniq$3 = caseGrafting(__uniq$2, __uniq$1, __uniq$2);
  return __uniq$3;
})();
export const IO$println$__at__$main$spec__1 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const caseHeuristicP = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  const __uniq$10 = 1;
  const __uniq$11 = __uniq$1 === __uniq$10;
  return __uniq$11 ? __uniq$2 === 2 ? __uniq$3 === __uniq$10 ? __uniq$10 : __uniq$3 === 2 ? 2 : __uniq$3 === 3 ? 3 : __uniq$3 === 4 ? 4 : 5 : __uniq$3 === 4 ? 4 : 5 : __uniq$2 === 2 ? __uniq$3 === 3 ? 3 : 5 : 5;
};
export const main$__closed__12 = (() => {
  const __uniq$1 = 2;
  const __uniq$2 = 1;
  const __uniq$3 = caseHeuristicP(__uniq$2, __uniq$1, __uniq$1);
  return __uniq$3;
})();
export const caseHeuristicPB = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1.tag === "Column$one" ? __uniq$1._1 === 1 ? __uniq$2.tag === "Column$one" ? __uniq$2._1 === 1 ? 1 : 4 : __uniq$2.tag === "Column$zero" ? 3 : 4 : __uniq$2.tag === "Column$zero" ? 3 : 4 : __uniq$1.tag === "Column$two" ? __uniq$1._1 === 2 ? __uniq$1._2 === 3 ? __uniq$2.tag === "Column$two" ? __uniq$2._1 === 2 ? __uniq$2._2 === 3 ? 2 : 4 : 4 : __uniq$2.tag === "Column$zero" ? 3 : 4 : __uniq$2.tag === "Column$zero" ? 3 : 4 : __uniq$2.tag === "Column$zero" ? 3 : 4 : __uniq$2.tag === "Column$zero" ? 3 : 4;
export const main$__closed__14 = (() => {
  const __uniq$1 = { tag: "Column$two", _1: 2, _2: 3 };
  const __uniq$2 = caseHeuristicPB(__uniq$1, __uniq$1);
  return __uniq$2;
})();
export const caseHeuristicPBAN = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1.tag === "Column$one" ? __uniq$1._1 === 1 ? __uniq$2.tag === "Column$one" ? __uniq$2._1 === 1 ? 1 : 4 : 4 : __uniq$1._1 === 2 ? __uniq$2.tag === "Column$one" ? __uniq$2._1 === 2 ? 2 : 4 : 4 : 4 : __uniq$1.tag === "Column$two" ? __uniq$2.tag === "Column$two" ? 3 : 4 : 4;
export const main$__closed__21 = caseHeuristicPBAN({ tag: "Column$two", _1: 7, _2: 8 }, main$__closed__16);
export const main$__closed__27 = caseJacobs({ tag: "Expr$mul", _1: { tag: "Expr$add", _1: { tag: "Expr$zero" }, _2: main$__closed__24 }, _2: main$__closed__24 });
export const caseNamed1 = (/* tobj */ __uniq$1) => {
  const __uniq$2 = 1;
  const __uniq$3 = __uniq$1 === __uniq$2;
  if (__uniq$3) {
    return "111";
  } else if (__uniq$1 === 2) {
    return "2";
  } else {
    const __uniq$7 = String(__uniq$1);
    return "any: " + __uniq$7 + __uniq$7 + __uniq$7;
  }
};
export const main$__closed__28 = caseNamed1(1);
export const main$__closed__29 = caseNamed1(9);
export const caseNamed2 = (/* obj */ __uniq$1) => {
  const __uniq$10 = __uniq$1._1;
  const __uniq$11 = __uniq$1._2;
  const __uniq$12 = __uniq$1._3;
  const __uniq$13 = 1;
  const __uniq$14 = __uniq$10 === __uniq$13;
  if (__uniq$14) {
    const __uniq$4 = String(__uniq$11);
    const __uniq$5 = String(__uniq$12);
    return __uniq$4 + __uniq$5 + "1";
  } else if (__uniq$11 === __uniq$13) {
    const __uniq$4 = String(__uniq$10);
    const __uniq$5 = String(__uniq$12);
    return __uniq$4 + __uniq$5 + "1";
  } else if (__uniq$12 === __uniq$13) {
    const __uniq$4 = String(__uniq$10);
    const __uniq$5 = String(__uniq$11);
    return __uniq$4 + __uniq$5 + "1";
  } else {
    const __uniq$17 = String(__uniq$10);
    const __uniq$19 = String(__uniq$11);
    const __uniq$22 = String(__uniq$12);
    return __uniq$17 + __uniq$17 + __uniq$19 + __uniq$19 + __uniq$22 + __uniq$22;
  }
};
export const main$__closed__31 = caseNamed2({ tag: "Product3$mk", _1: 1, _2: 2, _3: 3 });
export const main$__closed__34 = caseNamed2({ tag: "Product3$mk", _1: 4, _2: 5, _3: 6 });
export const main = () => {
  const __uniq$2 = main$__closed__0;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__1);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__0(main$__closed__2);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__0(main$__closed__3);
        if (__uniq$9.tag === "EST$Out$ok") {
          const __uniq$11 = IO$println$__at__$main$spec__0(main$__closed__4);
          if (__uniq$11.tag === "EST$Out$ok") {
            const __uniq$13 = IO$println$__at__$main$spec__0(main$__closed__6);
            if (__uniq$13.tag === "EST$Out$ok") {
              const __uniq$15 = IO$println$__at__$main$spec__0(main$__closed__7);
              if (__uniq$15.tag === "EST$Out$ok") {
                const __uniq$17 = IO$println$__at__$main$spec__0(main$__closed__9);
                if (__uniq$17.tag === "EST$Out$ok") {
                  const __uniq$19 = IO$println$__at__$main$spec__1(main$__closed__10);
                  if (__uniq$19.tag === "EST$Out$ok") {
                    const __uniq$21 = IO$println$__at__$main$spec__1(main$__closed__11);
                    if (__uniq$21.tag === "EST$Out$ok") {
                      const __uniq$23 = IO$println$__at__$main$spec__1(main$__closed__12);
                      if (__uniq$23.tag === "EST$Out$ok") {
                        const __uniq$25 = IO$println$__at__$main$spec__1(main$__closed__14);
                        if (__uniq$25.tag === "EST$Out$ok") {
                          const __uniq$27 = IO$println$__at__$main$spec__1(main$__closed__17);
                          if (__uniq$27.tag === "EST$Out$ok") {
                            const __uniq$29 = IO$println$__at__$main$spec__1(main$__closed__21);
                            if (__uniq$29.tag === "EST$Out$ok") {
                              const __uniq$31 = IO$println$__at__$main$spec__0(main$__closed__23);
                              if (__uniq$31.tag === "EST$Out$ok") {
                                const __uniq$33 = IO$println$__at__$main$spec__0(main$__closed__27);
                                if (__uniq$33.tag === "EST$Out$ok") {
                                  const __uniq$35 = IO$println$__at__$main$spec__0(main$__closed__28);
                                  if (__uniq$35.tag === "EST$Out$ok") {
                                    const __uniq$37 = IO$println$__at__$main$spec__0(main$__closed__29);
                                    if (__uniq$37.tag === "EST$Out$ok") {
                                      const __uniq$39 = IO$println$__at__$main$spec__0(main$__closed__31);
                                      if (__uniq$39.tag === "EST$Out$ok") {
                                        const __uniq$41 = IO$println$__at__$main$spec__0(main$__closed__34);
                                        return __uniq$41;
                                      } else if (__uniq$39.tag === "EST$Out$error") {
                                        return __uniq$39;
                                      }
                                    } else if (__uniq$37.tag === "EST$Out$error") {
                                      return __uniq$37;
                                    }
                                  } else if (__uniq$35.tag === "EST$Out$error") {
                                    return __uniq$35;
                                  }
                                } else if (__uniq$33.tag === "EST$Out$error") {
                                  return __uniq$33;
                                }
                              } else if (__uniq$31.tag === "EST$Out$error") {
                                return __uniq$31;
                              }
                            } else if (__uniq$29.tag === "EST$Out$error") {
                              return __uniq$29;
                            }
                          } else if (__uniq$27.tag === "EST$Out$error") {
                            return __uniq$27;
                          }
                        } else if (__uniq$25.tag === "EST$Out$error") {
                          return __uniq$25;
                        }
                      } else if (__uniq$23.tag === "EST$Out$error") {
                        return __uniq$23;
                      }
                    } else if (__uniq$21.tag === "EST$Out$error") {
                      return __uniq$21;
                    }
                  } else if (__uniq$19.tag === "EST$Out$error") {
                    return __uniq$19;
                  }
                } else if (__uniq$17.tag === "EST$Out$error") {
                  return __uniq$17;
                }
              } else if (__uniq$15.tag === "EST$Out$error") {
                return __uniq$15;
              }
            } else if (__uniq$13.tag === "EST$Out$error") {
              return __uniq$13;
            }
          } else if (__uniq$11.tag === "EST$Out$error") {
            return __uniq$11;
          }
        } else if (__uniq$9.tag === "EST$Out$error") {
          return __uniq$9;
        }
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const Expr$add$elim = (/* tobj */ __uniq$2, /* tobj */ __uniq$4) => Expr$ctorElim$__redArg(__uniq$2, __uniq$4);
export const Expr$add$elim$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => Expr$ctorElim$__redArg(__uniq$1, __uniq$2);
export const instReprColumn$repr$__closed__1 = { tag: "Std$Format$text", _1: "Column.zero" };
export const Expr$ctorIdx = (/* tobj */ __uniq$1) => {
  if (__uniq$1.tag === "Expr$add") {
    return 0;
  } else if (__uniq$1.tag === "Expr$mul") {
    return 1;
  } else if (__uniq$1.tag === "Expr$succ") {
    return 2;
  } else if (__uniq$1.tag === "Expr$zero") {
    return 3;
  }
};
export const instReprColumn$repr$__closed__4 = { tag: "Std$Format$append", _1: { tag: "Std$Format$text", _1: "Column.one" }, _2: { tag: "Std$Format$line" } };
export const instReprColumn$repr$__closed__8 = { tag: "Std$Format$append", _1: { tag: "Std$Format$text", _1: "Column.two" }, _2: { tag: "Std$Format$line" } };
export const instReprColumn$repr = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1.tag === "Column$zero") {
    if (1024 <= __uniq$2) {
      const __uniq$16 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 1, _2: instReprColumn$repr$__closed__1 } };
      __uniq$16._2 = 0;
      const __uniq$17 = Repr$addAppParen(__uniq$16, __uniq$2);
      return __uniq$17;
    } else {
      const __uniq$16 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 2, _2: instReprColumn$repr$__closed__1 } };
      __uniq$16._2 = 0;
      const __uniq$17 = Repr$addAppParen(__uniq$16, __uniq$2);
      return __uniq$17;
    }
  } else if (__uniq$1.tag === "Column$one") {
    if (1024 <= __uniq$2) {
      if (__uniq$1._1 < 0) {
        const __uniq$42 = String(__uniq$1._1);
        {
          const __uniq$44 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$42 }, 1024);
          {
            const __uniq$9 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 1, _2: { tag: "Std$Format$append", _1: instReprColumn$repr$__closed__4, _2: __uniq$44 } } };
            __uniq$9._2 = 0;
            const __uniq$10 = Repr$addAppParen(__uniq$9, __uniq$2);
            return __uniq$10;
          }
        }
      } else {
        const __uniq$39 = String(__uniq$1._1);
        {
          const __uniq$9 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 1, _2: { tag: "Std$Format$append", _1: instReprColumn$repr$__closed__4, _2: { tag: "Std$Format$text", _1: __uniq$39 } } } };
          __uniq$9._2 = 0;
          const __uniq$10 = Repr$addAppParen(__uniq$9, __uniq$2);
          return __uniq$10;
        }
      }
    } else {
      if (__uniq$1._1 < 0) {
        const __uniq$42 = String(__uniq$1._1);
        {
          const __uniq$44 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$42 }, 1024);
          {
            const __uniq$9 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 2, _2: { tag: "Std$Format$append", _1: instReprColumn$repr$__closed__4, _2: __uniq$44 } } };
            __uniq$9._2 = 0;
            const __uniq$10 = Repr$addAppParen(__uniq$9, __uniq$2);
            return __uniq$10;
          }
        }
      } else {
        const __uniq$39 = String(__uniq$1._1);
        {
          const __uniq$9 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 2, _2: { tag: "Std$Format$append", _1: instReprColumn$repr$__closed__4, _2: { tag: "Std$Format$text", _1: __uniq$39 } } } };
          __uniq$9._2 = 0;
          const __uniq$10 = Repr$addAppParen(__uniq$9, __uniq$2);
          return __uniq$10;
        }
      }
    }
  } else if (__uniq$1.tag === "Column$two") {
    if (1024 <= __uniq$2) {
      const __uniq$76 = { tag: "Std$Format$line" };
      if (__uniq$1._1 < 0) {
        const __uniq$83 = String(__uniq$1._1);
        const __uniq$85 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$83 }, 1024);
        {
          const __uniq$63 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprColumn$repr$__closed__8, _2: __uniq$85 }, _2: __uniq$76 };
          if (__uniq$1._2 < 0) {
            const __uniq$69 = String(__uniq$1._2);
            const __uniq$71 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$69 }, 1024);
            {
              const __uniq$25 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 1, _2: { tag: "Std$Format$append", _1: __uniq$63, _2: __uniq$71 } } };
              __uniq$25._2 = 0;
              const __uniq$26 = Repr$addAppParen(__uniq$25, __uniq$2);
              return __uniq$26;
            }
          } else {
            const __uniq$66 = String(__uniq$1._2);
            {
              const __uniq$25 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 1, _2: { tag: "Std$Format$append", _1: __uniq$63, _2: { tag: "Std$Format$text", _1: __uniq$66 } } } };
              __uniq$25._2 = 0;
              const __uniq$26 = Repr$addAppParen(__uniq$25, __uniq$2);
              return __uniq$26;
            }
          }
        }
      } else {
        const __uniq$80 = String(__uniq$1._1);
        {
          const __uniq$63 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprColumn$repr$__closed__8, _2: { tag: "Std$Format$text", _1: __uniq$80 } }, _2: __uniq$76 };
          if (__uniq$1._2 < 0) {
            const __uniq$69 = String(__uniq$1._2);
            const __uniq$71 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$69 }, 1024);
            {
              const __uniq$25 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 1, _2: { tag: "Std$Format$append", _1: __uniq$63, _2: __uniq$71 } } };
              __uniq$25._2 = 0;
              const __uniq$26 = Repr$addAppParen(__uniq$25, __uniq$2);
              return __uniq$26;
            }
          } else {
            const __uniq$66 = String(__uniq$1._2);
            {
              const __uniq$25 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 1, _2: { tag: "Std$Format$append", _1: __uniq$63, _2: { tag: "Std$Format$text", _1: __uniq$66 } } } };
              __uniq$25._2 = 0;
              const __uniq$26 = Repr$addAppParen(__uniq$25, __uniq$2);
              return __uniq$26;
            }
          }
        }
      }
    } else {
      const __uniq$76 = { tag: "Std$Format$line" };
      if (__uniq$1._1 < 0) {
        const __uniq$83 = String(__uniq$1._1);
        const __uniq$85 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$83 }, 1024);
        {
          const __uniq$63 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprColumn$repr$__closed__8, _2: __uniq$85 }, _2: __uniq$76 };
          if (__uniq$1._2 < 0) {
            const __uniq$69 = String(__uniq$1._2);
            const __uniq$71 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$69 }, 1024);
            {
              const __uniq$25 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 2, _2: { tag: "Std$Format$append", _1: __uniq$63, _2: __uniq$71 } } };
              __uniq$25._2 = 0;
              const __uniq$26 = Repr$addAppParen(__uniq$25, __uniq$2);
              return __uniq$26;
            }
          } else {
            const __uniq$66 = String(__uniq$1._2);
            {
              const __uniq$25 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 2, _2: { tag: "Std$Format$append", _1: __uniq$63, _2: { tag: "Std$Format$text", _1: __uniq$66 } } } };
              __uniq$25._2 = 0;
              const __uniq$26 = Repr$addAppParen(__uniq$25, __uniq$2);
              return __uniq$26;
            }
          }
        }
      } else {
        const __uniq$80 = String(__uniq$1._1);
        {
          const __uniq$63 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprColumn$repr$__closed__8, _2: { tag: "Std$Format$text", _1: __uniq$80 } }, _2: __uniq$76 };
          if (__uniq$1._2 < 0) {
            const __uniq$69 = String(__uniq$1._2);
            const __uniq$71 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$69 }, 1024);
            {
              const __uniq$25 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 2, _2: { tag: "Std$Format$append", _1: __uniq$63, _2: __uniq$71 } } };
              __uniq$25._2 = 0;
              const __uniq$26 = Repr$addAppParen(__uniq$25, __uniq$2);
              return __uniq$26;
            }
          } else {
            const __uniq$66 = String(__uniq$1._2);
            {
              const __uniq$25 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 2, _2: { tag: "Std$Format$append", _1: __uniq$63, _2: { tag: "Std$Format$text", _1: __uniq$66 } } } };
              __uniq$25._2 = 0;
              const __uniq$26 = Repr$addAppParen(__uniq$25, __uniq$2);
              return __uniq$26;
            }
          }
        }
      }
    }
  }
};
export const instReprColumn = () => instReprColumn$repr;
export const Column$ctorElim = (/* tobj */ __uniq$2, /* tobj */ __uniq$3, /* tobj */ __uniq$5) => Column$ctorElim$__redArg(__uniq$3, __uniq$5);
export const instReprExpr$repr$__closed__9 = { tag: "Std$Format$append", _1: { tag: "Std$Format$text", _1: "Expr.mul" }, _2: { tag: "Std$Format$line" } };
export const instReprExpr$repr$__closed__12 = { tag: "Std$Format$append", _1: { tag: "Std$Format$text", _1: "Expr.succ" }, _2: { tag: "Std$Format$line" } };
export const instReprExpr$repr = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1.tag === "Expr$add") {
    if (1024 <= __uniq$2) {
      const __uniq$18 = instReprExpr$repr(__uniq$1._1, 1024);
      {
        const __uniq$21 = instReprExpr$repr(__uniq$1._2, 1024);
        const __uniq$25 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 1, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprExpr$repr$__closed__4, _2: __uniq$18 }, _2: { tag: "Std$Format$line" } }, _2: __uniq$21 } } };
        __uniq$25._2 = 0;
        const __uniq$26 = Repr$addAppParen(__uniq$25, __uniq$2);
        return __uniq$26;
      }
    } else {
      const __uniq$18 = instReprExpr$repr(__uniq$1._1, 1024);
      {
        const __uniq$21 = instReprExpr$repr(__uniq$1._2, 1024);
        const __uniq$25 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 2, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprExpr$repr$__closed__4, _2: __uniq$18 }, _2: { tag: "Std$Format$line" } }, _2: __uniq$21 } } };
        __uniq$25._2 = 0;
        const __uniq$26 = Repr$addAppParen(__uniq$25, __uniq$2);
        return __uniq$26;
      }
    }
  } else if (__uniq$1.tag === "Expr$mul") {
    if (1024 <= __uniq$2) {
      const __uniq$43 = instReprExpr$repr(__uniq$1._1, 1024);
      {
        const __uniq$46 = instReprExpr$repr(__uniq$1._2, 1024);
        const __uniq$50 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 1, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprExpr$repr$__closed__9, _2: __uniq$43 }, _2: { tag: "Std$Format$line" } }, _2: __uniq$46 } } };
        __uniq$50._2 = 0;
        const __uniq$51 = Repr$addAppParen(__uniq$50, __uniq$2);
        return __uniq$51;
      }
    } else {
      const __uniq$43 = instReprExpr$repr(__uniq$1._1, 1024);
      {
        const __uniq$46 = instReprExpr$repr(__uniq$1._2, 1024);
        const __uniq$50 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 2, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprExpr$repr$__closed__9, _2: __uniq$43 }, _2: { tag: "Std$Format$line" } }, _2: __uniq$46 } } };
        __uniq$50._2 = 0;
        const __uniq$51 = Repr$addAppParen(__uniq$50, __uniq$2);
        return __uniq$51;
      }
    }
  } else if (__uniq$1.tag === "Expr$succ") {
    if (1024 <= __uniq$2) {
      const __uniq$64 = instReprExpr$repr(__uniq$1._1, 1024);
      const __uniq$68 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 1, _2: { tag: "Std$Format$append", _1: instReprExpr$repr$__closed__12, _2: __uniq$64 } } };
      __uniq$68._2 = 0;
      const __uniq$69 = Repr$addAppParen(__uniq$68, __uniq$2);
      return __uniq$69;
    } else {
      const __uniq$64 = instReprExpr$repr(__uniq$1._1, 1024);
      const __uniq$68 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 2, _2: { tag: "Std$Format$append", _1: instReprExpr$repr$__closed__12, _2: __uniq$64 } } };
      __uniq$68._2 = 0;
      const __uniq$69 = Repr$addAppParen(__uniq$68, __uniq$2);
      return __uniq$69;
    }
  } else if (__uniq$1.tag === "Expr$zero") {
    if (1024 <= __uniq$2) {
      const __uniq$7 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 1, _2: instReprExpr$repr$__closed__1 } };
      __uniq$7._2 = 0;
      const __uniq$8 = Repr$addAppParen(__uniq$7, __uniq$2);
      return __uniq$8;
    } else {
      const __uniq$7 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 2, _2: instReprExpr$repr$__closed__1 } };
      __uniq$7._2 = 0;
      const __uniq$8 = Repr$addAppParen(__uniq$7, __uniq$2);
      return __uniq$8;
    }
  }
};
export const Column$two$elim = (/* tobj */ __uniq$2, /* tobj */ __uniq$4) => Column$ctorElim$__redArg(__uniq$2, __uniq$4);
export const Expr$succ$elim$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => Expr$ctorElim$__redArg(__uniq$1, __uniq$2);
export const Expr$mul$elim$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => Expr$ctorElim$__redArg(__uniq$1, __uniq$2);
export const Column$one$elim$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => Column$ctorElim$__redArg(__uniq$1, __uniq$2);
export const Expr$zero$elim = (/* tobj */ __uniq$2, /* tobj */ __uniq$4) => Expr$ctorElim$__redArg(__uniq$2, __uniq$4);
export const Expr$zero$elim$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => Expr$ctorElim$__redArg(__uniq$1, __uniq$2);
export const instReprExpr = () => instReprExpr$repr;
export const Expr$succ$elim = (/* tobj */ __uniq$2, /* tobj */ __uniq$4) => Expr$ctorElim$__redArg(__uniq$2, __uniq$4);
export const Column$zero$elim$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => Column$ctorElim$__redArg(__uniq$1, __uniq$2);
export const Column$one$elim = (/* tobj */ __uniq$2, /* tobj */ __uniq$4) => Column$ctorElim$__redArg(__uniq$2, __uniq$4);
export const Expr$mul$elim = (/* tobj */ __uniq$2, /* tobj */ __uniq$4) => Expr$ctorElim$__redArg(__uniq$2, __uniq$4);

main();
