// Generated by Lean ES6 emitter
import { Std$Format$pretty } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Format/Basic.js";
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { Repr$addAppParen } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test1Opt = (/* tobj */ __uniq$1) => __uniq$1 === 1 ? { tag: "Option$some", _1: 1 } : __uniq$1 === 2 ? { tag: "Option$some", _1: 2 } : __uniq$1 === 3 ? { tag: "Option$some", _1: 3 } : { tag: "Option$none" };
export const main$__closed__0 = test1Opt(1);
export const Option$repr$__at__$main$spec__0$__closed__3 = { tag: "Std$Format$text", _1: "some " };
export const Option$repr$__at__$main$spec__0 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1.tag === "Option$none") {
    return { tag: "Std$Format$text", _1: "none" };
  } else if (__uniq$1.tag === "Option$some") {
    if (__uniq$1._1 < 0) {
      const __uniq$17 = String(__uniq$1._1);
      {
        const __uniq$19 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$17 }, 1024);
        {
          const __uniq$10 = Repr$addAppParen({ tag: "Std$Format$append", _1: Option$repr$__at__$main$spec__0$__closed__3, _2: __uniq$19 }, __uniq$2);
          return __uniq$10;
        }
      }
    } else {
      const __uniq$14 = String(__uniq$1._1);
      {
        const __uniq$10 = Repr$addAppParen({ tag: "Std$Format$append", _1: Option$repr$__at__$main$spec__0$__closed__3, _2: { tag: "Std$Format$text", _1: __uniq$14 } }, __uniq$2);
        return __uniq$10;
      }
    }
  }
};
export const main$__closed__1 = Option$repr$__at__$main$spec__0(main$__closed__0, 0);
export const IO$print$__at__$IO$println$__at__$main$spec__1$spec__1 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__1 = (/* tobj */ __uniq$1) => {
  const __uniq$3 = 120;
  const __uniq$4 = 0;
  const __uniq$5 = Std$Format$pretty(__uniq$1, __uniq$3, __uniq$4, __uniq$4);
  const __uniq$6 = 10;
  const __uniq$7 = __uniq$5 + String.fromCodePoint(__uniq$6);
  const __uniq$8 = IO$print$__at__$IO$println$__at__$main$spec__1$spec__1(__uniq$7);
  return __uniq$8;
};
export const main$__closed__2 = test1Opt(3);
export const main$__closed__3 = Option$repr$__at__$main$spec__0(main$__closed__2, 0);
export const main$__closed__5 = test1Opt(9);
export const main$__closed__6 = Option$repr$__at__$main$spec__0(main$__closed__5, 0);
export const main = () => {
  const __uniq$2 = main$__closed__1;
  const __uniq$3 = IO$println$__at__$main$spec__1(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__1(main$__closed__3);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__1(main$__closed__6);
      return __uniq$7;
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};

main();
