// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test1 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  const __uniq$3 = 1;
  const __uniq$4 = __uniq$1 === __uniq$3;
  return __uniq$4 ? __uniq$2 === __uniq$3 ? "1.1" : __uniq$2 === 2 ? "1.2" : __uniq$2 === 3 ? "1.3" : __uniq$2 === 4 ? "_.4" : __uniq$2 === 5 ? "1.5" : "_._" : __uniq$2 === 4 ? "_.4" : __uniq$2 === 2 ? "_.2" : "_._";
};
export const main$__closed__0 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = test1(__uniq$1, __uniq$1);
  return __uniq$2;
})();
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main$__closed__1 = test1(1, 2);
export const main$__closed__2 = test1(2, 4);
export const main$__closed__3 = (() => {
  const __uniq$1 = 2;
  const __uniq$2 = test1(__uniq$1, __uniq$1);
  return __uniq$2;
})();
export const main = () => {
  const __uniq$2 = main$__closed__0;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__1);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__0(main$__closed__2);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__0(main$__closed__3);
        return __uniq$9;
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};

main();
