// Generated by Lean ES6 emitter
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const SumType$ctorElim$__redArg = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$2(__uniq$1._1);
export const SumType$L$elim$__redArg = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => SumType$ctorElim$__redArg(__uniq$1, __uniq$2);
export const test1 = (/* obj */ __uniq$1) => {
  if (__uniq$1.tag === "SumType$L") {
    return __uniq$1._1 === 1 ? "1" : __uniq$1._1 === 2 ? "2" : "3";
  } else if (__uniq$1.tag === "SumType$R") {
    return "4";
  }
};
export const SumType$ctorElim = (/* tobj */ __uniq$2, /* obj */ __uniq$3, /* tobj */ __uniq$5) => SumType$ctorElim$__redArg(__uniq$3, __uniq$5);
export const main$__closed__1 = test1({ tag: "SumType$L", _1: 1 });
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main$__closed__3 = test1({ tag: "SumType$L", _1: 2 });
export const main$__closed__5 = test1({ tag: "SumType$L", _1: 42 });
export const main$__closed__7 = test1({ tag: "SumType$R", _1: 42 });
export const main = () => {
  const __uniq$2 = main$__closed__1;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__3);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__0(main$__closed__5);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__0(main$__closed__7);
        return __uniq$9;
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const SumType$ctorIdx = (/* obj */ __uniq$1) => {
  if (__uniq$1.tag === "SumType$L") {
    return 0;
  } else if (__uniq$1.tag === "SumType$R") {
    return 1;
  }
};
export const SumType$L$elim = (/* obj */ __uniq$2, /* tobj */ __uniq$4) => SumType$ctorElim$__redArg(__uniq$2, __uniq$4);
export const SumType$R$elim$__redArg = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => SumType$ctorElim$__redArg(__uniq$1, __uniq$2);
export const SumType$R$elim = (/* obj */ __uniq$2, /* tobj */ __uniq$4) => SumType$ctorElim$__redArg(__uniq$2, __uniq$4);

main();
