// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const main$__closed__11 = (() => {
  const __uniq$1 = 9;
  const __uniq$2 = { tag: "InnerEF$mk", _1: __uniq$1, _2: __uniq$1 };
  return __uniq$2;
})();
export const main$__closed__14 = (() => {
  const __uniq$1 = 9;
  const __uniq$2 = { tag: "InnerBC$mk", _1: __uniq$1, _2: __uniq$1 };
  return __uniq$2;
})();
export const test2 = (/* obj */ __uniq$1) => {
  const __uniq$6 = __uniq$1._1;
  const __uniq$7 = __uniq$1._2;
  const __uniq$8 = __uniq$6._1;
  const __uniq$9 = __uniq$6._2;
  const __uniq$10 = 1;
  const __uniq$11 = __uniq$8 === __uniq$10;
  return __uniq$11 ? __uniq$9 === 2 ? __uniq$7._1 === __uniq$10 ? __uniq$7._2 === 2 ? __uniq$10 : 3 : 3 : 4 : __uniq$9 === 2 ? __uniq$7._1 === __uniq$10 ? __uniq$7._2 === 2 ? 2 : 4 : 4 : 4;
};
export const main$__closed__16 = test2({ tag: "Outer$mk", _1: main$__closed__14, _2: main$__closed__11 });
export const main$__closed__3 = { tag: "InnerEF$mk", _1: 1, _2: 2 };
export const test1 = (/* obj */ __uniq$1) => {
  const __uniq$2 = __uniq$1._1;
  const __uniq$3 = __uniq$1._2;
  const __uniq$4 = __uniq$1._3;
  const __uniq$5 = 1;
  const __uniq$6 = __uniq$2 === __uniq$5;
  return __uniq$6 ? "0" : __uniq$2 === 2 ? __uniq$3 === __uniq$5 ? "1" : __uniq$3 === 2 ? __uniq$4 === __uniq$5 ? "2" : "3" : __uniq$4 === __uniq$5 ? "2" : "catch" : __uniq$3 === __uniq$5 ? "1" : __uniq$4 === __uniq$5 ? "2" : "catch";
};
export const main$__closed__9 = test2({ tag: "Outer$mk", _1: { tag: "InnerBC$mk", _1: 5, _2: 2 }, _2: main$__closed__3 });
export const main$__closed__1 = test1({ tag: "ABC$mk", _1: 1, _2: 2, _3: 3 });
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main$__closed__2 = { tag: "InnerBC$mk", _1: 1, _2: 2 };
export const main$__closed__5 = test2({ tag: "Outer$mk", _1: main$__closed__2, _2: main$__closed__3 });
export const IO$println$__at__$main$spec__1 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main$__closed__13 = test2({ tag: "Outer$mk", _1: main$__closed__2, _2: main$__closed__11 });
export const main = () => {
  const __uniq$2 = main$__closed__1;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__1(main$__closed__5);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__1(main$__closed__9);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__1(main$__closed__13);
        if (__uniq$9.tag === "EST$Out$ok") {
          const __uniq$11 = IO$println$__at__$main$spec__1(main$__closed__16);
          return __uniq$11;
        } else if (__uniq$9.tag === "EST$Out$error") {
          return __uniq$9;
        }
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};

main();
