// Generated by Lean ES6 emitter
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test2 = () => "???";
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main = () => {
  const __uniq$2 = "???";
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$4 = IO$println$__at__$main$spec__0(__uniq$2);
    if (__uniq$4.tag === "EST$Out$ok") {
      const __uniq$5 = IO$println$__at__$main$spec__0(__uniq$2);
      if (__uniq$5.tag === "EST$Out$ok") {
        const __uniq$6 = IO$println$__at__$main$spec__0(__uniq$2);
        return __uniq$6;
      } else if (__uniq$5.tag === "EST$Out$error") {
        return __uniq$5;
      }
    } else if (__uniq$4.tag === "EST$Out$error") {
      return __uniq$4;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const test3 = () => "???";
export const flubImpl = (/* obj */ __uniq$1) => "???";
export const test1 = () => "???";
export const test4 = () => "???";

main();
