// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const cpsResult = (/* tobj */ __uniq$1) => {
  const __uniq$2 = 1;
  const __uniq$3 = __uniq$1 + __uniq$2;
  const __uniq$4 = __uniq$3 + __uniq$2;
  const __uniq$5 = { tag: "PUnit$unit" };
  const __uniq$6 = { tag: "Prod$mk", _1: __uniq$4, _2: __uniq$5 };
  return __uniq$6;
};
export const main$__closed__1 = cpsResult(0);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main = () => IO$println$__at__$main$spec__0(main$__closed__1._1);

main();
