// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test2 = (/* tobj */ __uniq$1) => {
  const __uniq$2 = 1;
  const __uniq$3 = __uniq$1 + __uniq$2;
  const __uniq$4 = 10;
  const __uniq$5 = __uniq$3 < __uniq$4;
  return __uniq$5 ? __uniq$3 : __uniq$3 * 2;
};
export const bindCPS$__redArg$__lam__0 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => __uniq$1(__uniq$3, __uniq$2);
export const bindCPS$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => __uniq$1(bindCPS$__redArg$__lam__0.length - 2 === 0 ? () => bindCPS$__redArg$__lam__0(__uniq$2, __uniq$3) : bindCPS$__redArg$__lam__0.length - 2 === 1 ? (x_1) => bindCPS$__redArg$__lam__0(__uniq$2, __uniq$3, x_1) : bindCPS$__redArg$__lam__0.length - 2 === 2 ? (x_1, x_2) => bindCPS$__redArg$__lam__0(__uniq$2, __uniq$3, x_1, x_2) : (x_1, x_2, x_3) => bindCPS$__redArg$__lam__0(__uniq$2, __uniq$3, x_1, x_2, x_3));
export const test1 = (/* tobj */ __uniq$1) => (__uniq$1 + 1) * 2;
export const main$__closed__0 = test1(10);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main$__closed__2 = test2(5);
export const main$__closed__4 = test2(15);
export const main = () => {
  const __uniq$2 = main$__closed__0;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__2);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__0(main$__closed__4);
      return __uniq$7;
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const pureCPS$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$2(__uniq$1);
export const bindCPS = (/* tobj */ __uniq$4, /* tobj */ __uniq$5, /* tobj */ __uniq$6) => __uniq$4(bindCPS$__redArg$__lam__0.length - 2 === 0 ? () => bindCPS$__redArg$__lam__0(__uniq$5, __uniq$6) : bindCPS$__redArg$__lam__0.length - 2 === 1 ? (x_1) => bindCPS$__redArg$__lam__0(__uniq$5, __uniq$6, x_1) : bindCPS$__redArg$__lam__0.length - 2 === 2 ? (x_1, x_2) => bindCPS$__redArg$__lam__0(__uniq$5, __uniq$6, x_1, x_2) : (x_1, x_2, x_3) => bindCPS$__redArg$__lam__0(__uniq$5, __uniq$6, x_1, x_2, x_3));
export const pureCPS = (/* tobj */ __uniq$3, /* tobj */ __uniq$4) => __uniq$4(__uniq$3);

main();
