// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test2 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tagged */ __uniq$3) => __uniq$1(1, __uniq$2("foo", __uniq$3));
export const flip_u39_$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => __uniq$1(__uniq$3, __uniq$2);
export const test4$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => __uniq$1(__uniq$3, __uniq$2);
export const const_u39_ = (/* tobj */ __uniq$3, /* tobj */ __uniq$4) => __uniq$3;
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const IO$println$__at__$main$spec__1 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const IO$println$__at__$main$spec__2 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main = () => {
  const __uniq$2 = "ok";
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__1(2 + 1);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__2(42);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__1(0);
        return __uniq$9;
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const test3$__redArg = (/* obj */ __uniq$1, /* obj */ __uniq$2) => __uniq$1(__uniq$2(1, 2), 3);
export const test3 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tagged */ __uniq$3) => test3$__redArg(__uniq$1, __uniq$2);
export const const_u39_$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const test5$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const test6 = (/* tobj */ __uniq$1) => __uniq$1;
export const test1 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tagged */ __uniq$3) => __uniq$1(1, __uniq$2("foo", __uniq$3));
export const test5 = (/* tobj */ __uniq$3, /* tobj */ __uniq$4) => __uniq$3;
export const flip_u39_ = (/* tobj */ __uniq$4, /* tobj */ __uniq$5, /* tobj */ __uniq$6) => __uniq$4(__uniq$6, __uniq$5);
export const test4 = (/* tobj */ __uniq$4, /* tobj */ __uniq$5, /* tobj */ __uniq$6) => __uniq$4(__uniq$6, __uniq$5);

main();
