// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const main$__lam__0 = (/* tobj */ __uniq$1) => "f" + String(__uniq$1);
export const test2 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tobj */ __uniq$3) => {
  const __uniq$4 = __uniq$1(__uniq$3);
  const __uniq$5 = __uniq$2(__uniq$3);
  const __uniq$6 = __uniq$4 + __uniq$5;
  const __uniq$7 = __uniq$6 + __uniq$4;
  const __uniq$8 = __uniq$7 + __uniq$5;
  return __uniq$8;
};
export const main$__lam__1 = (/* tobj */ __uniq$1) => "g" + String(__uniq$1);
export const test1 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tobj */ __uniq$3) => __uniq$1(__uniq$3) + __uniq$2(__uniq$3);
export const main$__closed__3 = test1(main$__lam__0, main$__lam__1, 42);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main$__closed__4 = test2(main$__lam__0, main$__lam__1, 42);
export const main = () => {
  const __uniq$2 = main$__closed__3;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__4);
    return __uniq$5;
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};

main();
