// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { Bool$repr$__redArg, Repr$addAppParen, String$quote } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Repr.js";
import { lean_string_length } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/String/Bootstrap.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const main$__lam__0 = (/* tobj */ __uniq$1) => "a" + String(__uniq$1);
export const eqTest1$__closed__2 = (() => {
  const __uniq$1 = 0;
  const __uniq$2 = "hello";
  const __uniq$3 = 42;
  const __uniq$4 = { tag: "R$mk", _1: __uniq$3, _2: __uniq$2 };
  __uniq$4._3 = __uniq$1;
  return __uniq$4;
})();
export const instBEqR$beq = (/* obj */ __uniq$1, /* obj */ __uniq$2) => {
  const __uniq$3 = __uniq$1._1;
  const __uniq$4 = __uniq$1._2;
  const __uniq$5 = __uniq$1._3;
  const __uniq$6 = __uniq$2._1;
  const __uniq$7 = __uniq$2._2;
  const __uniq$8 = __uniq$2._3;
  const __uniq$9 = __uniq$3 === __uniq$6;
  if (__uniq$9) {
    const __uniq$10 = __uniq$4 === __uniq$7;
    return __uniq$10 ? __uniq$5 ? __uniq$8 : __uniq$8 ? __uniq$5 : __uniq$10 : __uniq$10;
  } else {
    return __uniq$9;
  }
};
export const eqTest1$__closed__3 = (() => {
  const __uniq$1 = eqTest1$__closed__2;
  const __uniq$2 = __uniq$1 === __uniq$1;
  return __uniq$2;
})();
export const eqTest1 = () => eqTest1$__closed__3;
export const main$__lam__1 = (/* tobj */ __uniq$1) => "b" + String(__uniq$1);
export const functionAppend = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tobj */ __uniq$3) => __uniq$1(__uniq$3) + __uniq$2(__uniq$3);
export const main$__closed__8 = functionAppend(main$__lam__0, main$__lam__1, 7);
export const instBEqR$__closed__0 = (x_1, x_2) => x_1 === x_2;
export const instReprR$repr$__redArg$__closed__5 = { tag: "Std$Format$text", _1: " := " };
export const eqTest2$__closed__1 = (() => {
  const __uniq$1 = 0;
  const __uniq$2 = "hello";
  const __uniq$3 = 43;
  const __uniq$4 = { tag: "R$mk", _1: __uniq$3, _2: __uniq$2 };
  __uniq$4._3 = __uniq$1;
  return __uniq$4;
})();
export const eqTest2$__closed__2 = eqTest1$__closed__2 === eqTest2$__closed__1;
export const eqTest3 = () => eqTest2$__closed__2 ? 0 : 1;
export const main$__lam__2 = (/* obj */ __uniq$1) => __uniq$1 + "!";
export const instReprR$repr$__redArg$__closed__9 = { tag: "Std$Format$text", _1: "," };
export const instReprR$repr$__redArg$__closed__11 = { tag: "Std$Format$text", _1: "bar" };
export const instReprR$repr$__redArg$__closed__13 = { tag: "Std$Format$text", _1: "baz" };
export const instReprR$repr$__redArg$__closed__15 = lean_string_length("{ ");
export const instReprR$repr$__redArg$__closed__17 = { tag: "Std$Format$text", _1: "{ " };
export const instReprR$repr$__redArg$__closed__18 = { tag: "Std$Format$text", _1: " }" };
export const instReprR$repr$__redArg = (/* obj */ __uniq$1) => {
  const __uniq$2 = __uniq$1._1;
  const __uniq$3 = __uniq$1._2;
  const __uniq$4 = __uniq$1._3;
  const __uniq$5 = instReprR$repr$__redArg$__closed__5;
  const __uniq$6 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$nil" }, _2: { tag: "Std$Format$text", _1: "foo" } }, _2: instReprR$repr$__redArg$__closed__5 };
  const __uniq$7 = 7;
  const __uniq$42 = 0;
  const __uniq$43 = 0;
  const __uniq$44 = __uniq$2 < __uniq$43;
  if (__uniq$44) {
    const __uniq$47 = String(__uniq$2);
    const __uniq$49 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$47 }, __uniq$42);
    {
      const __uniq$11 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$49 } };
      __uniq$11._2 = 0;
      const __uniq$15 = { tag: "Std$Format$line" };
      const __uniq$20 = String$quote(__uniq$3);
      const __uniq$23 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$20 } } };
      __uniq$23._2 = 0;
      const __uniq$30 = Bool$repr$__redArg(__uniq$4);
      const __uniq$32 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$30 } };
      __uniq$32._2 = 0;
      const __uniq$40 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprR$repr$__redArg$__closed__15, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprR$repr$__redArg$__closed__17, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$6, _2: __uniq$11 }, _2: instReprR$repr$__redArg$__closed__9 }, _2: __uniq$15 }, _2: instReprR$repr$__redArg$__closed__11 }, _2: __uniq$5 }, _2: __uniq$23 }, _2: instReprR$repr$__redArg$__closed__9 }, _2: __uniq$15 }, _2: instReprR$repr$__redArg$__closed__13 }, _2: __uniq$5 }, _2: __uniq$32 } }, _2: instReprR$repr$__redArg$__closed__18 } } };
      __uniq$40._2 = 0;
      return __uniq$40;
    }
  } else {
    const __uniq$45 = String(__uniq$2);
    {
      const __uniq$11 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$45 } } };
      __uniq$11._2 = 0;
      const __uniq$15 = { tag: "Std$Format$line" };
      const __uniq$20 = String$quote(__uniq$3);
      const __uniq$23 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$20 } } };
      __uniq$23._2 = 0;
      const __uniq$30 = Bool$repr$__redArg(__uniq$4);
      const __uniq$32 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$30 } };
      __uniq$32._2 = 0;
      const __uniq$40 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprR$repr$__redArg$__closed__15, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprR$repr$__redArg$__closed__17, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$6, _2: __uniq$11 }, _2: instReprR$repr$__redArg$__closed__9 }, _2: __uniq$15 }, _2: instReprR$repr$__redArg$__closed__11 }, _2: __uniq$5 }, _2: __uniq$23 }, _2: instReprR$repr$__redArg$__closed__9 }, _2: __uniq$15 }, _2: instReprR$repr$__redArg$__closed__13 }, _2: __uniq$5 }, _2: __uniq$32 } }, _2: instReprR$repr$__redArg$__closed__18 } } };
      __uniq$40._2 = 0;
      return __uniq$40;
    }
  }
};
export const instReprR$repr = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => instReprR$repr$__redArg(__uniq$1);
export const maybeConst$__closed__0 = { tag: "Option$some", _1: 42 };
export const maybeConst = (/* tobj */ __uniq$1) => {
  if (__uniq$1.tag === "Option$none") {
    return { tag: "Option$none" };
  } else if (__uniq$1.tag === "Option$some") {
    return maybeConst$__closed__0;
  }
};
export const functionAppend4 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tobj */ __uniq$3) => {
  const __uniq$4 = __uniq$1(__uniq$3);
  const __uniq$5 = __uniq$2(__uniq$3);
  const __uniq$6 = __uniq$4 + __uniq$5;
  const __uniq$7 = __uniq$6 + __uniq$4;
  const __uniq$8 = __uniq$7 + __uniq$5;
  return __uniq$8;
};
export const main$__closed__9 = functionAppend4(main$__lam__0, main$__lam__1, 7);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* UInt8 */ __uniq$1) => {
  if (__uniq$1) {
    const __uniq$5 = "true" + String.fromCodePoint(10);
    const __uniq$6 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$5);
    return __uniq$6;
  } else {
    const __uniq$5 = "false" + String.fromCodePoint(10);
    const __uniq$6 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$5);
    return __uniq$6;
  }
};
export const eqTest2 = () => eqTest2$__closed__2;
export const IO$println$__at__$main$spec__1 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main$__lam__3 = (/* tagged */ __uniq$1) => "ok";
export const pipeDemo = (/* obj */ __uniq$1, /* obj */ __uniq$2) => __uniq$2(__uniq$1({ tag: "PUnit$unit" }));
export const main$__closed__4 = pipeDemo(main$__lam__3, main$__lam__2);
export const main$__closed__7 = maybeConst({ tag: "Option$some", _1: "x" });
export const maybeShow = (/* tobj */ __uniq$1) => {
  if (__uniq$1.tag === "Option$none") {
    return { tag: "Option$none" };
  } else if (__uniq$1.tag === "Option$some") {
    const __uniq$6 = String(__uniq$1._1);
    return { tag: "Option$some", _1: __uniq$6 };
  }
};
export const main$__closed__10 = maybeShow(maybeConst$__closed__0);
export const main$__closed__14 = false;
export const main$__closed__15 = (() => {
  const __uniq$1 = 12;
  const __uniq$2 = __uniq$1 === __uniq$1;
  return __uniq$2;
})();
export const main = () => {
  const __uniq$2 = eqTest1();
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$4 = eqTest2();
    const __uniq$5 = IO$println$__at__$main$spec__0(__uniq$4);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$6 = eqTest3();
      const __uniq$7 = IO$println$__at__$main$spec__0(__uniq$6);
      if (__uniq$7.tag === "EST$Out$ok") {
        if (main$__closed__15) {
          const __uniq$31 = IO$println$__at__$main$spec__0(0);
          if (__uniq$31.tag === "EST$Out$ok") {
            if (main$__closed__14) {
              const __uniq$21 = IO$println$__at__$main$spec__0(0);
              if (__uniq$21.tag === "EST$Out$ok") {
                const __uniq$23 = IO$println$__at__$main$spec__1(main$__closed__8);
                if (__uniq$23.tag === "EST$Out$ok") {
                  const __uniq$25 = IO$println$__at__$main$spec__1(main$__closed__9);
                  if (__uniq$25.tag === "EST$Out$ok") {
                    if (main$__closed__10.tag === "Option$none") {
                      const __uniq$15 = IO$println$__at__$main$spec__1("none");
                      if (__uniq$15.tag === "EST$Out$ok") {
                        if (main$__closed__7.tag === "Option$none") {
                          const __uniq$9 = String(0);
                          const __uniq$10 = IO$println$__at__$main$spec__1(__uniq$9);
                          if (__uniq$10.tag === "EST$Out$ok") {
                            const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__4);
                            return __uniq$12;
                          } else if (__uniq$10.tag === "EST$Out$error") {
                            return __uniq$10;
                          }
                        } else if (main$__closed__7.tag === "Option$some") {
                          const __uniq$9 = String(main$__closed__7._1);
                          const __uniq$10 = IO$println$__at__$main$spec__1(__uniq$9);
                          if (__uniq$10.tag === "EST$Out$ok") {
                            const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__4);
                            return __uniq$12;
                          } else if (__uniq$10.tag === "EST$Out$error") {
                            return __uniq$10;
                          }
                        }
                      } else if (__uniq$15.tag === "EST$Out$error") {
                        return __uniq$15;
                      }
                    } else if (main$__closed__10.tag === "Option$some") {
                      const __uniq$15 = IO$println$__at__$main$spec__1(main$__closed__10._1);
                      if (__uniq$15.tag === "EST$Out$ok") {
                        if (main$__closed__7.tag === "Option$none") {
                          const __uniq$9 = String(0);
                          const __uniq$10 = IO$println$__at__$main$spec__1(__uniq$9);
                          if (__uniq$10.tag === "EST$Out$ok") {
                            const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__4);
                            return __uniq$12;
                          } else if (__uniq$10.tag === "EST$Out$error") {
                            return __uniq$10;
                          }
                        } else if (main$__closed__7.tag === "Option$some") {
                          const __uniq$9 = String(main$__closed__7._1);
                          const __uniq$10 = IO$println$__at__$main$spec__1(__uniq$9);
                          if (__uniq$10.tag === "EST$Out$ok") {
                            const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__4);
                            return __uniq$12;
                          } else if (__uniq$10.tag === "EST$Out$error") {
                            return __uniq$10;
                          }
                        }
                      } else if (__uniq$15.tag === "EST$Out$error") {
                        return __uniq$15;
                      }
                    }
                  } else if (__uniq$25.tag === "EST$Out$error") {
                    return __uniq$25;
                  }
                } else if (__uniq$23.tag === "EST$Out$error") {
                  return __uniq$23;
                }
              } else if (__uniq$21.tag === "EST$Out$error") {
                return __uniq$21;
              }
            } else {
              const __uniq$21 = IO$println$__at__$main$spec__0(1);
              if (__uniq$21.tag === "EST$Out$ok") {
                const __uniq$23 = IO$println$__at__$main$spec__1(main$__closed__8);
                if (__uniq$23.tag === "EST$Out$ok") {
                  const __uniq$25 = IO$println$__at__$main$spec__1(main$__closed__9);
                  if (__uniq$25.tag === "EST$Out$ok") {
                    if (main$__closed__10.tag === "Option$none") {
                      const __uniq$15 = IO$println$__at__$main$spec__1("none");
                      if (__uniq$15.tag === "EST$Out$ok") {
                        if (main$__closed__7.tag === "Option$none") {
                          const __uniq$9 = String(0);
                          const __uniq$10 = IO$println$__at__$main$spec__1(__uniq$9);
                          if (__uniq$10.tag === "EST$Out$ok") {
                            const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__4);
                            return __uniq$12;
                          } else if (__uniq$10.tag === "EST$Out$error") {
                            return __uniq$10;
                          }
                        } else if (main$__closed__7.tag === "Option$some") {
                          const __uniq$9 = String(main$__closed__7._1);
                          const __uniq$10 = IO$println$__at__$main$spec__1(__uniq$9);
                          if (__uniq$10.tag === "EST$Out$ok") {
                            const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__4);
                            return __uniq$12;
                          } else if (__uniq$10.tag === "EST$Out$error") {
                            return __uniq$10;
                          }
                        }
                      } else if (__uniq$15.tag === "EST$Out$error") {
                        return __uniq$15;
                      }
                    } else if (main$__closed__10.tag === "Option$some") {
                      const __uniq$15 = IO$println$__at__$main$spec__1(main$__closed__10._1);
                      if (__uniq$15.tag === "EST$Out$ok") {
                        if (main$__closed__7.tag === "Option$none") {
                          const __uniq$9 = String(0);
                          const __uniq$10 = IO$println$__at__$main$spec__1(__uniq$9);
                          if (__uniq$10.tag === "EST$Out$ok") {
                            const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__4);
                            return __uniq$12;
                          } else if (__uniq$10.tag === "EST$Out$error") {
                            return __uniq$10;
                          }
                        } else if (main$__closed__7.tag === "Option$some") {
                          const __uniq$9 = String(main$__closed__7._1);
                          const __uniq$10 = IO$println$__at__$main$spec__1(__uniq$9);
                          if (__uniq$10.tag === "EST$Out$ok") {
                            const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__4);
                            return __uniq$12;
                          } else if (__uniq$10.tag === "EST$Out$error") {
                            return __uniq$10;
                          }
                        }
                      } else if (__uniq$15.tag === "EST$Out$error") {
                        return __uniq$15;
                      }
                    }
                  } else if (__uniq$25.tag === "EST$Out$error") {
                    return __uniq$25;
                  }
                } else if (__uniq$23.tag === "EST$Out$error") {
                  return __uniq$23;
                }
              } else if (__uniq$21.tag === "EST$Out$error") {
                return __uniq$21;
              }
            }
          } else if (__uniq$31.tag === "EST$Out$error") {
            return __uniq$31;
          }
        } else {
          const __uniq$31 = IO$println$__at__$main$spec__0(1);
          if (__uniq$31.tag === "EST$Out$ok") {
            if (main$__closed__14) {
              const __uniq$21 = IO$println$__at__$main$spec__0(0);
              if (__uniq$21.tag === "EST$Out$ok") {
                const __uniq$23 = IO$println$__at__$main$spec__1(main$__closed__8);
                if (__uniq$23.tag === "EST$Out$ok") {
                  const __uniq$25 = IO$println$__at__$main$spec__1(main$__closed__9);
                  if (__uniq$25.tag === "EST$Out$ok") {
                    if (main$__closed__10.tag === "Option$none") {
                      const __uniq$15 = IO$println$__at__$main$spec__1("none");
                      if (__uniq$15.tag === "EST$Out$ok") {
                        if (main$__closed__7.tag === "Option$none") {
                          const __uniq$9 = String(0);
                          const __uniq$10 = IO$println$__at__$main$spec__1(__uniq$9);
                          if (__uniq$10.tag === "EST$Out$ok") {
                            const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__4);
                            return __uniq$12;
                          } else if (__uniq$10.tag === "EST$Out$error") {
                            return __uniq$10;
                          }
                        } else if (main$__closed__7.tag === "Option$some") {
                          const __uniq$9 = String(main$__closed__7._1);
                          const __uniq$10 = IO$println$__at__$main$spec__1(__uniq$9);
                          if (__uniq$10.tag === "EST$Out$ok") {
                            const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__4);
                            return __uniq$12;
                          } else if (__uniq$10.tag === "EST$Out$error") {
                            return __uniq$10;
                          }
                        }
                      } else if (__uniq$15.tag === "EST$Out$error") {
                        return __uniq$15;
                      }
                    } else if (main$__closed__10.tag === "Option$some") {
                      const __uniq$15 = IO$println$__at__$main$spec__1(main$__closed__10._1);
                      if (__uniq$15.tag === "EST$Out$ok") {
                        if (main$__closed__7.tag === "Option$none") {
                          const __uniq$9 = String(0);
                          const __uniq$10 = IO$println$__at__$main$spec__1(__uniq$9);
                          if (__uniq$10.tag === "EST$Out$ok") {
                            const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__4);
                            return __uniq$12;
                          } else if (__uniq$10.tag === "EST$Out$error") {
                            return __uniq$10;
                          }
                        } else if (main$__closed__7.tag === "Option$some") {
                          const __uniq$9 = String(main$__closed__7._1);
                          const __uniq$10 = IO$println$__at__$main$spec__1(__uniq$9);
                          if (__uniq$10.tag === "EST$Out$ok") {
                            const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__4);
                            return __uniq$12;
                          } else if (__uniq$10.tag === "EST$Out$error") {
                            return __uniq$10;
                          }
                        }
                      } else if (__uniq$15.tag === "EST$Out$error") {
                        return __uniq$15;
                      }
                    }
                  } else if (__uniq$25.tag === "EST$Out$error") {
                    return __uniq$25;
                  }
                } else if (__uniq$23.tag === "EST$Out$error") {
                  return __uniq$23;
                }
              } else if (__uniq$21.tag === "EST$Out$error") {
                return __uniq$21;
              }
            } else {
              const __uniq$21 = IO$println$__at__$main$spec__0(1);
              if (__uniq$21.tag === "EST$Out$ok") {
                const __uniq$23 = IO$println$__at__$main$spec__1(main$__closed__8);
                if (__uniq$23.tag === "EST$Out$ok") {
                  const __uniq$25 = IO$println$__at__$main$spec__1(main$__closed__9);
                  if (__uniq$25.tag === "EST$Out$ok") {
                    if (main$__closed__10.tag === "Option$none") {
                      const __uniq$15 = IO$println$__at__$main$spec__1("none");
                      if (__uniq$15.tag === "EST$Out$ok") {
                        if (main$__closed__7.tag === "Option$none") {
                          const __uniq$9 = String(0);
                          const __uniq$10 = IO$println$__at__$main$spec__1(__uniq$9);
                          if (__uniq$10.tag === "EST$Out$ok") {
                            const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__4);
                            return __uniq$12;
                          } else if (__uniq$10.tag === "EST$Out$error") {
                            return __uniq$10;
                          }
                        } else if (main$__closed__7.tag === "Option$some") {
                          const __uniq$9 = String(main$__closed__7._1);
                          const __uniq$10 = IO$println$__at__$main$spec__1(__uniq$9);
                          if (__uniq$10.tag === "EST$Out$ok") {
                            const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__4);
                            return __uniq$12;
                          } else if (__uniq$10.tag === "EST$Out$error") {
                            return __uniq$10;
                          }
                        }
                      } else if (__uniq$15.tag === "EST$Out$error") {
                        return __uniq$15;
                      }
                    } else if (main$__closed__10.tag === "Option$some") {
                      const __uniq$15 = IO$println$__at__$main$spec__1(main$__closed__10._1);
                      if (__uniq$15.tag === "EST$Out$ok") {
                        if (main$__closed__7.tag === "Option$none") {
                          const __uniq$9 = String(0);
                          const __uniq$10 = IO$println$__at__$main$spec__1(__uniq$9);
                          if (__uniq$10.tag === "EST$Out$ok") {
                            const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__4);
                            return __uniq$12;
                          } else if (__uniq$10.tag === "EST$Out$error") {
                            return __uniq$10;
                          }
                        } else if (main$__closed__7.tag === "Option$some") {
                          const __uniq$9 = String(main$__closed__7._1);
                          const __uniq$10 = IO$println$__at__$main$spec__1(__uniq$9);
                          if (__uniq$10.tag === "EST$Out$ok") {
                            const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__4);
                            return __uniq$12;
                          } else if (__uniq$10.tag === "EST$Out$error") {
                            return __uniq$10;
                          }
                        }
                      } else if (__uniq$15.tag === "EST$Out$error") {
                        return __uniq$15;
                      }
                    }
                  } else if (__uniq$25.tag === "EST$Out$error") {
                    return __uniq$25;
                  }
                } else if (__uniq$23.tag === "EST$Out$error") {
                  return __uniq$23;
                }
              } else if (__uniq$21.tag === "EST$Out$error") {
                return __uniq$21;
              }
            }
          } else if (__uniq$31.tag === "EST$Out$error") {
            return __uniq$31;
          }
        }
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const instReprR = () => instReprR$repr;
export const instBEqR = () => instBEqR$__closed__0;

main();
