// Generated by Lean ES6 emitter
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const IO$print$__at__$IO$println$__at__$test$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const main$__lam__0 = (/* tagged */ __uniq$1) => ({ tag: "EST$Out$ok", _1: { tag: "Option$some", _1: { tag: "List$cons", _1: "a", _2: { tag: "List$cons", _1: "b", _2: { tag: "List$cons", _1: "c", _2: { tag: "List$nil" } } } } } });
export const IO$println$__at__$test$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$test$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const List$forM$__at__$test$spec__1 = (/* tobj */ __uniq$1) => {
  while (true) {
    if (__uniq$1.tag === "List$nil") {
      return { tag: "EST$Out$ok", _1: { tag: "PUnit$unit" } };
    } else if (__uniq$1.tag === "List$cons") {
      const __uniq$5 = __uniq$1._1;
      const __uniq$6 = __uniq$1._2;
      const __uniq$7 = IO$println$__at__$test$spec__0(__uniq$5);
      if (__uniq$7.tag === "EST$Out$ok") {
        __uniq$1 = __uniq$6;
        continue;
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    }
  }
};
export const test = (/* obj */ __uniq$1) => {
  const __uniq$3 = { tag: "PUnit$unit" };
  const __uniq$4 = __uniq$1(__uniq$3);
  if (__uniq$4.tag === "EST$Out$ok") {
    if (__uniq$4._1.tag === "Option$none") {
      return { tag: "EST$Out$ok", _1: __uniq$3 };
    } else if (__uniq$4._1.tag === "Option$some") {
      const __uniq$10 = List$forM$__at__$test$spec__1(__uniq$4._1._1);
      return __uniq$10;
    }
  } else if (__uniq$4.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$4._1 };
  }
};
export const main$__lam__1 = (/* tagged */ __uniq$1) => ({ tag: "EST$Out$ok", _1: { tag: "Option$none" } });
export const main = () => {
  const __uniq$2 = main$__lam__0;
  const __uniq$3 = test(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = test(main$__lam__1);
    return __uniq$5;
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};

main();
