// Generated by Lean ES6 emitter
import { Function$comp } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main$__lam__0 = (/* tagged */ __uniq$1) => IO$println$__at__$main$spec__0("test1");
export const instMonadMyId$__lam__10 = (/* tobj */ __uniq$3, /* tobj */ __uniq$4, /* tagged */ __uniq$5) => __uniq$4({ tag: "PUnit$unit" }, __uniq$5);
export const test2$__redArg = (/* tobj */ __uniq$1, /* tagged */ __uniq$2) => __uniq$1({ tag: "PUnit$unit" }, __uniq$2);
export const test2 = (/* tobj */ __uniq$2, /* tagged */ __uniq$3) => test2$__redArg(__uniq$2, __uniq$3);
export const instMonadMyId$__lam__3 = (/* tobj */ __uniq$3, /* tobj */ __uniq$4, /* tagged */ __uniq$5) => __uniq$4(__uniq$3({ tag: "PUnit$unit" }), __uniq$5);
export const instMonadMyId$__lam__8 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tagged */ __uniq$3) => __uniq$1;
export const instMonadMyId$__lam__7 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3, /* tagged */ __uniq$4) => __uniq$2(__uniq$1({ tag: "PUnit$unit" }), instMonadMyId$__lam__8.length - 1 === 0 ? () => instMonadMyId$__lam__8(__uniq$3) : instMonadMyId$__lam__8.length - 1 === 1 ? (x_1) => instMonadMyId$__lam__8(__uniq$3, x_1) : instMonadMyId$__lam__8.length - 1 === 2 ? (x_1, x_2) => instMonadMyId$__lam__8(__uniq$3, x_1, x_2) : (x_1, x_2, x_3) => instMonadMyId$__lam__8(__uniq$3, x_1, x_2, x_3), __uniq$4);
export const instMonadMyId$__lam__9 = (/* tobj */ __uniq$1, /* tobj */ __uniq$4, /* tobj */ __uniq$5, /* tagged */ __uniq$6) => __uniq$1(__uniq$4, instMonadMyId$__lam__7.length - 2 === 0 ? () => instMonadMyId$__lam__7(__uniq$5, __uniq$1) : instMonadMyId$__lam__7.length - 2 === 1 ? (x_1) => instMonadMyId$__lam__7(__uniq$5, __uniq$1, x_1) : instMonadMyId$__lam__7.length - 2 === 2 ? (x_1, x_2) => instMonadMyId$__lam__7(__uniq$5, __uniq$1, x_1, x_2) : (x_1, x_2, x_3) => instMonadMyId$__lam__7(__uniq$5, __uniq$1, x_1, x_2, x_3), __uniq$6);
export const instMonadMyId$__closed__6 = (() => {
  const __uniq$1 = instMonadMyId$__lam__3;
  const __uniq$2 = instMonadMyId$__lam__9.length - 1 === 0 ? () => instMonadMyId$__lam__9(__uniq$1) : instMonadMyId$__lam__9.length - 1 === 1 ? (x_1) => instMonadMyId$__lam__9(__uniq$1, x_1) : instMonadMyId$__lam__9.length - 1 === 2 ? (x_1, x_2) => instMonadMyId$__lam__9(__uniq$1, x_1, x_2) : (x_1, x_2, x_3) => instMonadMyId$__lam__9(__uniq$1, x_1, x_2, x_3);
  return __uniq$2;
})();
export const test1 = (/* obj */ __uniq$1) => __uniq$1({ tag: "PUnit$unit" });
export const instMonadMyId$__lam__4 = (/* tobj */ __uniq$1, /* tagged */ __uniq$2) => __uniq$1;
export const instMonadMyId$__lam__1 = (/* tobj */ __uniq$3, /* tobj */ __uniq$4, /* tagged */ __uniq$5) => __uniq$3;
export const instMonadMyId$__lam__0 = (/* tobj */ __uniq$3, /* tobj */ __uniq$4, /* tagged */ __uniq$5) => __uniq$3(__uniq$4({ tag: "PUnit$unit" }));
export const instMonadMyId$__lam__5 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3, /* tobj */ __uniq$4, /* tagged */ __uniq$5) => __uniq$3(__uniq$1({ tag: "PUnit$unit" }), Function$comp.length - 2 === 0 ? () => Function$comp(__uniq$2, __uniq$4) : Function$comp.length - 2 === 1 ? (x_1) => Function$comp(__uniq$2, __uniq$4, x_1) : Function$comp.length - 2 === 2 ? (x_1, x_2) => Function$comp(__uniq$2, __uniq$4, x_1, x_2) : (x_1, x_2, x_3) => Function$comp(__uniq$2, __uniq$4, x_1, x_2, x_3), __uniq$5);
export const main$__lam__1 = (/* tagged */ __uniq$1, /* tagged */ __uniq$2) => "test2";
export const main$__closed__2 = test2$__redArg(main$__lam__1, { tag: "PUnit$unit" });
export const main = () => {
  const __uniq$2 = main$__lam__0;
  const __uniq$3 = test1(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__2);
    return __uniq$5;
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const instMonadMyId$__lam__6 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$5, /* tobj */ __uniq$6, /* tagged */ __uniq$7) => __uniq$2(__uniq$5, instMonadMyId$__lam__5.length - 3 === 0 ? () => instMonadMyId$__lam__5(__uniq$6, __uniq$1, __uniq$2) : instMonadMyId$__lam__5.length - 3 === 1 ? (x_1) => instMonadMyId$__lam__5(__uniq$6, __uniq$1, __uniq$2, x_1) : instMonadMyId$__lam__5.length - 3 === 2 ? (x_1, x_2) => instMonadMyId$__lam__5(__uniq$6, __uniq$1, __uniq$2, x_1, x_2) : (x_1, x_2, x_3) => instMonadMyId$__lam__5(__uniq$6, __uniq$1, __uniq$2, x_1, x_2, x_3), __uniq$7);
export const instMonadMyId$__closed__5 = (() => {
  const __uniq$1 = instMonadMyId$__lam__3;
  const __uniq$2 = instMonadMyId$__lam__4;
  const __uniq$3 = instMonadMyId$__lam__6.length - 2 === 0 ? () => instMonadMyId$__lam__6(__uniq$2, __uniq$1) : instMonadMyId$__lam__6.length - 2 === 1 ? (x_1) => instMonadMyId$__lam__6(__uniq$2, __uniq$1, x_1) : instMonadMyId$__lam__6.length - 2 === 2 ? (x_1, x_2) => instMonadMyId$__lam__6(__uniq$2, __uniq$1, x_1, x_2) : (x_1, x_2, x_3) => instMonadMyId$__lam__6(__uniq$2, __uniq$1, x_1, x_2, x_3);
  return __uniq$3;
})();
export const instMonadMyId$__lam__2 = (/* tobj */ __uniq$2, /* tagged */ __uniq$3) => __uniq$2;
export const instMonadMyId = () => ({ tag: "Monad$mk", _1: { tag: "Applicative$mk", _1: { tag: "Functor$mk", _1: instMonadMyId$__lam__0, _2: instMonadMyId$__lam__1 }, _2: instMonadMyId$__lam__2, _3: instMonadMyId$__closed__5, _4: instMonadMyId$__closed__6, _5: instMonadMyId$__lam__10 }, _2: instMonadMyId$__lam__3 });

main();
