// Generated by Lean ES6 emitter
import { lean_array_uget_borrowed } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Array/Basic.js";
import { Std$Format$pretty } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Format/Basic.js";
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { Repr$addAppParen } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Repr.js";
import { lean_usize_add, lean_usize_of_nat } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/UInt/BasicAux.js";
import { lean_array_push } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const IO$print$__at__$IO$println$__at__$test1$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$test2$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$test1$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg = (/* USize */ __uniq$1, /* USize */ __uniq$2, /* tagged */ __uniq$3) => {
  while (true) {
    const __uniq$5 = __uniq$1 === __uniq$2;
    if (__uniq$5) {
      return { tag: "EST$Out$ok", _1: __uniq$3 };
    } else {
      const __uniq$7 = IO$println$__at__$test2$spec__0("wat");
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$10 = lean_usize_add(__uniq$1, 1);
        const _tmp_1 = __uniq$2;
        __uniq$1 = __uniq$10;
        __uniq$2 = _tmp_1;
        __uniq$3 = __uniq$7._1;
        continue;
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    }
  }
};
export const IO$println$__at__$test1$spec__0 = (/* tobj */ __uniq$1) => {
  const __uniq$3 = 120;
  const __uniq$4 = 0;
  const __uniq$5 = Std$Format$pretty(__uniq$1, __uniq$3, __uniq$4, __uniq$4);
  const __uniq$6 = 10;
  const __uniq$7 = __uniq$5 + String.fromCodePoint(__uniq$6);
  const __uniq$8 = IO$print$__at__$IO$println$__at__$test1$spec__0$spec__0(__uniq$7);
  return __uniq$8;
};
export const __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$__private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__2$spec__2 = (/* obj */ __uniq$1, /* USize */ __uniq$2, /* USize */ __uniq$3, /* tagged */ __uniq$4) => {
  while (true) {
    const __uniq$12 = __uniq$2 === __uniq$3;
    if (__uniq$12) {
      return { tag: "EST$Out$ok", _1: __uniq$4 };
    } else {
      const __uniq$13 = lean_array_uget_borrowed(__uniq$1, __uniq$2);
      if (__uniq$13 < 0) {
        const __uniq$20 = String(__uniq$13);
        const __uniq$22 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$20 }, 0);
        const __uniq$23 = IO$println$__at__$test1$spec__0(__uniq$22);
        {
          if (__uniq$23.tag === "EST$Out$ok") {
            const __uniq$9 = lean_usize_add(__uniq$2, 1);
            const _tmp_0 = __uniq$1;
            const _tmp_2 = __uniq$3;
            __uniq$1 = _tmp_0;
            __uniq$2 = __uniq$9;
            __uniq$3 = _tmp_2;
            __uniq$4 = __uniq$23._1;
            continue;
          } else if (__uniq$23.tag === "EST$Out$error") {
            return __uniq$23;
          }
        }
      } else {
        const __uniq$17 = String(__uniq$13);
        const __uniq$19 = IO$println$__at__$test1$spec__0({ tag: "Std$Format$text", _1: __uniq$17 });
        {
          if (__uniq$19.tag === "EST$Out$ok") {
            const __uniq$9 = lean_usize_add(__uniq$2, 1);
            const _tmp_0 = __uniq$1;
            const _tmp_2 = __uniq$3;
            __uniq$1 = _tmp_0;
            __uniq$2 = __uniq$9;
            __uniq$3 = _tmp_2;
            __uniq$4 = __uniq$19._1;
            continue;
          } else if (__uniq$19.tag === "EST$Out$error") {
            return __uniq$19;
          }
        }
      }
    }
  }
};
export const __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__2 = (/* obj */ __uniq$1, /* USize */ __uniq$2, /* USize */ __uniq$3, /* tagged */ __uniq$4) => {
  const __uniq$12 = __uniq$2 === __uniq$3;
  if (__uniq$12) {
    return { tag: "EST$Out$ok", _1: __uniq$4 };
  } else {
    const __uniq$13 = lean_array_uget_borrowed(__uniq$1, __uniq$2);
    if (__uniq$13 < 0) {
      const __uniq$20 = String(__uniq$13);
      const __uniq$22 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$20 }, 0);
      const __uniq$23 = IO$println$__at__$test1$spec__0(__uniq$22);
      {
        if (__uniq$23.tag === "EST$Out$ok") {
          const __uniq$9 = lean_usize_add(__uniq$2, 1);
          const __uniq$10 = __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$__private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__2$spec__2(__uniq$1, __uniq$9, __uniq$3, __uniq$23._1);
          return __uniq$10;
        } else if (__uniq$23.tag === "EST$Out$error") {
          return __uniq$23;
        }
      }
    } else {
      const __uniq$17 = String(__uniq$13);
      const __uniq$19 = IO$println$__at__$test1$spec__0({ tag: "Std$Format$text", _1: __uniq$17 });
      {
        if (__uniq$19.tag === "EST$Out$ok") {
          const __uniq$9 = lean_usize_add(__uniq$2, 1);
          const __uniq$10 = __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$__private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__2$spec__2(__uniq$1, __uniq$9, __uniq$3, __uniq$19._1);
          return __uniq$10;
        } else if (__uniq$19.tag === "EST$Out$error") {
          return __uniq$19;
        }
      }
    }
  }
};
export const test2 = (/* obj */ __uniq$1) => {
  const __uniq$3 = 42;
  const __uniq$4 = __uniq$1(__uniq$3);
  const __uniq$5 = 0;
  const __uniq$6 = __uniq$4.length;
  const __uniq$33 = __uniq$5 < __uniq$6;
  if (__uniq$33) {
    const __uniq$34 = { tag: "PUnit$unit" };
    if (__uniq$6 <= __uniq$6) {
      const __uniq$40 = lean_usize_of_nat(__uniq$6);
      const __uniq$41 = __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__2(__uniq$4, 0, __uniq$40, __uniq$34);
      {
        if (__uniq$41.tag === "EST$Out$ok") {
          const __uniq$21 = __uniq$5 < __uniq$6;
          if (__uniq$21) {
            const __uniq$22 = { tag: "PUnit$unit" };
            if (__uniq$6 <= __uniq$6) {
              const __uniq$28 = lean_usize_of_nat(__uniq$6);
              const __uniq$29 = __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__2(__uniq$4, 0, __uniq$28, __uniq$22);
              {
                if (__uniq$29.tag === "EST$Out$ok") {
                  const __uniq$7 = { tag: "PUnit$unit" };
                  const __uniq$8 = __uniq$5 < __uniq$6;
                  return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
                } else if (__uniq$29.tag === "EST$Out$error") {
                  return __uniq$29;
                }
              }
            } else if (__uniq$21) {
              const __uniq$25 = lean_usize_of_nat(__uniq$6);
              const __uniq$26 = __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__2(__uniq$4, 0, __uniq$25, __uniq$22);
              {
                if (__uniq$26.tag === "EST$Out$ok") {
                  const __uniq$7 = { tag: "PUnit$unit" };
                  const __uniq$8 = __uniq$5 < __uniq$6;
                  return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
                } else if (__uniq$26.tag === "EST$Out$error") {
                  return __uniq$26;
                }
              }
            } else {
              const __uniq$7 = { tag: "PUnit$unit" };
              const __uniq$8 = __uniq$5 < __uniq$6;
              return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
            }
          } else {
            const __uniq$7 = { tag: "PUnit$unit" };
            const __uniq$8 = __uniq$5 < __uniq$6;
            return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
          }
        } else if (__uniq$41.tag === "EST$Out$error") {
          return __uniq$41;
        }
      }
    } else if (__uniq$33) {
      const __uniq$37 = lean_usize_of_nat(__uniq$6);
      const __uniq$38 = __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__2(__uniq$4, 0, __uniq$37, __uniq$34);
      {
        if (__uniq$38.tag === "EST$Out$ok") {
          const __uniq$21 = __uniq$5 < __uniq$6;
          if (__uniq$21) {
            const __uniq$22 = { tag: "PUnit$unit" };
            if (__uniq$6 <= __uniq$6) {
              const __uniq$28 = lean_usize_of_nat(__uniq$6);
              const __uniq$29 = __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__2(__uniq$4, 0, __uniq$28, __uniq$22);
              {
                if (__uniq$29.tag === "EST$Out$ok") {
                  const __uniq$7 = { tag: "PUnit$unit" };
                  const __uniq$8 = __uniq$5 < __uniq$6;
                  return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
                } else if (__uniq$29.tag === "EST$Out$error") {
                  return __uniq$29;
                }
              }
            } else if (__uniq$21) {
              const __uniq$25 = lean_usize_of_nat(__uniq$6);
              const __uniq$26 = __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__2(__uniq$4, 0, __uniq$25, __uniq$22);
              {
                if (__uniq$26.tag === "EST$Out$ok") {
                  const __uniq$7 = { tag: "PUnit$unit" };
                  const __uniq$8 = __uniq$5 < __uniq$6;
                  return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
                } else if (__uniq$26.tag === "EST$Out$error") {
                  return __uniq$26;
                }
              }
            } else {
              const __uniq$7 = { tag: "PUnit$unit" };
              const __uniq$8 = __uniq$5 < __uniq$6;
              return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
            }
          } else {
            const __uniq$7 = { tag: "PUnit$unit" };
            const __uniq$8 = __uniq$5 < __uniq$6;
            return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
          }
        } else if (__uniq$38.tag === "EST$Out$error") {
          return __uniq$38;
        }
      }
    } else {
      const __uniq$21 = __uniq$5 < __uniq$6;
      if (__uniq$21) {
        const __uniq$22 = { tag: "PUnit$unit" };
        if (__uniq$6 <= __uniq$6) {
          const __uniq$28 = lean_usize_of_nat(__uniq$6);
          const __uniq$29 = __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__2(__uniq$4, 0, __uniq$28, __uniq$22);
          {
            if (__uniq$29.tag === "EST$Out$ok") {
              const __uniq$7 = { tag: "PUnit$unit" };
              const __uniq$8 = __uniq$5 < __uniq$6;
              return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
            } else if (__uniq$29.tag === "EST$Out$error") {
              return __uniq$29;
            }
          }
        } else if (__uniq$21) {
          const __uniq$25 = lean_usize_of_nat(__uniq$6);
          const __uniq$26 = __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__2(__uniq$4, 0, __uniq$25, __uniq$22);
          {
            if (__uniq$26.tag === "EST$Out$ok") {
              const __uniq$7 = { tag: "PUnit$unit" };
              const __uniq$8 = __uniq$5 < __uniq$6;
              return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
            } else if (__uniq$26.tag === "EST$Out$error") {
              return __uniq$26;
            }
          }
        } else {
          const __uniq$7 = { tag: "PUnit$unit" };
          const __uniq$8 = __uniq$5 < __uniq$6;
          return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
        }
      } else {
        const __uniq$7 = { tag: "PUnit$unit" };
        const __uniq$8 = __uniq$5 < __uniq$6;
        return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
      }
    }
  } else {
    const __uniq$21 = __uniq$5 < __uniq$6;
    if (__uniq$21) {
      const __uniq$22 = { tag: "PUnit$unit" };
      if (__uniq$6 <= __uniq$6) {
        const __uniq$28 = lean_usize_of_nat(__uniq$6);
        const __uniq$29 = __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__2(__uniq$4, 0, __uniq$28, __uniq$22);
        {
          if (__uniq$29.tag === "EST$Out$ok") {
            const __uniq$7 = { tag: "PUnit$unit" };
            const __uniq$8 = __uniq$5 < __uniq$6;
            return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
          } else if (__uniq$29.tag === "EST$Out$error") {
            return __uniq$29;
          }
        }
      } else if (__uniq$21) {
        const __uniq$25 = lean_usize_of_nat(__uniq$6);
        const __uniq$26 = __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__2(__uniq$4, 0, __uniq$25, __uniq$22);
        {
          if (__uniq$26.tag === "EST$Out$ok") {
            const __uniq$7 = { tag: "PUnit$unit" };
            const __uniq$8 = __uniq$5 < __uniq$6;
            return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
          } else if (__uniq$26.tag === "EST$Out$error") {
            return __uniq$26;
          }
        }
      } else {
        const __uniq$7 = { tag: "PUnit$unit" };
        const __uniq$8 = __uniq$5 < __uniq$6;
        return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
      }
    } else {
      const __uniq$7 = { tag: "PUnit$unit" };
      const __uniq$8 = __uniq$5 < __uniq$6;
      return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
    }
  }
};
export const __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test1$spec__1 = (/* obj */ __uniq$1, /* USize */ __uniq$2, /* USize */ __uniq$3, /* tagged */ __uniq$4) => {
  while (true) {
    const __uniq$16 = __uniq$2 === __uniq$3;
    if (__uniq$16) {
      return { tag: "EST$Out$ok", _1: __uniq$4 };
    } else {
      const __uniq$17 = lean_array_uget_borrowed(__uniq$1, __uniq$2);
      if (__uniq$17 < 0) {
        const __uniq$23 = String(__uniq$17);
        const __uniq$25 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$23 }, 0);
        {
          const __uniq$13 = IO$println$__at__$test1$spec__0(__uniq$25);
          if (__uniq$13.tag === "EST$Out$ok") {
            const __uniq$14 = IO$println$__at__$test1$spec__0(__uniq$25);
            {
              if (__uniq$14.tag === "EST$Out$ok") {
                const __uniq$9 = lean_usize_add(__uniq$2, 1);
                const _tmp_0 = __uniq$1;
                const _tmp_2 = __uniq$3;
                __uniq$1 = _tmp_0;
                __uniq$2 = __uniq$9;
                __uniq$3 = _tmp_2;
                __uniq$4 = __uniq$14._1;
                continue;
              } else if (__uniq$14.tag === "EST$Out$error") {
                return __uniq$14;
              }
            }
          } else if (__uniq$13.tag === "EST$Out$error") {
            if (__uniq$13.tag === "EST$Out$ok") {
              const __uniq$9 = lean_usize_add(__uniq$2, 1);
              const _tmp_0 = __uniq$1;
              const _tmp_2 = __uniq$3;
              __uniq$1 = _tmp_0;
              __uniq$2 = __uniq$9;
              __uniq$3 = _tmp_2;
              __uniq$4 = __uniq$13._1;
              continue;
            } else if (__uniq$13.tag === "EST$Out$error") {
              return __uniq$13;
            }
          }
        }
      } else {
        const __uniq$21 = String(__uniq$17);
        const __uniq$22 = { tag: "Std$Format$text", _1: __uniq$21 };
        {
          const __uniq$13 = IO$println$__at__$test1$spec__0(__uniq$22);
          if (__uniq$13.tag === "EST$Out$ok") {
            const __uniq$14 = IO$println$__at__$test1$spec__0(__uniq$22);
            {
              if (__uniq$14.tag === "EST$Out$ok") {
                const __uniq$9 = lean_usize_add(__uniq$2, 1);
                const _tmp_0 = __uniq$1;
                const _tmp_2 = __uniq$3;
                __uniq$1 = _tmp_0;
                __uniq$2 = __uniq$9;
                __uniq$3 = _tmp_2;
                __uniq$4 = __uniq$14._1;
                continue;
              } else if (__uniq$14.tag === "EST$Out$error") {
                return __uniq$14;
              }
            }
          } else if (__uniq$13.tag === "EST$Out$error") {
            if (__uniq$13.tag === "EST$Out$ok") {
              const __uniq$9 = lean_usize_add(__uniq$2, 1);
              const _tmp_0 = __uniq$1;
              const _tmp_2 = __uniq$3;
              __uniq$1 = _tmp_0;
              __uniq$2 = __uniq$9;
              __uniq$3 = _tmp_2;
              __uniq$4 = __uniq$13._1;
              continue;
            } else if (__uniq$13.tag === "EST$Out$error") {
              return __uniq$13;
            }
          }
        }
      }
    }
  }
};
export const test1 = (/* obj */ __uniq$1) => {
  const __uniq$3 = 42;
  const __uniq$4 = __uniq$1(__uniq$3);
  const __uniq$5 = 0;
  const __uniq$6 = __uniq$4.length;
  const __uniq$7 = { tag: "PUnit$unit" };
  const __uniq$8 = __uniq$5 < __uniq$6;
  return __uniq$8 ? __uniq$6 <= __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test1$spec__1(__uniq$4, 0, lean_usize_of_nat(__uniq$6), __uniq$7) : __uniq$8 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test1$spec__1(__uniq$4, 0, lean_usize_of_nat(__uniq$6), __uniq$7) : { tag: "EST$Out$ok", _1: __uniq$7 } : { tag: "EST$Out$ok", _1: __uniq$7 };
};
export const main$__lam__0 = (/* tobj */ __uniq$1) => lean_array_push(lean_array_push([], __uniq$1), __uniq$1 + 1);
export const main$__lam__1 = (/* tobj */ __uniq$1) => lean_array_push([], __uniq$1);
export const main$__closed__4 = lean_array_push(lean_array_push([], 5), 15);
export const __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test3$spec__0 = (/* obj */ __uniq$1, /* USize */ __uniq$2, /* USize */ __uniq$3, /* tagged */ __uniq$4) => {
  while (true) {
    const __uniq$14 = __uniq$2 === __uniq$3;
    if (__uniq$14) {
      return { tag: "EST$Out$ok", _1: __uniq$4 };
    } else {
      const __uniq$15 = lean_array_uget_borrowed(__uniq$1, __uniq$2);
      if (__uniq$15 < 10) {
        if (__uniq$15 < 0) {
          const __uniq$25 = String(__uniq$15);
          const __uniq$27 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$25 }, 0);
          const __uniq$28 = IO$println$__at__$test1$spec__0(__uniq$27);
          {
            if (__uniq$28.tag === "EST$Out$ok") {
              const __uniq$8 = lean_usize_add(__uniq$2, 1);
              const _tmp_0 = __uniq$1;
              const _tmp_2 = __uniq$3;
              __uniq$1 = _tmp_0;
              __uniq$2 = __uniq$8;
              __uniq$3 = _tmp_2;
              __uniq$4 = __uniq$28._1;
              continue;
            } else if (__uniq$28.tag === "EST$Out$error") {
              return __uniq$28;
            }
          }
        } else {
          const __uniq$22 = String(__uniq$15);
          const __uniq$24 = IO$println$__at__$test1$spec__0({ tag: "Std$Format$text", _1: __uniq$22 });
          {
            if (__uniq$24.tag === "EST$Out$ok") {
              const __uniq$8 = lean_usize_add(__uniq$2, 1);
              const _tmp_0 = __uniq$1;
              const _tmp_2 = __uniq$3;
              __uniq$1 = _tmp_0;
              __uniq$2 = __uniq$8;
              __uniq$3 = _tmp_2;
              __uniq$4 = __uniq$24._1;
              continue;
            } else if (__uniq$24.tag === "EST$Out$error") {
              return __uniq$24;
            }
          }
        }
      } else {
        const __uniq$8 = lean_usize_add(__uniq$2, 1);
        const _tmp_0 = __uniq$1;
        const _tmp_2 = __uniq$3;
        __uniq$1 = _tmp_0;
        __uniq$2 = __uniq$8;
        __uniq$3 = _tmp_2;
        __uniq$4 = { tag: "PUnit$unit" };
        continue;
      }
    }
  }
};
export const test3 = (/* obj */ __uniq$1) => {
  const __uniq$3 = 0;
  const __uniq$4 = __uniq$1.length;
  const __uniq$5 = { tag: "PUnit$unit" };
  const __uniq$6 = __uniq$3 < __uniq$4;
  return __uniq$6 ? __uniq$4 <= __uniq$4 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test3$spec__0(__uniq$1, 0, lean_usize_of_nat(__uniq$4), __uniq$5) : __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test3$spec__0(__uniq$1, 0, lean_usize_of_nat(__uniq$4), __uniq$5) : { tag: "EST$Out$ok", _1: __uniq$5 } : { tag: "EST$Out$ok", _1: __uniq$5 };
};
export const __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test4$spec__0 = (/* obj */ __uniq$1, /* USize */ __uniq$2, /* USize */ __uniq$3, /* tagged */ __uniq$4) => {
  while (true) {
    const __uniq$12 = __uniq$2 === __uniq$3;
    if (__uniq$12) {
      return { tag: "EST$Out$ok", _1: __uniq$4 };
    } else {
      const __uniq$13 = lean_array_uget_borrowed(__uniq$1, __uniq$2);
      if (__uniq$13 < 10) {
        if (__uniq$13 < 0) {
          const __uniq$24 = String(__uniq$13);
          const __uniq$26 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$24 }, 0);
          const __uniq$27 = IO$println$__at__$test1$spec__0(__uniq$26);
          {
            if (__uniq$27.tag === "EST$Out$ok") {
              const __uniq$9 = lean_usize_add(__uniq$2, 1);
              const _tmp_0 = __uniq$1;
              const _tmp_2 = __uniq$3;
              __uniq$1 = _tmp_0;
              __uniq$2 = __uniq$9;
              __uniq$3 = _tmp_2;
              __uniq$4 = __uniq$27._1;
              continue;
            } else if (__uniq$27.tag === "EST$Out$error") {
              return __uniq$27;
            }
          }
        } else {
          const __uniq$21 = String(__uniq$13);
          const __uniq$23 = IO$println$__at__$test1$spec__0({ tag: "Std$Format$text", _1: __uniq$21 });
          {
            if (__uniq$23.tag === "EST$Out$ok") {
              const __uniq$9 = lean_usize_add(__uniq$2, 1);
              const _tmp_0 = __uniq$1;
              const _tmp_2 = __uniq$3;
              __uniq$1 = _tmp_0;
              __uniq$2 = __uniq$9;
              __uniq$3 = _tmp_2;
              __uniq$4 = __uniq$23._1;
              continue;
            } else if (__uniq$23.tag === "EST$Out$error") {
              return __uniq$23;
            }
          }
        }
      } else {
        const __uniq$17 = IO$println$__at__$test2$spec__0("wat");
        {
          if (__uniq$17.tag === "EST$Out$ok") {
            const __uniq$9 = lean_usize_add(__uniq$2, 1);
            const _tmp_0 = __uniq$1;
            const _tmp_2 = __uniq$3;
            __uniq$1 = _tmp_0;
            __uniq$2 = __uniq$9;
            __uniq$3 = _tmp_2;
            __uniq$4 = __uniq$17._1;
            continue;
          } else if (__uniq$17.tag === "EST$Out$error") {
            return __uniq$17;
          }
        }
      }
    }
  }
};
export const test4 = (/* obj */ __uniq$1) => {
  const __uniq$3 = 0;
  const __uniq$4 = __uniq$1.length;
  const __uniq$5 = { tag: "PUnit$unit" };
  const __uniq$6 = __uniq$3 < __uniq$4;
  return __uniq$6 ? __uniq$4 <= __uniq$4 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test4$spec__0(__uniq$1, 0, lean_usize_of_nat(__uniq$4), __uniq$5) : __uniq$6 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test4$spec__0(__uniq$1, 0, lean_usize_of_nat(__uniq$4), __uniq$5) : { tag: "EST$Out$ok", _1: __uniq$5 } : { tag: "EST$Out$ok", _1: __uniq$5 };
};
export const main = () => {
  const __uniq$2 = main$__lam__0;
  const __uniq$3 = test1(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = test2(main$__lam__1);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = test3(main$__closed__4);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$8 = test4(main$__closed__4);
        return __uniq$8;
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1 = (/* obj */ __uniq$1, /* USize */ __uniq$2, /* USize */ __uniq$3, /* tagged */ __uniq$4) => __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test2$spec__1$__redArg(__uniq$2, __uniq$3, __uniq$4);

main();
