// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const main$__lam__0 = (/* tagged */ __uniq$1) => ({ tag: "EST$Out$ok", _1: 1 });
export const instMonadMyEffect$__aux__1$__redArg = (/* tobj */ __uniq$1, /* obj */ __uniq$2) => {
  const __uniq$4 = __uniq$2();
  if (__uniq$4.tag === "EST$Out$ok") {
    const __uniq$8 = __uniq$1(__uniq$4._1);
    return { tag: "EST$Out$ok", _1: __uniq$8 };
  } else if (__uniq$4.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$4._1 };
  }
};
export const instMonadMyEffect$__aux__9 = (/* obj */ __uniq$3, /* obj */ __uniq$4) => {
  const __uniq$6 = __uniq$3();
  if (__uniq$6.tag === "EST$Out$ok") {
    const __uniq$9 = __uniq$4({ tag: "PUnit$unit" });
    if (__uniq$9.tag === "EST$Out$ok") {
      return { tag: "EST$Out$ok", _1: __uniq$6._1 };
    } else if (__uniq$9.tag === "EST$Out$error") {
      return { tag: "EST$Out$error", _1: __uniq$9._1 };
    }
  } else if (__uniq$6.tag === "EST$Out$error") {
    return __uniq$6;
  }
};
export const instMonadMyEffect$__aux__5 = (/* tobj */ __uniq$2) => ({ tag: "EST$Out$ok", _1: __uniq$2 });
export const instMonadMyEffect$__aux__9$__redArg = (/* obj */ __uniq$1, /* obj */ __uniq$2) => {
  const __uniq$4 = __uniq$1();
  if (__uniq$4.tag === "EST$Out$ok") {
    const __uniq$7 = __uniq$2({ tag: "PUnit$unit" });
    if (__uniq$7.tag === "EST$Out$ok") {
      return { tag: "EST$Out$ok", _1: __uniq$4._1 };
    } else if (__uniq$7.tag === "EST$Out$error") {
      return { tag: "EST$Out$error", _1: __uniq$7._1 };
    }
  } else if (__uniq$4.tag === "EST$Out$error") {
    return __uniq$4;
  }
};
export const instMonadMyEffect$__aux__11$__redArg = (/* obj */ __uniq$1, /* obj */ __uniq$2) => {
  const __uniq$4 = __uniq$1();
  if (__uniq$4.tag === "EST$Out$ok") {
    const __uniq$6 = __uniq$2({ tag: "PUnit$unit" });
    return __uniq$6;
  } else if (__uniq$4.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$4._1 };
  }
};
export const instMonadMyEffect$__aux__1 = (/* tobj */ __uniq$3, /* obj */ __uniq$4) => {
  const __uniq$6 = __uniq$4();
  if (__uniq$6.tag === "EST$Out$ok") {
    const __uniq$10 = __uniq$3(__uniq$6._1);
    return { tag: "EST$Out$ok", _1: __uniq$10 };
  } else if (__uniq$6.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$6._1 };
  }
};
export const instMonadMyEffect$__aux__13 = (/* obj */ __uniq$3, /* obj */ __uniq$4) => {
  const __uniq$6 = __uniq$3();
  if (__uniq$6.tag === "EST$Out$ok") {
    const __uniq$8 = __uniq$4(__uniq$6._1);
    return __uniq$8;
  } else if (__uniq$6.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$6._1 };
  }
};
export const instMonadMyEffect$__aux__3 = (/* tobj */ __uniq$3, /* obj */ __uniq$4) => {
  const __uniq$6 = __uniq$4();
  if (__uniq$6.tag === "EST$Out$ok") {
    return { tag: "EST$Out$ok", _1: __uniq$3 };
  } else if (__uniq$6.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$6._1 };
  }
};
export const instMonadMyEffect$__aux__3$__redArg = (/* tobj */ __uniq$1, /* obj */ __uniq$2) => {
  const __uniq$4 = __uniq$2();
  if (__uniq$4.tag === "EST$Out$ok") {
    return { tag: "EST$Out$ok", _1: __uniq$1 };
  } else if (__uniq$4.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$4._1 };
  }
};
export const test = (/* obj */ __uniq$1) => {
  const __uniq$3 = { tag: "PUnit$unit" };
  const __uniq$4 = __uniq$1(__uniq$3);
  if (__uniq$4.tag === "EST$Out$ok") {
    const __uniq$6 = __uniq$1(__uniq$3);
    if (__uniq$6.tag === "EST$Out$ok") {
      return { tag: "EST$Out$ok", _1: __uniq$4._1 + __uniq$6._1 };
    } else if (__uniq$6.tag === "EST$Out$error") {
      return __uniq$6;
    }
  } else if (__uniq$4.tag === "EST$Out$error") {
    return __uniq$4;
  }
};
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main = () => {
  const __uniq$2 = main$__lam__0;
  const __uniq$3 = test(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(__uniq$3._1);
    return __uniq$5;
  } else if (__uniq$3.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$3._1 };
  }
};
export const instMonadMyEffect$__aux__11 = (/* obj */ __uniq$3, /* obj */ __uniq$4) => {
  const __uniq$6 = __uniq$3();
  if (__uniq$6.tag === "EST$Out$ok") {
    const __uniq$8 = __uniq$4({ tag: "PUnit$unit" });
    return __uniq$8;
  } else if (__uniq$6.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$6._1 };
  }
};
export const instMonadMyEffect$__aux__7 = (/* obj */ __uniq$3, /* obj */ __uniq$4) => {
  const __uniq$6 = __uniq$3();
  if (__uniq$6.tag === "EST$Out$ok") {
    const __uniq$9 = __uniq$4({ tag: "PUnit$unit" });
    if (__uniq$9.tag === "EST$Out$ok") {
      const __uniq$13 = __uniq$6._1(__uniq$9._1);
      return { tag: "EST$Out$ok", _1: __uniq$13 };
    } else if (__uniq$9.tag === "EST$Out$error") {
      return { tag: "EST$Out$error", _1: __uniq$9._1 };
    }
  } else if (__uniq$6.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$6._1 };
  }
};
export const instMonadMyEffect$__aux__13$__redArg = (/* obj */ __uniq$1, /* obj */ __uniq$2) => {
  const __uniq$4 = __uniq$1();
  if (__uniq$4.tag === "EST$Out$ok") {
    const __uniq$6 = __uniq$2(__uniq$4._1);
    return __uniq$6;
  } else if (__uniq$4.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$4._1 };
  }
};
export const instMonadMyEffect$__aux__5$__redArg = (/* tobj */ __uniq$1) => ({ tag: "EST$Out$ok", _1: __uniq$1 });
export const instMonadMyEffect = () => ({ tag: "Monad$mk", _1: { tag: "Applicative$mk", _1: { tag: "Functor$mk", _1: instMonadMyEffect$__aux__1, _2: instMonadMyEffect$__aux__3 }, _2: instMonadMyEffect$__aux__5, _3: instMonadMyEffect$__aux__7, _4: instMonadMyEffect$__aux__9, _5: instMonadMyEffect$__aux__11 }, _2: instMonadMyEffect$__aux__13 });
export const instMonadMyEffect$__aux__7$__redArg = (/* obj */ __uniq$1, /* obj */ __uniq$2) => {
  const __uniq$4 = __uniq$1();
  if (__uniq$4.tag === "EST$Out$ok") {
    const __uniq$7 = __uniq$2({ tag: "PUnit$unit" });
    if (__uniq$7.tag === "EST$Out$ok") {
      const __uniq$11 = __uniq$4._1(__uniq$7._1);
      return { tag: "EST$Out$ok", _1: __uniq$11 };
    } else if (__uniq$7.tag === "EST$Out$error") {
      return { tag: "EST$Out$error", _1: __uniq$7._1 };
    }
  } else if (__uniq$4.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$4._1 };
  }
};

main();
