// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const main$__lam__0 = (/* tagged */ __uniq$1) => ({ tag: "EST$Out$ok", _1: 42 });
export const test2 = (/* obj */ __uniq$1) => {
  const __uniq$3 = { tag: "PUnit$unit" };
  const __uniq$4 = __uniq$1(__uniq$3);
  if (__uniq$4.tag === "EST$Out$ok") {
    const __uniq$6 = __uniq$1(__uniq$3);
    if (__uniq$6.tag === "EST$Out$ok") {
      return { tag: "EST$Out$ok", _1: __uniq$4._1 + __uniq$6._1 };
    } else if (__uniq$6.tag === "EST$Out$error") {
      return __uniq$6;
    }
  } else if (__uniq$4.tag === "EST$Out$error") {
    return __uniq$4;
  }
};
export const test1 = () => 1;
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main = () => {
  const __uniq$2 = test1();
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = test2(main$__lam__0);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__0(__uniq$5._1);
      return __uniq$7;
    } else if (__uniq$5.tag === "EST$Out$error") {
      return { tag: "EST$Out$error", _1: __uniq$5._1 };
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};

main();
