// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
import { lean_st_mk_ref, lean_st_ref_get, lean_st_ref_set } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/ST.js";
export const main$__lam__0 = (/* tobj */ __uniq$1, /* tagged */ __uniq$2) => {
  const __uniq$4 = lean_st_ref_get(__uniq$1);
  const __uniq$5 = 1;
  const __uniq$6 = __uniq$4 + __uniq$5;
  const __uniq$7 = lean_st_ref_set(__uniq$1, __uniq$6);
  const __uniq$8 = { tag: "EST$Out$ok", _1: __uniq$6 };
  return __uniq$8;
};
export const test = (/* obj */ __uniq$1) => {
  const __uniq$3 = { tag: "PUnit$unit" };
  const __uniq$4 = __uniq$1(__uniq$3);
  if (__uniq$4.tag === "EST$Out$ok") {
    const __uniq$6 = __uniq$1(__uniq$3);
    if (__uniq$6.tag === "EST$Out$ok") {
      const __uniq$8 = __uniq$1(__uniq$3);
      if (__uniq$8.tag === "EST$Out$ok") {
        const __uniq$10 = __uniq$1(__uniq$3);
        if (__uniq$10.tag === "EST$Out$ok") {
          return { tag: "EST$Out$ok", _1: __uniq$4._1 + (__uniq$6._1 + __uniq$8._1) - __uniq$10._1 };
        } else if (__uniq$10.tag === "EST$Out$error") {
          return __uniq$10;
        }
      } else if (__uniq$8.tag === "EST$Out$error") {
        return __uniq$8;
      }
    } else if (__uniq$6.tag === "EST$Out$error") {
      return __uniq$6;
    }
  } else if (__uniq$4.tag === "EST$Out$error") {
    return __uniq$4;
  }
};
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main = () => {
  const __uniq$2 = 0;
  const __uniq$3 = lean_st_mk_ref(__uniq$2);
  const __uniq$4 = main$__lam__0.length - 1 === 0 ? () => main$__lam__0(__uniq$3) : main$__lam__0.length - 1 === 1 ? (x_1) => main$__lam__0(__uniq$3, x_1) : main$__lam__0.length - 1 === 2 ? (x_1, x_2) => main$__lam__0(__uniq$3, x_1, x_2) : (x_1, x_2, x_3) => main$__lam__0(__uniq$3, x_1, x_2, x_3);
  const __uniq$5 = test(__uniq$4);
  if (__uniq$5.tag === "EST$Out$ok") {
    const __uniq$7 = IO$println$__at__$main$spec__0(__uniq$5._1);
    return __uniq$7;
  } else if (__uniq$5.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$5._1 };
  }
};

main();
