// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Function$comp } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const instMonadMyEffect$__lam__8 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => ({ tag: "EST$Out$ok", _1: __uniq$1 });
export const instMonadMyEffect$__lam__7 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tobj */ __uniq$3) => __uniq$2(__uniq$1({ tag: "PUnit$unit" }), instMonadMyEffect$__lam__8.length - 1 === 0 ? () => instMonadMyEffect$__lam__8(__uniq$3) : instMonadMyEffect$__lam__8.length - 1 === 1 ? (x_1) => instMonadMyEffect$__lam__8(__uniq$3, x_1) : instMonadMyEffect$__lam__8.length - 1 === 2 ? (x_1, x_2) => instMonadMyEffect$__lam__8(__uniq$3, x_1, x_2) : (x_1, x_2, x_3) => instMonadMyEffect$__lam__8(__uniq$3, x_1, x_2, x_3));
export const instMonadMyEffect$__lam__9 = (/* obj */ __uniq$1, /* obj */ __uniq$4, /* obj */ __uniq$5) => __uniq$1(__uniq$4, instMonadMyEffect$__lam__7.length - 2 === 0 ? () => instMonadMyEffect$__lam__7(__uniq$5, __uniq$1) : instMonadMyEffect$__lam__7.length - 2 === 1 ? (x_1) => instMonadMyEffect$__lam__7(__uniq$5, __uniq$1, x_1) : instMonadMyEffect$__lam__7.length - 2 === 2 ? (x_1, x_2) => instMonadMyEffect$__lam__7(__uniq$5, __uniq$1, x_1, x_2) : (x_1, x_2, x_3) => instMonadMyEffect$__lam__7(__uniq$5, __uniq$1, x_1, x_2, x_3));
export const instMonadMyEffect$__lam__0 = (/* tobj */ __uniq$3, /* obj */ __uniq$4) => {
  const __uniq$6 = __uniq$4();
  if (__uniq$6.tag === "EST$Out$ok") {
    const __uniq$10 = __uniq$3(__uniq$6._1);
    return { tag: "EST$Out$ok", _1: __uniq$10 };
  } else if (__uniq$6.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$6._1 };
  }
};
export const instMonadMyEffect$__lam__4 = (/* tobj */ __uniq$1) => ({ tag: "EST$Out$ok", _1: __uniq$1 });
export const instMonadMyEffect$__lam__10 = (/* obj */ __uniq$3, /* obj */ __uniq$4) => {
  const __uniq$6 = __uniq$3();
  if (__uniq$6.tag === "EST$Out$ok") {
    const __uniq$8 = __uniq$4({ tag: "PUnit$unit" });
    return __uniq$8;
  } else if (__uniq$6.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$6._1 };
  }
};
export const instMonadMyEffect$__lam__3 = (/* obj */ __uniq$3, /* obj */ __uniq$4) => {
  const __uniq$6 = __uniq$3();
  if (__uniq$6.tag === "EST$Out$ok") {
    const __uniq$8 = __uniq$4(__uniq$6._1);
    return __uniq$8;
  } else if (__uniq$6.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$6._1 };
  }
};
export const instMonadMyEffect$__lam__5 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* obj */ __uniq$3, /* tobj */ __uniq$4) => __uniq$3(__uniq$1({ tag: "PUnit$unit" }), Function$comp.length - 2 === 0 ? () => Function$comp(__uniq$2, __uniq$4) : Function$comp.length - 2 === 1 ? (x_1) => Function$comp(__uniq$2, __uniq$4, x_1) : Function$comp.length - 2 === 2 ? (x_1, x_2) => Function$comp(__uniq$2, __uniq$4, x_1, x_2) : (x_1, x_2, x_3) => Function$comp(__uniq$2, __uniq$4, x_1, x_2, x_3));
export const instMonadMyEffect$__lam__6 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* obj */ __uniq$5, /* obj */ __uniq$6) => __uniq$2(__uniq$5, instMonadMyEffect$__lam__5.length - 3 === 0 ? () => instMonadMyEffect$__lam__5(__uniq$6, __uniq$1, __uniq$2) : instMonadMyEffect$__lam__5.length - 3 === 1 ? (x_1) => instMonadMyEffect$__lam__5(__uniq$6, __uniq$1, __uniq$2, x_1) : instMonadMyEffect$__lam__5.length - 3 === 2 ? (x_1, x_2) => instMonadMyEffect$__lam__5(__uniq$6, __uniq$1, __uniq$2, x_1, x_2) : (x_1, x_2, x_3) => instMonadMyEffect$__lam__5(__uniq$6, __uniq$1, __uniq$2, x_1, x_2, x_3));
export const instMonadMyEffect$__closed__5 = (() => {
  const __uniq$1 = instMonadMyEffect$__lam__3;
  const __uniq$2 = instMonadMyEffect$__lam__4;
  const __uniq$3 = instMonadMyEffect$__lam__6.length - 2 === 0 ? () => instMonadMyEffect$__lam__6(__uniq$2, __uniq$1) : instMonadMyEffect$__lam__6.length - 2 === 1 ? (x_1) => instMonadMyEffect$__lam__6(__uniq$2, __uniq$1, x_1) : instMonadMyEffect$__lam__6.length - 2 === 2 ? (x_1, x_2) => instMonadMyEffect$__lam__6(__uniq$2, __uniq$1, x_1, x_2) : (x_1, x_2, x_3) => instMonadMyEffect$__lam__6(__uniq$2, __uniq$1, x_1, x_2, x_3);
  return __uniq$3;
})();
export const instMonadMyEffect$__closed__6 = (() => {
  const __uniq$1 = instMonadMyEffect$__lam__3;
  const __uniq$2 = instMonadMyEffect$__lam__9.length - 1 === 0 ? () => instMonadMyEffect$__lam__9(__uniq$1) : instMonadMyEffect$__lam__9.length - 1 === 1 ? (x_1) => instMonadMyEffect$__lam__9(__uniq$1, x_1) : instMonadMyEffect$__lam__9.length - 1 === 2 ? (x_1, x_2) => instMonadMyEffect$__lam__9(__uniq$1, x_1, x_2) : (x_1, x_2, x_3) => instMonadMyEffect$__lam__9(__uniq$1, x_1, x_2, x_3);
  return __uniq$2;
})();
export const instMonadMyEffect$__lam__2 = (/* tobj */ __uniq$2) => ({ tag: "EST$Out$ok", _1: __uniq$2 });
export const instMonadMyEffect$__lam__1 = (/* tobj */ __uniq$3, /* obj */ __uniq$4) => {
  const __uniq$6 = __uniq$4();
  if (__uniq$6.tag === "EST$Out$ok") {
    return { tag: "EST$Out$ok", _1: __uniq$3 };
  } else if (__uniq$6.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$6._1 };
  }
};
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main = () => IO$println$__at__$main$spec__0(2);
export const test$__lam__0 = (/* tobj */ __uniq$1) => ({ tag: "EST$Out$ok", _1: __uniq$1 + __uniq$1 });
export const test$__closed__1 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = test$__lam__0.length - 1 === 0 ? () => test$__lam__0(__uniq$1) : test$__lam__0.length - 1 === 1 ? (x_1) => test$__lam__0(__uniq$1, x_1) : test$__lam__0.length - 1 === 2 ? (x_1, x_2) => test$__lam__0(__uniq$1, x_1, x_2) : (x_1, x_2, x_3) => test$__lam__0(__uniq$1, x_1, x_2, x_3);
  return __uniq$2;
})();
export const test = () => test$__closed__1;
export const instMonadMyEffect = () => ({ tag: "Monad$mk", _1: { tag: "Applicative$mk", _1: { tag: "Functor$mk", _1: instMonadMyEffect$__lam__0, _2: instMonadMyEffect$__lam__1 }, _2: instMonadMyEffect$__lam__2, _3: instMonadMyEffect$__closed__5, _4: instMonadMyEffect$__closed__6, _5: instMonadMyEffect$__lam__10 }, _2: instMonadMyEffect$__lam__3 });

main();
