// Generated by Lean ES6 emitter
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test1 = (/* obj */ __uniq$1, /* tagged */ __uniq$2, /* tagged */ __uniq$3) => __uniq$1(__uniq$2);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* UInt8 */ __uniq$1) => {
  if (__uniq$1) {
    const __uniq$5 = "true" + String.fromCodePoint(10);
    const __uniq$6 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$5);
    return __uniq$6;
  } else {
    const __uniq$5 = "false" + String.fromCodePoint(10);
    const __uniq$6 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$5);
    return __uniq$6;
  }
};
export const main = () => {
  const __uniq$2 = 1;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(0);
    return __uniq$5;
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const test1$__redArg = (/* obj */ __uniq$1, /* tagged */ __uniq$2) => __uniq$1(__uniq$2);

main();
