// Generated by Lean ES6 emitter
import { lean_float_add, lean_float_sub, lean_float_to_string } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Float.js";
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const main$__lam__0 = (/* tagged */ __uniq$1) => 1;
export const prec2__4 = (/* Float */ __uniq$1) => lean_float_add(lean_float_add(lean_float_sub(__uniq$1, __uniq$1), __uniq$1), __uniq$1);
export const sharedElse = (/* UInt8 */ __uniq$1, /* UInt8 */ __uniq$2, /* UInt8 */ __uniq$3) => __uniq$1 ? __uniq$2 ? 1 : __uniq$3 ? 2 : 3 : __uniq$3 ? 2 : 3;
export const main$__closed__8 = (() => {
  const __uniq$1 = 0;
  const __uniq$2 = 1;
  const __uniq$3 = sharedElse(__uniq$2, __uniq$1, __uniq$2);
  return __uniq$3;
})();
export const prec1$__redArg = (/* obj */ __uniq$1) => __uniq$1({ tag: "PUnit$unit" });
export const prec1 = (/* obj */ __uniq$1, /* tagged */ __uniq$2, /* tagged */ __uniq$3) => prec1$__redArg(__uniq$1);
export const prec2__3 = (/* Float */ __uniq$1) => lean_float_add(__uniq$1, lean_float_add(__uniq$1, lean_float_sub(__uniq$1, __uniq$1)));
export const prec2__5 = (/* Float */ __uniq$1) => lean_float_add(lean_float_sub(__uniq$1, __uniq$1), lean_float_add(__uniq$1, __uniq$1));
export const main$__closed__9 = (() => {
  const __uniq$1 = 0;
  const __uniq$2 = sharedElse(__uniq$1, __uniq$1, __uniq$1);
  return __uniq$2;
})();
export const main$__closed__1 = prec1$__redArg(main$__lam__0);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* UInt8 */ __uniq$1) => {
  if (__uniq$1) {
    const __uniq$5 = "true" + String.fromCodePoint(10);
    const __uniq$6 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$5);
    return __uniq$6;
  } else {
    const __uniq$5 = "false" + String.fromCodePoint(10);
    const __uniq$6 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$5);
    return __uniq$6;
  }
};
export const main$__closed__2 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 15;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const prec2__1 = (/* Float */ __uniq$1) => lean_float_add(__uniq$1, lean_float_add(__uniq$1, lean_float_add(__uniq$1, __uniq$1)));
export const main$__closed__3 = prec2__1(main$__closed__2);
export const IO$println$__at__$main$spec__1 = (/* Float */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(lean_float_to_string(__uniq$1) + String.fromCodePoint(10));
export const prec2__2 = (/* Float */ __uniq$1) => lean_float_add(lean_float_add(lean_float_add(__uniq$1, __uniq$1), __uniq$1), __uniq$1);
export const main$__closed__4 = prec2__2(main$__closed__2);
export const main$__closed__5 = prec2__3(main$__closed__2);
export const main$__closed__6 = prec2__4(main$__closed__2);
export const main$__closed__7 = prec2__5(main$__closed__2);
export const IO$println$__at__$main$spec__2 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main = () => {
  const __uniq$2 = main$__closed__1;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__1(main$__closed__3);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__1(main$__closed__4);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__1(main$__closed__5);
        if (__uniq$9.tag === "EST$Out$ok") {
          const __uniq$11 = IO$println$__at__$main$spec__1(main$__closed__6);
          if (__uniq$11.tag === "EST$Out$ok") {
            const __uniq$13 = IO$println$__at__$main$spec__1(main$__closed__7);
            if (__uniq$13.tag === "EST$Out$ok") {
              const __uniq$15 = IO$println$__at__$main$spec__2(main$__closed__8);
              if (__uniq$15.tag === "EST$Out$ok") {
                const __uniq$17 = IO$println$__at__$main$spec__2(main$__closed__9);
                return __uniq$17;
              } else if (__uniq$15.tag === "EST$Out$error") {
                return __uniq$15;
              }
            } else if (__uniq$13.tag === "EST$Out$error") {
              return __uniq$13;
            }
          } else if (__uniq$11.tag === "EST$Out$error") {
            return __uniq$11;
          }
        } else if (__uniq$9.tag === "EST$Out$error") {
          return __uniq$9;
        }
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};

main();
