// Generated by Lean ES6 emitter
import { Std$Format$pretty } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Format/Basic.js";
import { String$quote } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const foldString = (/* tobj */ __uniq$1) => {
  if (__uniq$1.tag === "Option$none") {
    return "";
  } else if (__uniq$1.tag === "Option$some") {
    return __uniq$1._1;
  }
};
export const main$__closed__2 = foldString({ tag: "Option$some", _1: "a" });
export const main$__closed__3 = String$quote(main$__closed__2);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => {
  const __uniq$3 = 120;
  const __uniq$4 = 0;
  const __uniq$5 = Std$Format$pretty(__uniq$1, __uniq$3, __uniq$4, __uniq$4);
  const __uniq$6 = 10;
  const __uniq$7 = __uniq$5 + String.fromCodePoint(__uniq$6);
  const __uniq$8 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$7);
  return __uniq$8;
};
export const main$__closed__5 = foldString({ tag: "Option$none" });
export const main$__closed__6 = String$quote(main$__closed__5);
export const main = () => {
  const __uniq$2 = { tag: "Std$Format$text", _1: main$__closed__3 };
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0({ tag: "Std$Format$text", _1: main$__closed__6 });
    return __uniq$5;
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const test = (/* tobj */ __uniq$1) => foldString(__uniq$1);

main();
