// Generated by Lean ES6 emitter
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test2 = (/* obj */ __uniq$1) => "b";
export const test1 = (/* obj */ __uniq$1) => "a";
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main = () => {
  const __uniq$2 = "a";
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0("b");
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$6 = IO$println$__at__$main$spec__0(__uniq$2);
      if (__uniq$6.tag === "EST$Out$ok") {
        const __uniq$7 = IO$println$__at__$main$spec__0("b");
        return __uniq$7;
      } else if (__uniq$6.tag === "EST$Out$error") {
        return __uniq$6;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const test3 = (/* obj */ __uniq$1) => "a";
export const f = (/* obj */ __uniq$1) => "a";
export const g = (/* obj */ __uniq$1) => "b";
export const test4 = (/* obj */ __uniq$1) => "b";

main();
