// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const fc2__4 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tobj */ __uniq$3) => __uniq$2(__uniq$1(__uniq$2(__uniq$1(__uniq$2(__uniq$3)))));
export const mul4$__redArg = (/* tobj */ __uniq$1) => __uniq$1 * 4;
export const mul4 = (/* tagged */ __uniq$1, /* tobj */ __uniq$2) => mul4$__redArg(__uniq$2);
export const add3$__redArg = (/* tobj */ __uniq$1) => __uniq$1 + 3;
export const add3 = (/* tagged */ __uniq$1, /* tobj */ __uniq$2) => add3$__redArg(__uniq$2);
export const fc3__3 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tobj */ __uniq$3) => {
  const __uniq$4 = { tag: "PUnit$unit" };
  const __uniq$5 = __uniq$2(__uniq$4, __uniq$3);
  const __uniq$6 = __uniq$1(__uniq$4, __uniq$5);
  const __uniq$7 = __uniq$2(__uniq$4, __uniq$6);
  const __uniq$8 = __uniq$1(__uniq$4, __uniq$7);
  return __uniq$8;
};
export const main$__closed__11 = fc3__3(add3, mul4, 2);
export const fc3__1 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tobj */ __uniq$3) => {
  const __uniq$4 = { tag: "PUnit$unit" };
  const __uniq$5 = __uniq$2(__uniq$4, __uniq$3);
  const __uniq$6 = __uniq$1(__uniq$4, __uniq$5);
  return __uniq$6;
};
export const main$__closed__9 = fc3__1(add3, mul4, 2);
export const double = (/* tobj */ __uniq$1) => __uniq$1 * 2;
export const inc = (/* tobj */ __uniq$1) => __uniq$1 + 1;
export const fc2__1 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tobj */ __uniq$3) => __uniq$1(__uniq$2(__uniq$3));
export const main$__closed__3 = fc2__1(inc, double, 5);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const fc2__2 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tobj */ __uniq$3) => __uniq$2(__uniq$1(__uniq$2(__uniq$3)));
export const main$__closed__4 = fc2__2(inc, double, 5);
export const fc2__3 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tobj */ __uniq$3) => __uniq$1(__uniq$2(__uniq$1(__uniq$2(__uniq$3))));
export const main$__closed__5 = fc2__3(inc, double, 5);
export const main$__closed__6 = fc2__4(inc, double, 5);
export const fc3__2 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tobj */ __uniq$3) => {
  const __uniq$4 = { tag: "PUnit$unit" };
  const __uniq$5 = __uniq$2(__uniq$4, __uniq$3);
  const __uniq$6 = __uniq$1(__uniq$4, __uniq$5);
  const __uniq$7 = __uniq$2(__uniq$4, __uniq$6);
  return __uniq$7;
};
export const main$__closed__10 = fc3__2(add3, mul4, 2);
export const fc3__4 = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tobj */ __uniq$3) => {
  const __uniq$4 = { tag: "PUnit$unit" };
  const __uniq$5 = __uniq$2(__uniq$4, __uniq$3);
  const __uniq$6 = __uniq$1(__uniq$4, __uniq$5);
  const __uniq$7 = __uniq$2(__uniq$4, __uniq$6);
  const __uniq$8 = __uniq$1(__uniq$4, __uniq$7);
  const __uniq$9 = __uniq$2(__uniq$4, __uniq$8);
  return __uniq$9;
};
export const main$__closed__12 = fc3__4(add3, mul4, 2);
export const main = () => {
  const __uniq$2 = main$__closed__3;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__4);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__0(main$__closed__5);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__0(main$__closed__6);
        if (__uniq$9.tag === "EST$Out$ok") {
          const __uniq$11 = IO$println$__at__$main$spec__0(main$__closed__9);
          if (__uniq$11.tag === "EST$Out$ok") {
            const __uniq$13 = IO$println$__at__$main$spec__0(main$__closed__10);
            if (__uniq$13.tag === "EST$Out$ok") {
              const __uniq$15 = IO$println$__at__$main$spec__0(main$__closed__11);
              if (__uniq$15.tag === "EST$Out$ok") {
                const __uniq$17 = IO$println$__at__$main$spec__0(main$__closed__12);
                return __uniq$17;
              } else if (__uniq$15.tag === "EST$Out$error") {
                return __uniq$15;
              }
            } else if (__uniq$13.tag === "EST$Out$error") {
              return __uniq$13;
            }
          } else if (__uniq$11.tag === "EST$Out$error") {
            return __uniq$11;
          }
        } else if (__uniq$9.tag === "EST$Out$error") {
          return __uniq$9;
        }
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};

main();
