// Generated by Lean ES6 emitter
import { lean_array_size, lean_array_uget_borrowed } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Array/Basic.js";
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { List$reverse$__redArg } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/List/Basic.js";
import { String$Slice$Pos$nextn, lean_string_utf8_extract } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/String/Basic.js";
import { lean_string_memcmp } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/String/Pattern/Basic.js";
import { lean_usize_add, lean_usize_dec_lt } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/UInt/BasicAux.js";
import { lean_array_fget_borrowed, lean_array_mk, lean_array_push } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const mapF$__redArg$__lam__0 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3, /* tobj */ __uniq$4) => __uniq$2(__uniq$1(__uniq$3), __uniq$4);
export const test$__lam__2 = (/* obj */ __uniq$1) => "2" + __uniq$1;
export const IO$print$__at__$printArray$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$printArray$spec__1 = (/* obj */ __uniq$1, /* USize */ __uniq$2, /* USize */ __uniq$3, /* UInt8 */ __uniq$4) => {
  while (true) {
    const __uniq$6 = __uniq$3 < __uniq$2;
    if (__uniq$6) {
      const __uniq$9 = lean_array_uget_borrowed(__uniq$1, __uniq$3);
      if (__uniq$4) {
        const __uniq$11 = IO$print$__at__$printArray$spec__0("\"");
        if (__uniq$11.tag === "EST$Out$ok") {
          const __uniq$12 = IO$print$__at__$printArray$spec__0(__uniq$9);
          if (__uniq$12.tag === "EST$Out$ok") {
            const __uniq$13 = IO$print$__at__$printArray$spec__0("\"");
            if (__uniq$13.tag === "EST$Out$ok") {
              const __uniq$16 = lean_usize_add(__uniq$3, 1);
              const _tmp_0 = __uniq$1;
              const _tmp_1 = __uniq$2;
              __uniq$1 = _tmp_0;
              __uniq$2 = _tmp_1;
              __uniq$3 = __uniq$16;
              __uniq$4 = 0;
              continue;
            } else if (__uniq$13.tag === "EST$Out$error") {
              return { tag: "EST$Out$error", _1: __uniq$13._1 };
            }
          } else if (__uniq$12.tag === "EST$Out$error") {
            return { tag: "EST$Out$error", _1: __uniq$12._1 };
          }
        } else if (__uniq$11.tag === "EST$Out$error") {
          return { tag: "EST$Out$error", _1: __uniq$11._1 };
        }
      } else {
        const __uniq$38 = IO$print$__at__$printArray$spec__0(", ");
        if (__uniq$38.tag === "EST$Out$ok") {
          const __uniq$11 = IO$print$__at__$printArray$spec__0("\"");
          if (__uniq$11.tag === "EST$Out$ok") {
            const __uniq$12 = IO$print$__at__$printArray$spec__0(__uniq$9);
            if (__uniq$12.tag === "EST$Out$ok") {
              const __uniq$13 = IO$print$__at__$printArray$spec__0("\"");
              if (__uniq$13.tag === "EST$Out$ok") {
                const __uniq$16 = lean_usize_add(__uniq$3, 1);
                const _tmp_0 = __uniq$1;
                const _tmp_1 = __uniq$2;
                __uniq$1 = _tmp_0;
                __uniq$2 = _tmp_1;
                __uniq$3 = __uniq$16;
                __uniq$4 = 0;
                continue;
              } else if (__uniq$13.tag === "EST$Out$error") {
                return { tag: "EST$Out$error", _1: __uniq$13._1 };
              }
            } else if (__uniq$12.tag === "EST$Out$error") {
              return { tag: "EST$Out$error", _1: __uniq$12._1 };
            }
          } else if (__uniq$11.tag === "EST$Out$error") {
            return { tag: "EST$Out$error", _1: __uniq$11._1 };
          }
        } else if (__uniq$38.tag === "EST$Out$error") {
          return { tag: "EST$Out$error", _1: __uniq$38._1 };
        }
      }
    } else {
      return { tag: "EST$Out$ok", _1: __uniq$4 };
    }
  }
};
export const fromArray$loop$__redArg = (/* obj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3, /* tobj */ __uniq$4) => {
  while (true) {
    const __uniq$5 = __uniq$1.length;
    const __uniq$6 = __uniq$3 < __uniq$5;
    if (__uniq$6) {
      const __uniq$8 = __uniq$3 + 1;
      const __uniq$9 = lean_array_fget_borrowed(__uniq$1, __uniq$3);
      const __uniq$10 = __uniq$2(__uniq$9, __uniq$4);
      const _tmp_0 = __uniq$1;
      const _tmp_1 = __uniq$2;
      __uniq$1 = _tmp_0;
      __uniq$2 = _tmp_1;
      __uniq$3 = __uniq$8;
      __uniq$4 = __uniq$10;
      continue;
    } else {
      return __uniq$4;
    }
  }
};
export const fromArray$loop = (/* obj */ __uniq$2, /* tobj */ __uniq$4, /* tobj */ __uniq$5, /* tobj */ __uniq$6) => fromArray$loop$__redArg(__uniq$2, __uniq$4, __uniq$5, __uniq$6);
export const IO$println$__at__$printArray$spec__2 = (/* obj */ __uniq$1) => IO$print$__at__$printArray$spec__0(__uniq$1 + String.fromCodePoint(10));
export const fromArray$__redArg$__lam__0 = (/* obj */ __uniq$1, /* tobj */ __uniq$3, /* tobj */ __uniq$4) => fromArray$loop$__redArg(__uniq$1, __uniq$3, 0, __uniq$4);
export const fromArray = (/* obj */ __uniq$2) => fromArray$__redArg$__lam__0.length - 1 === 0 ? () => fromArray$__redArg$__lam__0(__uniq$2) : fromArray$__redArg$__lam__0.length - 1 === 1 ? (x_1) => fromArray$__redArg$__lam__0(__uniq$2, x_1) : fromArray$__redArg$__lam__0.length - 1 === 2 ? (x_1, x_2) => fromArray$__redArg$__lam__0(__uniq$2, x_1, x_2) : (x_1, x_2, x_3) => fromArray$__redArg$__lam__0(__uniq$2, x_1, x_2, x_3);
export const main$__closed__6 = lean_array_push(lean_array_push(lean_array_push(lean_array_push(lean_array_push(lean_array_push([], 9), 10), 11), 12), 19), 20);
export const test$__lam__0 = (/* tobj */ __uniq$1) => __uniq$1 + 1;
export const test$__lam__1$__closed__1 = new TextEncoder().encode("1").length;
export const test$__lam__1 = (/* obj */ __uniq$1) => {
  const __uniq$2 = "1";
  const __uniq$3 = new TextEncoder().encode(__uniq$1).length;
  const __uniq$4 = test$__lam__1$__closed__1;
  const __uniq$5 = __uniq$4 <= __uniq$3;
  return __uniq$5 ? lean_string_memcmp(__uniq$1, __uniq$2, 0, 0, __uniq$4) ? { tag: "Option$some", _1: lean_string_utf8_extract(__uniq$1, String$Slice$Pos$nextn({ tag: "String$Slice$mk", _1: __uniq$1, _2: 0, _3: __uniq$3 }, 0, 1), __uniq$3) } : { tag: "Option$none" } : { tag: "Option$none" };
};
export const test$__lam__3 = (/* obj */ __uniq$1) => __uniq$1 === "wat" ? 0 : 1;
export const test$__lam__4 = (/* obj */ __uniq$1) => __uniq$1 + "1";
export const mapF$__redArg$__lam__1 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$4, /* tobj */ __uniq$5) => __uniq$2(mapF$__redArg$__lam__0.length - 2 === 0 ? () => mapF$__redArg$__lam__0(__uniq$1, __uniq$4) : mapF$__redArg$__lam__0.length - 2 === 1 ? (x_1) => mapF$__redArg$__lam__0(__uniq$1, __uniq$4, x_1) : mapF$__redArg$__lam__0.length - 2 === 2 ? (x_1, x_2) => mapF$__redArg$__lam__0(__uniq$1, __uniq$4, x_1, x_2) : (x_1, x_2, x_3) => mapF$__redArg$__lam__0(__uniq$1, __uniq$4, x_1, x_2, x_3), __uniq$5);
export const test$__closed__5 = (x_1) => String(x_1);
export const filterMapF$__redArg$__lam__0 = (/* obj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3, /* tobj */ __uniq$4) => {
  const __uniq$5 = __uniq$1(__uniq$3);
  if (__uniq$5.tag === "Option$none") {
    return __uniq$4;
  } else if (__uniq$5.tag === "Option$some") {
    const __uniq$7 = __uniq$2(__uniq$5._1, __uniq$4);
    return __uniq$7;
  }
};
export const filterMapF$__redArg$__lam__1 = (/* obj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$4, /* tobj */ __uniq$5) => __uniq$2(filterMapF$__redArg$__lam__0.length - 2 === 0 ? () => filterMapF$__redArg$__lam__0(__uniq$1, __uniq$4) : filterMapF$__redArg$__lam__0.length - 2 === 1 ? (x_1) => filterMapF$__redArg$__lam__0(__uniq$1, __uniq$4, x_1) : filterMapF$__redArg$__lam__0.length - 2 === 2 ? (x_1, x_2) => filterMapF$__redArg$__lam__0(__uniq$1, __uniq$4, x_1, x_2) : (x_1, x_2, x_3) => filterMapF$__redArg$__lam__0(__uniq$1, __uniq$4, x_1, x_2, x_3), __uniq$5);
export const filterF$__redArg$__lam__0 = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1(__uniq$2) ? { tag: "Option$some", _1: __uniq$2 } : { tag: "Option$none" };
export const filterF$__redArg = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => {
  const __uniq$3 = filterF$__redArg$__lam__0.length - 1 === 0 ? () => filterF$__redArg$__lam__0(__uniq$1) : filterF$__redArg$__lam__0.length - 1 === 1 ? (x_1) => filterF$__redArg$__lam__0(__uniq$1, x_1) : filterF$__redArg$__lam__0.length - 1 === 2 ? (x_1, x_2) => filterF$__redArg$__lam__0(__uniq$1, x_1, x_2) : (x_1, x_2, x_3) => filterF$__redArg$__lam__0(__uniq$1, x_1, x_2, x_3);
  const __uniq$4 = filterMapF$__redArg$__lam__1.length - 2 === 0 ? () => filterMapF$__redArg$__lam__1(__uniq$3, __uniq$2) : filterMapF$__redArg$__lam__1.length - 2 === 1 ? (x_1) => filterMapF$__redArg$__lam__1(__uniq$3, __uniq$2, x_1) : filterMapF$__redArg$__lam__1.length - 2 === 2 ? (x_1, x_2) => filterMapF$__redArg$__lam__1(__uniq$3, __uniq$2, x_1, x_2) : (x_1, x_2, x_3) => filterMapF$__redArg$__lam__1(__uniq$3, __uniq$2, x_1, x_2, x_3);
  return __uniq$4;
};
export const toArray_u39_$__redArg$__lam__0 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => ({ tag: "List$cons", _1: __uniq$1, _2: __uniq$2 });
export const toArray_u39_$__redArg = (/* tobj */ __uniq$1) => lean_array_mk(List$reverse$__redArg(__uniq$1(toArray_u39_$__redArg$__lam__0, { tag: "List$nil" })));
export const test = (/* obj */ __uniq$1) => {
  const __uniq$2 = test$__lam__0;
  const __uniq$3 = test$__lam__1;
  const __uniq$4 = test$__lam__2;
  const __uniq$5 = test$__lam__3;
  const __uniq$6 = test$__lam__4;
  const __uniq$7 = fromArray$__redArg$__lam__0.length - 1 === 0 ? () => fromArray$__redArg$__lam__0(__uniq$1) : fromArray$__redArg$__lam__0.length - 1 === 1 ? (x_1) => fromArray$__redArg$__lam__0(__uniq$1, x_1) : fromArray$__redArg$__lam__0.length - 1 === 2 ? (x_1, x_2) => fromArray$__redArg$__lam__0(__uniq$1, x_1, x_2) : (x_1, x_2, x_3) => fromArray$__redArg$__lam__0(__uniq$1, x_1, x_2, x_3);
  const __uniq$8 = mapF$__redArg$__lam__1.length - 2 === 0 ? () => mapF$__redArg$__lam__1(__uniq$2, __uniq$7) : mapF$__redArg$__lam__1.length - 2 === 1 ? (x_1) => mapF$__redArg$__lam__1(__uniq$2, __uniq$7, x_1) : mapF$__redArg$__lam__1.length - 2 === 2 ? (x_1, x_2) => mapF$__redArg$__lam__1(__uniq$2, __uniq$7, x_1, x_2) : (x_1, x_2, x_3) => mapF$__redArg$__lam__1(__uniq$2, __uniq$7, x_1, x_2, x_3);
  const __uniq$9 = test$__closed__5;
  const __uniq$10 = mapF$__redArg$__lam__1.length - 2 === 0 ? () => mapF$__redArg$__lam__1(__uniq$9, __uniq$8) : mapF$__redArg$__lam__1.length - 2 === 1 ? (x_1) => mapF$__redArg$__lam__1(__uniq$9, __uniq$8, x_1) : mapF$__redArg$__lam__1.length - 2 === 2 ? (x_1, x_2) => mapF$__redArg$__lam__1(__uniq$9, __uniq$8, x_1, x_2) : (x_1, x_2, x_3) => mapF$__redArg$__lam__1(__uniq$9, __uniq$8, x_1, x_2, x_3);
  const __uniq$11 = filterMapF$__redArg$__lam__1.length - 2 === 0 ? () => filterMapF$__redArg$__lam__1(__uniq$3, __uniq$10) : filterMapF$__redArg$__lam__1.length - 2 === 1 ? (x_1) => filterMapF$__redArg$__lam__1(__uniq$3, __uniq$10, x_1) : filterMapF$__redArg$__lam__1.length - 2 === 2 ? (x_1, x_2) => filterMapF$__redArg$__lam__1(__uniq$3, __uniq$10, x_1, x_2) : (x_1, x_2, x_3) => filterMapF$__redArg$__lam__1(__uniq$3, __uniq$10, x_1, x_2, x_3);
  const __uniq$12 = mapF$__redArg$__lam__1.length - 2 === 0 ? () => mapF$__redArg$__lam__1(__uniq$4, __uniq$11) : mapF$__redArg$__lam__1.length - 2 === 1 ? (x_1) => mapF$__redArg$__lam__1(__uniq$4, __uniq$11, x_1) : mapF$__redArg$__lam__1.length - 2 === 2 ? (x_1, x_2) => mapF$__redArg$__lam__1(__uniq$4, __uniq$11, x_1, x_2) : (x_1, x_2, x_3) => mapF$__redArg$__lam__1(__uniq$4, __uniq$11, x_1, x_2, x_3);
  const __uniq$13 = filterF$__redArg(__uniq$5, __uniq$12);
  const __uniq$14 = mapF$__redArg$__lam__1.length - 2 === 0 ? () => mapF$__redArg$__lam__1(__uniq$6, __uniq$13) : mapF$__redArg$__lam__1.length - 2 === 1 ? (x_1) => mapF$__redArg$__lam__1(__uniq$6, __uniq$13, x_1) : mapF$__redArg$__lam__1.length - 2 === 2 ? (x_1, x_2) => mapF$__redArg$__lam__1(__uniq$6, __uniq$13, x_1, x_2) : (x_1, x_2, x_3) => mapF$__redArg$__lam__1(__uniq$6, __uniq$13, x_1, x_2, x_3);
  const __uniq$15 = toArray_u39_$__redArg(__uniq$14);
  return __uniq$15;
};
export const main$__closed__7 = test(main$__closed__6);
export const printArray = (/* obj */ __uniq$1) => {
  const __uniq$3 = "#[";
  const __uniq$4 = IO$print$__at__$printArray$spec__0(__uniq$3);
  if (__uniq$4.tag === "EST$Out$ok") {
    const __uniq$6 = lean_array_size(__uniq$1);
    const __uniq$8 = __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$printArray$spec__1(__uniq$1, __uniq$6, 0, 1);
    if (__uniq$8.tag === "EST$Out$ok") {
      const __uniq$10 = IO$println$__at__$printArray$spec__2("]");
      return __uniq$10;
    } else if (__uniq$8.tag === "EST$Out$error") {
      return { tag: "EST$Out$error", _1: __uniq$8._1 };
    }
  } else if (__uniq$4.tag === "EST$Out$error") {
    return __uniq$4;
  }
};
export const main = () => printArray(main$__closed__7);
export const filterMapF$__redArg = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => filterMapF$__redArg$__lam__1.length - 2 === 0 ? () => filterMapF$__redArg$__lam__1(__uniq$1, __uniq$2) : filterMapF$__redArg$__lam__1.length - 2 === 1 ? (x_1) => filterMapF$__redArg$__lam__1(__uniq$1, __uniq$2, x_1) : filterMapF$__redArg$__lam__1.length - 2 === 2 ? (x_1, x_2) => filterMapF$__redArg$__lam__1(__uniq$1, __uniq$2, x_1, x_2) : (x_1, x_2, x_3) => filterMapF$__redArg$__lam__1(__uniq$1, __uniq$2, x_1, x_2, x_3);
export const filterF = (/* obj */ __uniq$2, /* tobj */ __uniq$3) => filterF$__redArg(__uniq$2, __uniq$3);
export const filterMapF = (/* obj */ __uniq$3, /* tobj */ __uniq$4) => filterMapF$__redArg$__lam__1.length - 2 === 0 ? () => filterMapF$__redArg$__lam__1(__uniq$3, __uniq$4) : filterMapF$__redArg$__lam__1.length - 2 === 1 ? (x_1) => filterMapF$__redArg$__lam__1(__uniq$3, __uniq$4, x_1) : filterMapF$__redArg$__lam__1.length - 2 === 2 ? (x_1, x_2) => filterMapF$__redArg$__lam__1(__uniq$3, __uniq$4, x_1, x_2) : (x_1, x_2, x_3) => filterMapF$__redArg$__lam__1(__uniq$3, __uniq$4, x_1, x_2, x_3);
export const fromArray$__redArg = (/* obj */ __uniq$1) => fromArray$__redArg$__lam__0.length - 1 === 0 ? () => fromArray$__redArg$__lam__0(__uniq$1) : fromArray$__redArg$__lam__0.length - 1 === 1 ? (x_1) => fromArray$__redArg$__lam__0(__uniq$1, x_1) : fromArray$__redArg$__lam__0.length - 1 === 2 ? (x_1, x_2) => fromArray$__redArg$__lam__0(__uniq$1, x_1, x_2) : (x_1, x_2, x_3) => fromArray$__redArg$__lam__0(__uniq$1, x_1, x_2, x_3);
export const mapF = (/* tobj */ __uniq$3, /* tobj */ __uniq$4) => mapF$__redArg$__lam__1.length - 2 === 0 ? () => mapF$__redArg$__lam__1(__uniq$3, __uniq$4) : mapF$__redArg$__lam__1.length - 2 === 1 ? (x_1) => mapF$__redArg$__lam__1(__uniq$3, __uniq$4, x_1) : mapF$__redArg$__lam__1.length - 2 === 2 ? (x_1, x_2) => mapF$__redArg$__lam__1(__uniq$3, __uniq$4, x_1, x_2) : (x_1, x_2, x_3) => mapF$__redArg$__lam__1(__uniq$3, __uniq$4, x_1, x_2, x_3);
export const toArray_u39_ = (/* tobj */ __uniq$2) => toArray_u39_$__redArg(__uniq$2);
export const mapF$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => mapF$__redArg$__lam__1.length - 2 === 0 ? () => mapF$__redArg$__lam__1(__uniq$1, __uniq$2) : mapF$__redArg$__lam__1.length - 2 === 1 ? (x_1) => mapF$__redArg$__lam__1(__uniq$1, __uniq$2, x_1) : mapF$__redArg$__lam__1.length - 2 === 2 ? (x_1, x_2) => mapF$__redArg$__lam__1(__uniq$1, __uniq$2, x_1, x_2) : (x_1, x_2, x_3) => mapF$__redArg$__lam__1(__uniq$1, __uniq$2, x_1, x_2, x_3);

main();
