// Generated by Lean ES6 emitter
import { Std$Format$fill, Std$Format$pretty } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Format/Basic.js";
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { List$range } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/List/Basic.js";
import { List$forIn_u39_$loop$__redArg } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/List/Control.js";
import { Repr$addAppParen, String$quote } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Repr.js";
import { lean_string_length } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/String/Bootstrap.js";
import { Std$Format$joinSep$__at__$List$repr_u39_$__at__$Lean$Syntax$instReprPreresolved$repr$spec__0$spec__0 } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Meta/Defs.js";
import { lean_array_get_borrowed, lean_array_push, lean_array_to_list } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { instMonadEIO, lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const main$__lam__0 = (/* tobj */ __uniq$1, /* obj */ __uniq$2, /* tobj */ __uniq$3) => ({ tag: "EST$Out$ok", _1: { tag: "Result$mk", _1: __uniq$1, _2: __uniq$2, _3: __uniq$3 } });
export const main$__closed__16 = lean_array_push([], "3");
export const Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__2$spec__4$__lam__0 = (/* tobj */ __uniq$1) => __uniq$1 < 0 ? Repr$addAppParen({ tag: "Std$Format$text", _1: String(__uniq$1) }, 0) : { tag: "Std$Format$text", _1: String(__uniq$1) };
export const List$foldl$__at__$List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__2$spec__4$spec__6$spec__10 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  while (true) {
    if (__uniq$3.tag === "List$nil") {
      return __uniq$2;
    } else if (__uniq$3.tag === "List$cons") {
      const __uniq$4 = __uniq$3._1;
      const __uniq$5 = __uniq$3._2;
      {
        const __uniq$22 = { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 };
        {
          if (__uniq$4 < 0) {
            const __uniq$16 = String(__uniq$4);
            const __uniq$18 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$16 }, 0);
            const _tmp_0 = __uniq$1;
            __uniq$1 = _tmp_0;
            __uniq$2 = { tag: "Std$Format$append", _1: __uniq$22, _2: __uniq$18 };
            __uniq$3 = __uniq$5;
            continue;
          } else {
            const __uniq$12 = String(__uniq$4);
            const _tmp_0 = __uniq$1;
            __uniq$1 = _tmp_0;
            __uniq$2 = { tag: "Std$Format$append", _1: __uniq$22, _2: { tag: "Std$Format$text", _1: __uniq$12 } };
            __uniq$3 = __uniq$5;
            continue;
          }
        }
      }
    }
  }
};
export const List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__2$spec__4$spec__6 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  if (__uniq$3.tag === "List$nil") {
    return __uniq$2;
  } else if (__uniq$3.tag === "List$cons") {
    const __uniq$22 = { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 };
    {
      return __uniq$3._1 < 0 ? List$foldl$__at__$List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__2$spec__4$spec__6$spec__10(__uniq$1, { tag: "Std$Format$append", _1: __uniq$22, _2: Repr$addAppParen({ tag: "Std$Format$text", _1: String(__uniq$3._1) }, 0) }, __uniq$3._2) : List$foldl$__at__$List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__2$spec__4$spec__6$spec__10(__uniq$1, { tag: "Std$Format$append", _1: __uniq$22, _2: { tag: "Std$Format$text", _1: String(__uniq$3._1) } }, __uniq$3._2);
    }
  }
};
export const Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__2$spec__4 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1.tag === "List$nil") {
    return { tag: "Std$Format$nil" };
  } else if (__uniq$1.tag === "List$cons") {
    return __uniq$1._2.tag === "List$nil" ? Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__2$spec__4$__lam__0(__uniq$1._1) : List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__2$spec__4$spec__6(__uniq$2, Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__2$spec__4$__lam__0(__uniq$1._1), __uniq$1._2);
  }
};
export const instReprMerged$repr$__redArg$__closed__15 = { tag: "Std$Format$text", _1: "{ " };
export const instReprMerged$repr$__redArg$__closed__13 = lean_string_length("{ ");
export const diffWithIxE$__redArg$__closed__0 = instMonadEIO();
export const diffWithIxE$__redArg$__lam__0 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3, /* obj */ __uniq$4, /* obj */ __uniq$5, /* tobj */ __uniq$6, /* obj */ __uniq$7, /* obj */ __uniq$8, /* obj */ __uniq$9, /* tobj */ __uniq$10, /* obj */ __uniq$12) => {
  const __uniq$14 = __uniq$10 < __uniq$1;
  if (__uniq$14) {
    if (__uniq$10 < __uniq$2) {
      const __uniq$52 = lean_array_get_borrowed(__uniq$6, __uniq$7, __uniq$10);
      const __uniq$53 = lean_array_get_borrowed(__uniq$3, __uniq$4, __uniq$10);
      const __uniq$55 = __uniq$9(__uniq$10, __uniq$52, __uniq$53);
      if (__uniq$55.tag === "EST$Out$ok") {
        const __uniq$59 = lean_array_push(__uniq$12, __uniq$55._1);
        return { tag: "EST$Out$ok", _1: { tag: "ForInStep$yield", _1: __uniq$59 } };
      } else if (__uniq$55.tag === "EST$Out$error") {
        return { tag: "EST$Out$error", _1: __uniq$55._1 };
      }
    } else {
      const __uniq$36 = lean_array_get_borrowed(__uniq$6, __uniq$7, __uniq$10);
      const __uniq$38 = __uniq$8(__uniq$10, __uniq$36);
      if (__uniq$38.tag === "EST$Out$ok") {
        return { tag: "EST$Out$ok", _1: { tag: "ForInStep$yield", _1: __uniq$12 } };
      } else if (__uniq$38.tag === "EST$Out$error") {
        return { tag: "EST$Out$error", _1: __uniq$38._1 };
      }
    }
  } else if (__uniq$10 < __uniq$2) {
    const __uniq$18 = lean_array_get_borrowed(__uniq$3, __uniq$4, __uniq$10);
    const __uniq$20 = __uniq$5(__uniq$10, __uniq$18);
    if (__uniq$20.tag === "EST$Out$ok") {
      const __uniq$24 = lean_array_push(__uniq$12, __uniq$20._1);
      return { tag: "EST$Out$ok", _1: { tag: "ForInStep$yield", _1: __uniq$24 } };
    } else if (__uniq$20.tag === "EST$Out$error") {
      return { tag: "EST$Out$error", _1: __uniq$20._1 };
    }
  } else {
    return { tag: "EST$Out$ok", _1: { tag: "ForInStep$yield", _1: __uniq$12 } };
  }
};
export const diffWithIxE$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* obj */ __uniq$3, /* obj */ __uniq$4, /* obj */ __uniq$5, /* obj */ __uniq$6, /* obj */ __uniq$7) => {
  const __uniq$9 = diffWithIxE$__redArg$__closed__0;
  const __uniq$10 = [];
  const __uniq$11 = __uniq$3.length;
  const __uniq$12 = __uniq$4.length;
  const __uniq$13 = diffWithIxE$__redArg$__lam__0.length - 9 === 0 ? () => diffWithIxE$__redArg$__lam__0(__uniq$11, __uniq$12, __uniq$2, __uniq$4, __uniq$7, __uniq$1, __uniq$3, __uniq$6, __uniq$5) : diffWithIxE$__redArg$__lam__0.length - 9 === 1 ? (x_1) => diffWithIxE$__redArg$__lam__0(__uniq$11, __uniq$12, __uniq$2, __uniq$4, __uniq$7, __uniq$1, __uniq$3, __uniq$6, __uniq$5, x_1) : diffWithIxE$__redArg$__lam__0.length - 9 === 2 ? (x_1, x_2) => diffWithIxE$__redArg$__lam__0(__uniq$11, __uniq$12, __uniq$2, __uniq$4, __uniq$7, __uniq$1, __uniq$3, __uniq$6, __uniq$5, x_1, x_2) : (x_1, x_2, x_3) => diffWithIxE$__redArg$__lam__0(__uniq$11, __uniq$12, __uniq$2, __uniq$4, __uniq$7, __uniq$1, __uniq$3, __uniq$6, __uniq$5, x_1, x_2, x_3);
  const __uniq$19 = __uniq$11 < __uniq$12;
  if (__uniq$19) {
    const __uniq$15 = List$range(__uniq$12);
    const __uniq$16 = List$forIn_u39_$loop$__redArg(__uniq$9, __uniq$13, __uniq$15, __uniq$10);
    const __uniq$17 = __uniq$16();
    return __uniq$17;
  } else {
    const __uniq$15 = List$range(__uniq$11);
    const __uniq$16 = List$forIn_u39_$loop$__redArg(__uniq$9, __uniq$13, __uniq$15, __uniq$10);
    const __uniq$17 = __uniq$16();
    return __uniq$17;
  }
};
export const diffWithIxE = (/* tobj */ __uniq$4, /* tobj */ __uniq$5, /* obj */ __uniq$6, /* obj */ __uniq$7, /* obj */ __uniq$8, /* obj */ __uniq$9, /* obj */ __uniq$10) => diffWithIxE$__redArg(__uniq$4, __uniq$5, __uniq$6, __uniq$7, __uniq$8, __uniq$9, __uniq$10);
export const main$__lam__2 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => ({ tag: "EST$Out$ok", _1: { tag: "Result$mk", _1: __uniq$1, _2: "", _3: __uniq$2 } });
export const instReprMerged$repr$__redArg$__closed__9 = { tag: "Std$Format$text", _1: "," };
export const Array$repr$__at__$main$spec__0$__closed__1 = { tag: "Std$Format$append", _1: instReprMerged$repr$__redArg$__closed__9, _2: { tag: "Std$Format$line" } };
export const Array$repr$__at__$main$spec__0$__closed__3 = lean_string_length("#[");
export const Array$repr$__at__$main$spec__0$__closed__5 = { tag: "Std$Format$text", _1: "#[" };
export const Array$repr$__at__$main$spec__0$__closed__6 = { tag: "Std$Format$text", _1: "]" };
export const Array$repr$__at__$main$spec__0$__closed__8 = { tag: "Std$Format$text", _1: "#[]" };
export const Array$repr$__at__$main$spec__3 = (/* obj */ __uniq$1) => __uniq$1.length === 0 ? Array$repr$__at__$main$spec__0$__closed__8 : Std$Format$fill({ tag: "Std$Format$nest", _1: Array$repr$__at__$main$spec__0$__closed__3, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: Array$repr$__at__$main$spec__0$__closed__5, _2: Std$Format$joinSep$__at__$List$repr_u39_$__at__$Lean$Syntax$instReprPreresolved$repr$spec__0$spec__0(lean_array_to_list(__uniq$1), Array$repr$__at__$main$spec__0$__closed__1) }, _2: Array$repr$__at__$main$spec__0$__closed__6 } });
export const instReprMerged$repr$__redArg$__closed__5 = { tag: "Std$Format$text", _1: " := " };
export const instReprMerged$repr$__redArg$__closed__2 = { tag: "Std$Format$text", _1: "a" };
export const instReprMerged$repr$__redArg$__closed__11 = { tag: "Std$Format$text", _1: "b" };
export const instReprMerged$repr$__redArg$__closed__16 = { tag: "Std$Format$text", _1: " }" };
export const instReprMerged$repr$__redArg = (/* obj */ __uniq$1) => {
  const __uniq$2 = __uniq$1._1;
  const __uniq$3 = __uniq$1._2;
  const __uniq$45 = true;
  {
    const __uniq$9 = String$quote(__uniq$2);
    {
      const __uniq$13 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 5, _2: { tag: "Std$Format$text", _1: __uniq$9 } } };
      __uniq$13._2 = 0;
      const __uniq$21 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$nil" }, _2: instReprMerged$repr$__redArg$__closed__2 }, _2: instReprMerged$repr$__redArg$__closed__5 }, _2: __uniq$13 }, _2: instReprMerged$repr$__redArg$__closed__9 }, _2: { tag: "Std$Format$line" } }, _2: instReprMerged$repr$__redArg$__closed__11 }, _2: instReprMerged$repr$__redArg$__closed__5 };
      if (__uniq$3 < 0) {
        const __uniq$39 = String(__uniq$3);
        const __uniq$41 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$39 }, 0);
        {
          const __uniq$24 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 5, _2: __uniq$41 } };
          __uniq$24._2 = 0;
          const __uniq$32 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprMerged$repr$__redArg$__closed__13, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprMerged$repr$__redArg$__closed__15, _2: { tag: "Std$Format$append", _1: __uniq$21, _2: __uniq$24 } }, _2: instReprMerged$repr$__redArg$__closed__16 } } };
          __uniq$32._2 = 0;
          return __uniq$32;
        }
      } else {
        const __uniq$37 = String(__uniq$3);
        {
          const __uniq$24 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 5, _2: { tag: "Std$Format$text", _1: __uniq$37 } } };
          __uniq$24._2 = 0;
          const __uniq$32 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprMerged$repr$__redArg$__closed__13, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprMerged$repr$__redArg$__closed__15, _2: { tag: "Std$Format$append", _1: __uniq$21, _2: __uniq$24 } }, _2: instReprMerged$repr$__redArg$__closed__16 } } };
          __uniq$32._2 = 0;
          return __uniq$32;
        }
      }
    }
  }
};
export const List$foldl$__at__$List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1$spec__7 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  while (true) {
    if (__uniq$3.tag === "List$nil") {
      return __uniq$2;
    } else if (__uniq$3.tag === "List$cons") {
      const __uniq$4 = __uniq$3._1;
      const __uniq$5 = __uniq$3._2;
      {
        const __uniq$13 = { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 };
        {
          const __uniq$9 = instReprMerged$repr$__redArg(__uniq$4);
          const _tmp_0 = __uniq$1;
          __uniq$1 = _tmp_0;
          __uniq$2 = { tag: "Std$Format$append", _1: __uniq$13, _2: __uniq$9 };
          __uniq$3 = __uniq$5;
          continue;
        }
      }
    }
  }
};
export const main$__closed__17 = Array$repr$__at__$main$spec__3(main$__closed__16);
export const instReprResult$repr$__redArg = (/* obj */ __uniq$1) => {
  const __uniq$2 = __uniq$1._1;
  const __uniq$3 = __uniq$1._2;
  const __uniq$4 = __uniq$1._3;
  const __uniq$20 = instReprMerged$repr$__redArg$__closed__5;
  const __uniq$21 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$nil" }, _2: { tag: "Std$Format$text", _1: "ix" } }, _2: instReprMerged$repr$__redArg$__closed__5 };
  const __uniq$22 = 6;
  const __uniq$55 = 0;
  const __uniq$56 = 0;
  const __uniq$57 = __uniq$2 < __uniq$56;
  if (__uniq$57) {
    const __uniq$60 = String(__uniq$2);
    const __uniq$62 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$60 }, __uniq$55);
    {
      const __uniq$26 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$22, _2: __uniq$62 } };
      __uniq$26._2 = 0;
      const __uniq$30 = { tag: "Std$Format$line" };
      const __uniq$36 = String$quote(__uniq$3);
      const __uniq$39 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 5, _2: { tag: "Std$Format$text", _1: __uniq$36 } } };
      __uniq$39._2 = 0;
      const __uniq$45 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$21, _2: __uniq$26 }, _2: instReprMerged$repr$__redArg$__closed__9 }, _2: __uniq$30 }, _2: instReprMerged$repr$__redArg$__closed__2 }, _2: __uniq$20 }, _2: __uniq$39 }, _2: instReprMerged$repr$__redArg$__closed__9 }, _2: __uniq$30 }, _2: instReprMerged$repr$__redArg$__closed__11 }, _2: __uniq$20 };
      if (__uniq$4 < 0) {
        const __uniq$51 = String(__uniq$4);
        const __uniq$53 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$51 }, 0);
        {
          const __uniq$10 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 5, _2: __uniq$53 } };
          __uniq$10._2 = 0;
          const __uniq$18 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprMerged$repr$__redArg$__closed__13, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprMerged$repr$__redArg$__closed__15, _2: { tag: "Std$Format$append", _1: __uniq$45, _2: __uniq$10 } }, _2: instReprMerged$repr$__redArg$__closed__16 } } };
          __uniq$18._2 = 0;
          return __uniq$18;
        }
      } else {
        const __uniq$49 = String(__uniq$4);
        {
          const __uniq$10 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 5, _2: { tag: "Std$Format$text", _1: __uniq$49 } } };
          __uniq$10._2 = 0;
          const __uniq$18 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprMerged$repr$__redArg$__closed__13, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprMerged$repr$__redArg$__closed__15, _2: { tag: "Std$Format$append", _1: __uniq$45, _2: __uniq$10 } }, _2: instReprMerged$repr$__redArg$__closed__16 } } };
          __uniq$18._2 = 0;
          return __uniq$18;
        }
      }
    }
  } else {
    const __uniq$58 = String(__uniq$2);
    {
      const __uniq$26 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$22, _2: { tag: "Std$Format$text", _1: __uniq$58 } } };
      __uniq$26._2 = 0;
      const __uniq$30 = { tag: "Std$Format$line" };
      const __uniq$36 = String$quote(__uniq$3);
      const __uniq$39 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 5, _2: { tag: "Std$Format$text", _1: __uniq$36 } } };
      __uniq$39._2 = 0;
      const __uniq$45 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$21, _2: __uniq$26 }, _2: instReprMerged$repr$__redArg$__closed__9 }, _2: __uniq$30 }, _2: instReprMerged$repr$__redArg$__closed__2 }, _2: __uniq$20 }, _2: __uniq$39 }, _2: instReprMerged$repr$__redArg$__closed__9 }, _2: __uniq$30 }, _2: instReprMerged$repr$__redArg$__closed__11 }, _2: __uniq$20 };
      if (__uniq$4 < 0) {
        const __uniq$51 = String(__uniq$4);
        const __uniq$53 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$51 }, 0);
        {
          const __uniq$10 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 5, _2: __uniq$53 } };
          __uniq$10._2 = 0;
          const __uniq$18 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprMerged$repr$__redArg$__closed__13, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprMerged$repr$__redArg$__closed__15, _2: { tag: "Std$Format$append", _1: __uniq$45, _2: __uniq$10 } }, _2: instReprMerged$repr$__redArg$__closed__16 } } };
          __uniq$18._2 = 0;
          return __uniq$18;
        }
      } else {
        const __uniq$49 = String(__uniq$4);
        {
          const __uniq$10 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 5, _2: { tag: "Std$Format$text", _1: __uniq$49 } } };
          __uniq$10._2 = 0;
          const __uniq$18 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprMerged$repr$__redArg$__closed__13, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprMerged$repr$__redArg$__closed__15, _2: { tag: "Std$Format$append", _1: __uniq$45, _2: __uniq$10 } }, _2: instReprMerged$repr$__redArg$__closed__16 } } };
          __uniq$18._2 = 0;
          return __uniq$18;
        }
      }
    }
  }
};
export const instReprResult$repr = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => instReprResult$repr$__redArg(__uniq$1);
export const List$foldl$__at__$List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__4$spec__7$spec__10$spec__13 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  while (true) {
    if (__uniq$3.tag === "List$nil") {
      return __uniq$2;
    } else if (__uniq$3.tag === "List$cons") {
      const __uniq$4 = __uniq$3._1;
      const __uniq$5 = __uniq$3._2;
      {
        const __uniq$13 = { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 };
        {
          const __uniq$9 = instReprResult$repr$__redArg(__uniq$4);
          const _tmp_0 = __uniq$1;
          __uniq$1 = _tmp_0;
          __uniq$2 = { tag: "Std$Format$append", _1: __uniq$13, _2: __uniq$9 };
          __uniq$3 = __uniq$5;
          continue;
        }
      }
    }
  }
};
export const List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__4$spec__7$spec__10 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  if (__uniq$3.tag === "List$nil") {
    return __uniq$2;
  } else if (__uniq$3.tag === "List$cons") {
    const __uniq$9 = instReprResult$repr$__redArg(__uniq$3._1);
    const __uniq$11 = List$foldl$__at__$List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__4$spec__7$spec__10$spec__13(__uniq$1, { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 }, _2: __uniq$9 }, __uniq$3._2);
    return __uniq$11;
  }
};
export const Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__4$spec__7 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1.tag === "List$nil") {
    return { tag: "Std$Format$nil" };
  } else if (__uniq$1.tag === "List$cons") {
    return __uniq$1._2.tag === "List$nil" ? instReprResult$repr$__redArg(__uniq$1._1) : List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__4$spec__7$spec__10(__uniq$2, instReprResult$repr$__redArg(__uniq$1._1), __uniq$1._2);
  }
};
export const instReprMerged$repr = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => instReprMerged$repr$__redArg(__uniq$1);
export const instReprMerged = () => instReprMerged$repr;
export const main$__closed__9 = lean_array_push(lean_array_push([], 1), 2);
export const main$__lam__1 = (/* tobj */ __uniq$1, /* obj */ __uniq$2) => ({ tag: "EST$Out$ok", _1: { tag: "PUnit$unit" } });
export const main$__closed__6 = lean_array_push(lean_array_push(lean_array_push([], "1"), "2"), "3");
export const main$__closed__12 = lean_array_push(lean_array_push([], { tag: "Merged$mk", _1: "1", _2: 1 }), { tag: "Merged$mk", _1: "2", _2: 2 });
export const List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  if (__uniq$3.tag === "List$nil") {
    return __uniq$2;
  } else if (__uniq$3.tag === "List$cons") {
    const __uniq$9 = instReprMerged$repr$__redArg(__uniq$3._1);
    const __uniq$11 = List$foldl$__at__$List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1$spec__7(__uniq$1, { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 }, _2: __uniq$9 }, __uniq$3._2);
    return __uniq$11;
  }
};
export const Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1.tag === "List$nil") {
    return { tag: "Std$Format$nil" };
  } else if (__uniq$1.tag === "List$cons") {
    return __uniq$1._2.tag === "List$nil" ? instReprMerged$repr$__redArg(__uniq$1._1) : List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1(__uniq$2, instReprMerged$repr$__redArg(__uniq$1._1), __uniq$1._2);
  }
};
export const Array$repr$__at__$main$spec__0 = (/* obj */ __uniq$1) => __uniq$1.length === 0 ? Array$repr$__at__$main$spec__0$__closed__8 : Std$Format$fill({ tag: "Std$Format$nest", _1: Array$repr$__at__$main$spec__0$__closed__3, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: Array$repr$__at__$main$spec__0$__closed__5, _2: Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0(lean_array_to_list(__uniq$1), Array$repr$__at__$main$spec__0$__closed__1) }, _2: Array$repr$__at__$main$spec__0$__closed__6 } });
export const main$__closed__13 = Array$repr$__at__$main$spec__0(main$__closed__12);
export const IO$print$__at__$IO$println$__at__$main$spec__1$spec__2 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__1 = (/* tobj */ __uniq$1) => {
  const __uniq$3 = 120;
  const __uniq$4 = 0;
  const __uniq$5 = Std$Format$pretty(__uniq$1, __uniq$3, __uniq$4, __uniq$4);
  const __uniq$6 = 10;
  const __uniq$7 = __uniq$5 + String.fromCodePoint(__uniq$6);
  const __uniq$8 = IO$print$__at__$IO$println$__at__$main$spec__1$spec__2(__uniq$7);
  return __uniq$8;
};
export const Array$repr$__at__$main$spec__2 = (/* obj */ __uniq$1) => __uniq$1.length === 0 ? Array$repr$__at__$main$spec__0$__closed__8 : Std$Format$fill({ tag: "Std$Format$nest", _1: Array$repr$__at__$main$spec__0$__closed__3, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: Array$repr$__at__$main$spec__0$__closed__5, _2: Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__2$spec__4(lean_array_to_list(__uniq$1), Array$repr$__at__$main$spec__0$__closed__1) }, _2: Array$repr$__at__$main$spec__0$__closed__6 } });
export const main$__closed__15 = Array$repr$__at__$main$spec__2([]);
export const Array$repr$__at__$main$spec__4 = (/* obj */ __uniq$1) => __uniq$1.length === 0 ? Array$repr$__at__$main$spec__0$__closed__8 : Std$Format$fill({ tag: "Std$Format$nest", _1: Array$repr$__at__$main$spec__0$__closed__3, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: Array$repr$__at__$main$spec__0$__closed__5, _2: Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__4$spec__7(lean_array_to_list(__uniq$1), Array$repr$__at__$main$spec__0$__closed__1) }, _2: Array$repr$__at__$main$spec__0$__closed__6 } });
export const main = () => {
  const __uniq$2 = main$__lam__0;
  const __uniq$3 = main$__lam__1;
  const __uniq$4 = main$__lam__2;
  const __uniq$5 = "";
  const __uniq$6 = { default: 0 };
  const __uniq$7 = main$__closed__6;
  const __uniq$8 = main$__closed__9;
  const __uniq$9 = diffWithIxE$__redArg(__uniq$5, __uniq$6, __uniq$7, __uniq$8, __uniq$2, __uniq$3, __uniq$4);
  if (__uniq$9.tag === "EST$Out$ok") {
    const __uniq$12 = IO$println$__at__$main$spec__1(main$__closed__13);
    if (__uniq$12.tag === "EST$Out$ok") {
      const __uniq$14 = IO$println$__at__$main$spec__1(main$__closed__15);
      if (__uniq$14.tag === "EST$Out$ok") {
        const __uniq$16 = IO$println$__at__$main$spec__1(main$__closed__17);
        if (__uniq$16.tag === "EST$Out$ok") {
          const __uniq$17 = Array$repr$__at__$main$spec__4(__uniq$9._1);
          const __uniq$18 = IO$println$__at__$main$spec__1(__uniq$17);
          return __uniq$18;
        } else if (__uniq$16.tag === "EST$Out$error") {
          return __uniq$16;
        }
      } else if (__uniq$14.tag === "EST$Out$error") {
        return __uniq$14;
      }
    } else if (__uniq$12.tag === "EST$Out$error") {
      return __uniq$12;
    }
  } else if (__uniq$9.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$9._1 };
  }
};
export const instReprResult = () => instReprResult$repr;

main();
