// Generated by Lean ES6 emitter
import { Float$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Float.js";
import { Std$Format$pretty } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Format/Basic.js";
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { List$reverse$__redArg } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/List/Basic.js";
import { Bool$repr$__redArg, Repr$addAppParen, String$quote } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Repr.js";
import { lean_string_length } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/String/Bootstrap.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test1$__closed__5 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 420;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const test1$__closed__6 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = test1$__closed__5;
  const __uniq$3 = 12;
  const __uniq$4 = { tag: "Args$mk", _1: __uniq$3 };
  __uniq$4._2 = __uniq$2;
  __uniq$4._10 = __uniq$1;
  return __uniq$4;
})();
export const test1$__lam__2 = (/* UInt8 */ __uniq$1) => __uniq$1 ? 0 : 1;
export const test1$__lam__1 = (/* Float */ __uniq$1) => ({ tag: "Prod$mk", _1: "bar", _2: __uniq$1 });
export const test1$__lam__0 = (/* tobj */ __uniq$1) => __uniq$1 + 1;
export const test1$__closed__3 = { tag: "Fns$mk", _1: test1$__lam__0, _2: test1$__lam__1, _3: test1$__lam__2 };
export const zipRecord = (/* obj */ __uniq$1, /* obj */ __uniq$2) => {
  const __uniq$3 = __uniq$1._1;
  const __uniq$4 = __uniq$1._2;
  const __uniq$5 = __uniq$1._3;
  const __uniq$6 = __uniq$2._1;
  const __uniq$7 = __uniq$2._2;
  const __uniq$8 = __uniq$2._10;
  const __uniq$9 = __uniq$3(__uniq$6);
  const __uniq$10 = __uniq$7;
  const __uniq$11 = __uniq$4(__uniq$10);
  const __uniq$12 = __uniq$8;
  const __uniq$13 = __uniq$5(__uniq$12);
  const __uniq$14 = { tag: "R1$mk", _1: __uniq$9, _2: __uniq$11 };
  const __uniq$15 = __uniq$13;
  __uniq$14._3 = __uniq$15;
  return __uniq$14;
};
export const test2 = (/* obj */ __uniq$1) => zipRecord(test1$__closed__3, __uniq$1);
export const Prod$repr$__at__$instReprR1$repr$spec__0$__redArg$__closed__5 = lean_string_length("(");
export const instReprR1$repr$__redArg$__closed__5 = { tag: "Std$Format$text", _1: " := " };
export const List$foldl$__at__$Std$Format$joinSep$__at__$Prod$repr$__at__$instReprR1$repr$spec__0$spec__0$spec__1 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  while (true) {
    if (__uniq$3.tag === "List$nil") {
      return __uniq$2;
    } else if (__uniq$3.tag === "List$cons") {
      const __uniq$4 = __uniq$3._1;
      const __uniq$5 = __uniq$3._2;
      {
        const __uniq$12 = { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 };
        {
          const _tmp_0 = __uniq$1;
          __uniq$1 = _tmp_0;
          __uniq$2 = { tag: "Std$Format$append", _1: __uniq$12, _2: __uniq$4 };
          __uniq$3 = __uniq$5;
          continue;
        }
      }
    }
  }
};
export const Prod$repr$__at__$instReprR1$repr$spec__0$__redArg$__closed__2 = { tag: "Std$Format$text", _1: "," };
export const instReprR1$repr$__redArg$__closed__9 = { tag: "Std$Format$text", _1: "b" };
export const Std$Format$joinSep$__at__$Prod$repr$__at__$instReprR1$repr$spec__0$spec__0 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1.tag === "List$nil") {
    return { tag: "Std$Format$nil" };
  } else if (__uniq$1.tag === "List$cons") {
    return __uniq$1._2.tag === "List$nil" ? __uniq$1._1 : List$foldl$__at__$Std$Format$joinSep$__at__$Prod$repr$__at__$instReprR1$repr$spec__0$spec__0$spec__1(__uniq$2, __uniq$1._1, __uniq$1._2);
  }
};
export const Prod$repr$__at__$instReprR1$repr$spec__0$__redArg = (/* obj */ __uniq$1) => {
  const __uniq$2 = __uniq$1._1;
  const __uniq$3 = __uniq$1._2;
  const __uniq$28 = true;
  {
    const __uniq$6 = String$quote(__uniq$2);
    {
      const __uniq$12 = Float$repr(__uniq$3, 0);
      const __uniq$14 = List$reverse$__redArg({ tag: "List$cons", _1: __uniq$12, _2: { tag: "List$cons", _1: { tag: "Std$Format$text", _1: __uniq$6 }, _2: { tag: "List$nil" } } });
      const __uniq$16 = Std$Format$joinSep$__at__$Prod$repr$__at__$instReprR1$repr$spec__0$spec__0(__uniq$14, { tag: "Std$Format$append", _1: Prod$repr$__at__$instReprR1$repr$spec__0$__redArg$__closed__2, _2: { tag: "Std$Format$line" } });
      const __uniq$24 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: Prod$repr$__at__$instReprR1$repr$spec__0$__redArg$__closed__5, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$text", _1: "(" }, _2: __uniq$16 }, _2: { tag: "Std$Format$text", _1: ")" } } } };
      __uniq$24._2 = 0;
      return __uniq$24;
    }
  }
};
export const instReprR1$repr$__redArg$__closed__11 = { tag: "Std$Format$text", _1: "c" };
export const instReprR1$repr$__redArg$__closed__13 = lean_string_length("{ ");
export const instReprR1$repr$__redArg$__closed__15 = { tag: "Std$Format$text", _1: "{ " };
export const instReprR1$repr$__redArg$__closed__16 = { tag: "Std$Format$text", _1: " }" };
export const instReprR1$repr$__redArg = (/* obj */ __uniq$1) => {
  const __uniq$2 = __uniq$1._1;
  const __uniq$3 = __uniq$1._2;
  const __uniq$4 = __uniq$1._3;
  const __uniq$5 = instReprR1$repr$__redArg$__closed__5;
  const __uniq$6 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$nil" }, _2: { tag: "Std$Format$text", _1: "a" } }, _2: instReprR1$repr$__redArg$__closed__5 };
  const __uniq$7 = 5;
  const __uniq$41 = 0;
  const __uniq$42 = 0;
  const __uniq$43 = __uniq$2 < __uniq$42;
  if (__uniq$43) {
    const __uniq$46 = String(__uniq$2);
    const __uniq$48 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$46 }, __uniq$41);
    {
      const __uniq$11 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$48 } };
      __uniq$11._2 = 0;
      const __uniq$15 = { tag: "Std$Format$line" };
      const __uniq$20 = Prod$repr$__at__$instReprR1$repr$spec__0$__redArg(__uniq$3);
      const __uniq$22 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$20 } };
      __uniq$22._2 = 0;
      const __uniq$29 = Bool$repr$__redArg(__uniq$4);
      const __uniq$31 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$29 } };
      __uniq$31._2 = 0;
      const __uniq$39 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprR1$repr$__redArg$__closed__13, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprR1$repr$__redArg$__closed__15, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$6, _2: __uniq$11 }, _2: Prod$repr$__at__$instReprR1$repr$spec__0$__redArg$__closed__2 }, _2: __uniq$15 }, _2: instReprR1$repr$__redArg$__closed__9 }, _2: __uniq$5 }, _2: __uniq$22 }, _2: Prod$repr$__at__$instReprR1$repr$spec__0$__redArg$__closed__2 }, _2: __uniq$15 }, _2: instReprR1$repr$__redArg$__closed__11 }, _2: __uniq$5 }, _2: __uniq$31 } }, _2: instReprR1$repr$__redArg$__closed__16 } } };
      __uniq$39._2 = 0;
      return __uniq$39;
    }
  } else {
    const __uniq$44 = String(__uniq$2);
    {
      const __uniq$11 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$44 } } };
      __uniq$11._2 = 0;
      const __uniq$15 = { tag: "Std$Format$line" };
      const __uniq$20 = Prod$repr$__at__$instReprR1$repr$spec__0$__redArg(__uniq$3);
      const __uniq$22 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$20 } };
      __uniq$22._2 = 0;
      const __uniq$29 = Bool$repr$__redArg(__uniq$4);
      const __uniq$31 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$29 } };
      __uniq$31._2 = 0;
      const __uniq$39 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprR1$repr$__redArg$__closed__13, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprR1$repr$__redArg$__closed__15, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$6, _2: __uniq$11 }, _2: Prod$repr$__at__$instReprR1$repr$spec__0$__redArg$__closed__2 }, _2: __uniq$15 }, _2: instReprR1$repr$__redArg$__closed__9 }, _2: __uniq$5 }, _2: __uniq$22 }, _2: Prod$repr$__at__$instReprR1$repr$spec__0$__redArg$__closed__2 }, _2: __uniq$15 }, _2: instReprR1$repr$__redArg$__closed__11 }, _2: __uniq$5 }, _2: __uniq$31 } }, _2: instReprR1$repr$__redArg$__closed__16 } } };
      __uniq$39._2 = 0;
      return __uniq$39;
    }
  }
};
export const instReprR1$repr = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => instReprR1$repr$__redArg(__uniq$1);
export const test1$__closed__7 = zipRecord(test1$__closed__3, test1$__closed__6);
export const test1 = () => test1$__closed__7;
export const main$__closed__0 = instReprR1$repr$__redArg(test1());
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => {
  const __uniq$3 = 120;
  const __uniq$4 = 0;
  const __uniq$5 = Std$Format$pretty(__uniq$1, __uniq$3, __uniq$4, __uniq$4);
  const __uniq$6 = 10;
  const __uniq$7 = __uniq$5 + String.fromCodePoint(__uniq$6);
  const __uniq$8 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$7);
  return __uniq$8;
};
export const main$__closed__2 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 100;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const main$__closed__3 = (() => {
  const __uniq$1 = 0;
  const __uniq$2 = main$__closed__2;
  const __uniq$3 = 10;
  const __uniq$4 = { tag: "Args$mk", _1: __uniq$3 };
  __uniq$4._2 = __uniq$2;
  __uniq$4._10 = __uniq$1;
  return __uniq$4;
})();
export const main$__closed__4 = test2(main$__closed__3);
export const main$__closed__5 = instReprR1$repr$__redArg(main$__closed__4);
export const main = () => {
  const __uniq$2 = main$__closed__0;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__5);
    return __uniq$5;
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const Prod$repr$__at__$instReprR1$repr$spec__0 = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => Prod$repr$__at__$instReprR1$repr$spec__0$__redArg(__uniq$1);
export const instReprR1 = () => instReprR1$repr;

main();
