// Generated by Lean ES6 emitter
import { Std$Format$fill, Std$Format$pretty } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Format/Basic.js";
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { Repr$addAppParen } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Repr.js";
import { lean_string_length } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/String/Bootstrap.js";
import { lean_array_fget_borrowed, lean_array_push, lean_array_to_list } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const fn__prime = (/* tagged */ __uniq$1) => 0;
export const extern1$__closed__0 = fn__prime({ tag: "PUnit$unit" });
export const extern2$__closed__1 = lean_array_push([], extern1$__closed__0);
export const extern2$__closed__0 = lean_array_push([], 3);
export const extern1$__closed__1 = lean_array_push(lean_array_push(lean_array_push([], 1), 2), extern1$__closed__0);
export const extern1 = () => extern1$__closed__1;
export const extern2$__closed__2 = lean_array_push(lean_array_push(lean_array_push([], extern1()), extern2$__closed__0), extern2$__closed__1);
export const extern2 = () => extern2$__closed__2;
export const test4$__closed__1 = extern2().length;
export const Array$repr$__at__$main$spec__0$__closed__3 = { tag: "Std$Format$append", _1: { tag: "Std$Format$text", _1: "," }, _2: { tag: "Std$Format$line" } };
export const Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$__lam__0 = (/* tobj */ __uniq$1) => __uniq$1 < 0 ? Repr$addAppParen({ tag: "Std$Format$text", _1: String(__uniq$1) }, 0) : { tag: "Std$Format$text", _1: String(__uniq$1) };
export const List$foldl$__at__$List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1$spec__5 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  while (true) {
    if (__uniq$3.tag === "List$nil") {
      return __uniq$2;
    } else if (__uniq$3.tag === "List$cons") {
      const __uniq$4 = __uniq$3._1;
      const __uniq$5 = __uniq$3._2;
      {
        const __uniq$22 = { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 };
        {
          if (__uniq$4 < 0) {
            const __uniq$16 = String(__uniq$4);
            const __uniq$18 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$16 }, 0);
            const _tmp_0 = __uniq$1;
            __uniq$1 = _tmp_0;
            __uniq$2 = { tag: "Std$Format$append", _1: __uniq$22, _2: __uniq$18 };
            __uniq$3 = __uniq$5;
            continue;
          } else {
            const __uniq$12 = String(__uniq$4);
            const _tmp_0 = __uniq$1;
            __uniq$1 = _tmp_0;
            __uniq$2 = { tag: "Std$Format$append", _1: __uniq$22, _2: { tag: "Std$Format$text", _1: __uniq$12 } };
            __uniq$3 = __uniq$5;
            continue;
          }
        }
      }
    }
  }
};
export const List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  if (__uniq$3.tag === "List$nil") {
    return __uniq$2;
  } else if (__uniq$3.tag === "List$cons") {
    const __uniq$22 = { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 };
    {
      return __uniq$3._1 < 0 ? List$foldl$__at__$List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1$spec__5(__uniq$1, { tag: "Std$Format$append", _1: __uniq$22, _2: Repr$addAppParen({ tag: "Std$Format$text", _1: String(__uniq$3._1) }, 0) }, __uniq$3._2) : List$foldl$__at__$List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1$spec__5(__uniq$1, { tag: "Std$Format$append", _1: __uniq$22, _2: { tag: "Std$Format$text", _1: String(__uniq$3._1) } }, __uniq$3._2);
    }
  }
};
export const Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1.tag === "List$nil") {
    return { tag: "Std$Format$nil" };
  } else if (__uniq$1.tag === "List$cons") {
    return __uniq$1._2.tag === "List$nil" ? Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$__lam__0(__uniq$1._1) : List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1(__uniq$2, Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$__lam__0(__uniq$1._1), __uniq$1._2);
  }
};
export const Array$repr$__at__$main$spec__0$__closed__5 = lean_string_length("#[");
export const Array$repr$__at__$main$spec__0$__closed__7 = { tag: "Std$Format$text", _1: "#[" };
export const Array$repr$__at__$main$spec__0$__closed__8 = { tag: "Std$Format$text", _1: "]" };
export const Array$repr$__at__$main$spec__0$__closed__10 = { tag: "Std$Format$text", _1: "#[]" };
export const Array$repr$__at__$main$spec__0 = (/* obj */ __uniq$1) => __uniq$1.length === 0 ? Array$repr$__at__$main$spec__0$__closed__10 : Std$Format$fill({ tag: "Std$Format$nest", _1: Array$repr$__at__$main$spec__0$__closed__5, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: Array$repr$__at__$main$spec__0$__closed__7, _2: Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0(lean_array_to_list(__uniq$1), Array$repr$__at__$main$spec__0$__closed__3) }, _2: Array$repr$__at__$main$spec__0$__closed__8 } });
export const List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__2$spec__4$spec__6 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  while (true) {
    if (__uniq$3.tag === "List$nil") {
      return __uniq$2;
    } else if (__uniq$3.tag === "List$cons") {
      const __uniq$4 = __uniq$3._1;
      const __uniq$5 = __uniq$3._2;
      {
        const __uniq$13 = { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 };
        {
          const __uniq$9 = Array$repr$__at__$main$spec__0(__uniq$4);
          const _tmp_0 = __uniq$1;
          __uniq$1 = _tmp_0;
          __uniq$2 = { tag: "Std$Format$append", _1: __uniq$13, _2: __uniq$9 };
          __uniq$3 = __uniq$5;
          continue;
        }
      }
    }
  }
};
export const Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__2$spec__4 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1.tag === "List$nil") {
    return { tag: "Std$Format$nil" };
  } else if (__uniq$1.tag === "List$cons") {
    return __uniq$1._2.tag === "List$nil" ? Array$repr$__at__$main$spec__0(__uniq$1._1) : List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__2$spec__4$spec__6(__uniq$2, Array$repr$__at__$main$spec__0(__uniq$1._1), __uniq$1._2);
  }
};
export const test1$__closed__2 = lean_array_push([], 1);
export const test1$__closed__3 = lean_array_push(test1$__closed__2, 2);
export const test2$__closed__2 = lean_array_push(lean_array_push([], 3), 4);
export const test2$__closed__3 = { tag: "Option$some", _1: 3 };
export const Option$instBEq$beq$__at__$test2$spec__0 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1.tag === "Option$none") {
    if (__uniq$2.tag === "Option$none") {
      return 1;
    } else if (__uniq$2.tag === "Option$some") {
      return 0;
    }
  } else if (__uniq$1.tag === "Option$some") {
    if (__uniq$2.tag === "Option$none") {
      return 0;
    } else if (__uniq$2.tag === "Option$some") {
      return __uniq$1._1 === __uniq$2._1;
    }
  }
};
export const test2 = (/* obj */ __uniq$1) => {
  const __uniq$2 = 1;
  const __uniq$3 = { tag: "PUnit$unit" };
  const __uniq$4 = __uniq$1(__uniq$3);
  const __uniq$5 = 3;
  const __uniq$6 = [];
  const __uniq$7 = test1$__closed__3;
  const __uniq$8 = lean_array_push(__uniq$7, __uniq$4);
  const __uniq$9 = test2$__closed__2;
  const __uniq$10 = [];
  const __uniq$11 = lean_array_push(__uniq$10, __uniq$4);
  const __uniq$12 = lean_array_push(__uniq$6, __uniq$8);
  const __uniq$13 = lean_array_push(__uniq$12, __uniq$9);
  const __uniq$14 = lean_array_push(__uniq$13, __uniq$11);
  const __uniq$15 = test2$__closed__3;
  const __uniq$21 = 0;
  const __uniq$22 = __uniq$14.length;
  const __uniq$23 = __uniq$21 < __uniq$22;
  if (__uniq$23) {
    const __uniq$17 = Option$instBEq$beq$__at__$test2$spec__0(__uniq$15, { tag: "Option$some", _1: __uniq$14[__uniq$21].length });
    return __uniq$17 ? __uniq$14 : [...lean_array_push(__uniq$10, __uniq$8), ...__uniq$14];
  } else {
    const __uniq$17 = Option$instBEq$beq$__at__$test2$spec__0(__uniq$15, { tag: "Option$none" });
    return __uniq$17 ? __uniq$14 : [...lean_array_push(__uniq$10, __uniq$8), ...__uniq$14];
  }
};
export const main$__lam__0 = (/* tagged */ __uniq$1) => 0;
export const test1 = (/* obj */ __uniq$1) => {
  const __uniq$2 = { tag: "PUnit$unit" };
  const __uniq$3 = __uniq$1(__uniq$2);
  const __uniq$4 = 3;
  const __uniq$5 = test1$__closed__3;
  const __uniq$6 = lean_array_push(__uniq$5, __uniq$3);
  const __uniq$7 = __uniq$6.length;
  const __uniq$8 = __uniq$7 === __uniq$4;
  return __uniq$8 ? __uniq$6 : [];
};
export const main$__closed__1 = test1(main$__lam__0);
export const main$__closed__2 = Array$repr$__at__$main$spec__0(main$__closed__1);
export const IO$print$__at__$IO$println$__at__$main$spec__1$spec__2 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__1 = (/* tobj */ __uniq$1) => {
  const __uniq$3 = 120;
  const __uniq$4 = 0;
  const __uniq$5 = Std$Format$pretty(__uniq$1, __uniq$3, __uniq$4, __uniq$4);
  const __uniq$6 = 10;
  const __uniq$7 = __uniq$5 + String.fromCodePoint(__uniq$6);
  const __uniq$8 = IO$print$__at__$IO$println$__at__$main$spec__1$spec__2(__uniq$7);
  return __uniq$8;
};
export const main$__closed__3 = test2(main$__lam__0);
export const Array$repr$__at__$main$spec__2 = (/* obj */ __uniq$1) => __uniq$1.length === 0 ? Array$repr$__at__$main$spec__0$__closed__10 : Std$Format$fill({ tag: "Std$Format$nest", _1: Array$repr$__at__$main$spec__0$__closed__5, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: Array$repr$__at__$main$spec__0$__closed__7, _2: Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__2$spec__4(lean_array_to_list(__uniq$1), Array$repr$__at__$main$spec__0$__closed__3) }, _2: Array$repr$__at__$main$spec__0$__closed__8 } });
export const main$__closed__4 = Array$repr$__at__$main$spec__2(main$__closed__3);
export const test3$__closed__0 = extern1().length;
export const test3 = () => test3$__closed__0 === 3 ? extern1() : [];
export const main$__closed__5 = Array$repr$__at__$main$spec__0(test3());
export const test4$__closed__3 = lean_array_fget_borrowed(extern2(), 0);
export const test4 = () => {
  const __uniq$1 = test2$__closed__3;
  const __uniq$2 = extern2();
  const __uniq$7 = 0 < test4$__closed__1;
  if (__uniq$7) {
    const __uniq$4 = Option$instBEq$beq$__at__$test2$spec__0(__uniq$1, { tag: "Option$some", _1: test4$__closed__3.length });
    return __uniq$4 ? __uniq$2 : [];
  } else {
    const __uniq$4 = Option$instBEq$beq$__at__$test2$spec__0(__uniq$1, { tag: "Option$none" });
    return __uniq$4 ? __uniq$2 : [];
  }
};
export const main$__closed__6 = Array$repr$__at__$main$spec__2(test4());
export const main = () => {
  const __uniq$2 = main$__closed__2;
  const __uniq$3 = IO$println$__at__$main$spec__1(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__1(main$__closed__4);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__1(main$__closed__5);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__1(main$__closed__6);
        return __uniq$9;
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};

main();
