// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test2 = () => 42;
export const fn = (/* tobj */ __uniq$2) => 0;
export const extern1$__closed__0 = fn({ tag: "PUnit$unit" });
export const extern1$__closed__1 = (() => {
  const __uniq$1 = 0;
  const __uniq$2 = extern1$__closed__0;
  const __uniq$3 = 1;
  const __uniq$4 = { tag: "Rec$mk", _1: __uniq$2 };
  __uniq$4._2 = __uniq$3;
  __uniq$4._3 = __uniq$3;
  __uniq$4._4 = __uniq$1;
  return __uniq$4;
})();
export const test1 = () => 42;
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const test3 = () => 42;
export const test4 = () => 42;
export const test5 = 42;
export const test6 = () => 42;
export const main = () => {
  const __uniq$2 = test1();
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$4 = test2();
    const __uniq$5 = IO$println$__at__$main$spec__0(__uniq$4);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$6 = test3();
      const __uniq$7 = IO$println$__at__$main$spec__0(__uniq$6);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$8 = test4();
        const __uniq$9 = IO$println$__at__$main$spec__0(__uniq$8);
        if (__uniq$9.tag === "EST$Out$ok") {
          const __uniq$10 = test5;
          const __uniq$11 = IO$println$__at__$main$spec__0(__uniq$10);
          if (__uniq$11.tag === "EST$Out$ok") {
            const __uniq$12 = test6();
            const __uniq$13 = IO$println$__at__$main$spec__0(__uniq$12);
            return __uniq$13;
          } else if (__uniq$11.tag === "EST$Out$error") {
            return __uniq$11;
          }
        } else if (__uniq$9.tag === "EST$Out$error") {
          return __uniq$9;
        }
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const extern1 = () => extern1$__closed__1;

main();
