// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const fn__prime$__closed__3 = { tag: "Rec$mk", _1: 1, _2: 2, _3: 3 };
export const fn__prime = (/* tagged */ __uniq$1) => fn__prime$__closed__3;
export const extern1$__closed__0 = fn__prime({ tag: "PUnit$unit" });
export const extern1 = () => {
  const __uniq$1 = extern1$__closed__0;
  const __uniq$2 = __uniq$1._2;
  const __uniq$3 = __uniq$1._3;
  const __uniq$4 = 42;
  const __uniq$5 = { tag: "Rec$mk", _1: __uniq$4, _2: __uniq$2, _3: __uniq$3 };
  return __uniq$5;
};
export const test2 = () => {
  const __uniq$1 = extern1();
  const __uniq$2 = __uniq$1._1;
  const __uniq$3 = __uniq$1._3;
  const __uniq$4 = 42;
  const __uniq$5 = __uniq$2 === __uniq$4;
  return __uniq$5 ? __uniq$3 : 0;
};
export const main$__lam__0 = (/* tagged */ __uniq$1) => fn__prime$__closed__3;
export const test1 = (/* obj */ __uniq$1) => __uniq$1({ tag: "PUnit$unit" })._3;
export const main$__closed__1 = test1(main$__lam__0);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main = () => {
  const __uniq$2 = main$__closed__1;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$4 = test2();
    const __uniq$5 = IO$println$__at__$main$spec__0(__uniq$4);
    return __uniq$5;
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};

main();
