// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const maybe$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  if (__uniq$3.tag === "Option$none") {
    return __uniq$1;
  } else if (__uniq$3.tag === "Option$some") {
    const __uniq$5 = __uniq$2(__uniq$3._1);
    return __uniq$5;
  }
};
export const test5$__redArg$__lam__0 = (/* tobj */ __uniq$1, /* tagged */ __uniq$2) => __uniq$1 + 1;
export const test2$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => maybe$__redArg(__uniq$1({ tag: "PUnit$unit" }), __uniq$2(1), __uniq$3);
export const test2 = (/* tobj */ __uniq$3, /* tobj */ __uniq$4, /* tobj */ __uniq$5) => test2$__redArg(__uniq$3, __uniq$4, __uniq$5);
export const main$__lam__4 = (/* tobj */ __uniq$1, /* tagged */ __uniq$2) => __uniq$1 + 100;
export const main$__closed__7 = { tag: "Option$some", _1: 42 };
export const main$__lam__2 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1 + 100;
export const main$__lam__1 = (/* tagged */ __uniq$1) => 10;
export const main$__closed__8 = test2$__redArg(main$__lam__1, main$__lam__2, main$__closed__7);
export const maybe_u39_$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  if (__uniq$3.tag === "Option$none") {
    const __uniq$5 = __uniq$1({ tag: "PUnit$unit" });
    return __uniq$5;
  } else if (__uniq$3.tag === "Option$some") {
    const __uniq$7 = __uniq$2(__uniq$3._1);
    return __uniq$7;
  }
};
export const test4$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => maybe_u39_$__redArg(__uniq$1, __uniq$2(1), __uniq$3);
export const main$__closed__2 = { tag: "Option$some", _1: 41 };
export const main$__lam__0 = (/* tagged */ __uniq$1) => 0;
export const test1$__lam__0 = (/* tobj */ __uniq$1) => __uniq$1 + 1;
export const test3 = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => maybe_u39_$__redArg(__uniq$1, test1$__lam__0, __uniq$2);
export const main$__closed__11 = test3(main$__lam__0, main$__closed__2);
export const test5$__redArg = (/* tobj */ __uniq$1, /* obj */ __uniq$2, /* tobj */ __uniq$3) => maybe_u39_$__redArg(test5$__redArg$__lam__0.length - 1 === 0 ? () => test5$__redArg$__lam__0(__uniq$1) : test5$__redArg$__lam__0.length - 1 === 1 ? (x_1) => test5$__redArg$__lam__0(__uniq$1, x_1) : test5$__redArg$__lam__0.length - 1 === 2 ? (x_1, x_2) => test5$__redArg$__lam__0(__uniq$1, x_1, x_2) : (x_1, x_2, x_3) => test5$__redArg$__lam__0(__uniq$1, x_1, x_2, x_3), __uniq$2(1), __uniq$3);
export const main$__closed__17 = test5$__redArg(10, main$__lam__4, { tag: "Option$some", _1: { tag: "PUnit$unit" } });
export const main$__lam__3 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1 + 100;
export const test1 = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => maybe$__redArg(__uniq$1({ tag: "PUnit$unit" }), test1$__lam__0, __uniq$2);
export const main$__closed__3 = test1(main$__lam__0, main$__closed__2);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main$__closed__4 = test1(main$__lam__0, { tag: "Option$none" });
export const main$__closed__10 = test2$__redArg(main$__lam__1, main$__lam__3, { tag: "Option$none" });
export const main$__closed__12 = test3(main$__lam__0, { tag: "Option$none" });
export const main$__closed__13 = test4$__redArg(main$__lam__1, main$__lam__2, main$__closed__7);
export const main$__closed__14 = test4$__redArg(main$__lam__1, main$__lam__3, { tag: "Option$none" });
export const main = () => {
  const __uniq$2 = main$__closed__3;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__4);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__0(main$__closed__8);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__0(main$__closed__10);
        if (__uniq$9.tag === "EST$Out$ok") {
          const __uniq$11 = IO$println$__at__$main$spec__0(main$__closed__11);
          if (__uniq$11.tag === "EST$Out$ok") {
            const __uniq$13 = IO$println$__at__$main$spec__0(main$__closed__12);
            if (__uniq$13.tag === "EST$Out$ok") {
              const __uniq$15 = IO$println$__at__$main$spec__0(main$__closed__13);
              if (__uniq$15.tag === "EST$Out$ok") {
                const __uniq$17 = IO$println$__at__$main$spec__0(main$__closed__14);
                if (__uniq$17.tag === "EST$Out$ok") {
                  const __uniq$19 = IO$println$__at__$main$spec__0(main$__closed__17);
                  return __uniq$19;
                } else if (__uniq$17.tag === "EST$Out$error") {
                  return __uniq$17;
                }
              } else if (__uniq$15.tag === "EST$Out$error") {
                return __uniq$15;
              }
            } else if (__uniq$13.tag === "EST$Out$error") {
              return __uniq$13;
            }
          } else if (__uniq$11.tag === "EST$Out$error") {
            return __uniq$11;
          }
        } else if (__uniq$9.tag === "EST$Out$error") {
          return __uniq$9;
        }
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const maybe = (/* tobj */ __uniq$3, /* tobj */ __uniq$4, /* tobj */ __uniq$5) => maybe$__redArg(__uniq$3, __uniq$4, __uniq$5);
export const maybe_u39_ = (/* tobj */ __uniq$3, /* tobj */ __uniq$4, /* tobj */ __uniq$5) => maybe_u39_$__redArg(__uniq$3, __uniq$4, __uniq$5);
export const test5 = (/* tobj */ __uniq$2, /* obj */ __uniq$3, /* tobj */ __uniq$4) => test5$__redArg(__uniq$2, __uniq$3, __uniq$4);
export const test4 = (/* tobj */ __uniq$3, /* tobj */ __uniq$4, /* tobj */ __uniq$5) => test4$__redArg(__uniq$3, __uniq$4, __uniq$5);

main();
