// Generated by Lean ES6 emitter
import { Std$Format$pretty } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Format/Basic.js";
import { Int$toNat, lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Option$repr$__at__$Lean$Meta$instReprConfig__1$repr$spec__0 } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Meta/Defs.js";
import { lean_array_fget_borrowed, lean_array_push } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const testArrayIndex$__redArg = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => {
  const __uniq$3 = 0;
  const __uniq$4 = __uniq$2 < __uniq$3;
  if (__uniq$4) {
    return { tag: "Option$none" };
  } else {
    const __uniq$5 = Int$toNat(__uniq$2);
    return __uniq$5 < __uniq$1.length ? { tag: "Option$some", _1: lean_array_fget_borrowed(__uniq$1, __uniq$5) } : { tag: "Option$none" };
  }
};
export const main$__closed__0 = lean_array_push(lean_array_push(lean_array_push([], 1), 2), 3);
export const main$__closed__7 = testArrayIndex$__redArg(main$__closed__0, 1);
export const main$__closed__8 = Option$repr$__at__$Lean$Meta$instReprConfig__1$repr$spec__0(main$__closed__7, 0);
export const main$__closed__10 = testArrayIndex$__redArg(main$__closed__0, 2);
export const main$__closed__11 = Option$repr$__at__$Lean$Meta$instReprConfig__1$repr$spec__0(main$__closed__10, 0);
export const main$__closed__3 = testArrayIndex$__redArg(main$__closed__0, -1);
export const main$__closed__4 = Option$repr$__at__$Lean$Meta$instReprConfig__1$repr$spec__0(main$__closed__3, 0);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => {
  const __uniq$3 = 120;
  const __uniq$4 = 0;
  const __uniq$5 = Std$Format$pretty(__uniq$1, __uniq$3, __uniq$4, __uniq$4);
  const __uniq$6 = 10;
  const __uniq$7 = __uniq$5 + String.fromCodePoint(__uniq$6);
  const __uniq$8 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$7);
  return __uniq$8;
};
export const main$__closed__5 = testArrayIndex$__redArg(main$__closed__0, 0);
export const main$__closed__6 = Option$repr$__at__$Lean$Meta$instReprConfig__1$repr$spec__0(main$__closed__5, 0);
export const main$__closed__13 = testArrayIndex$__redArg(main$__closed__0, 3);
export const main$__closed__14 = Option$repr$__at__$Lean$Meta$instReprConfig__1$repr$spec__0(main$__closed__13, 0);
export const main = () => {
  const __uniq$2 = main$__closed__4;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__6);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__0(main$__closed__8);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__0(main$__closed__11);
        if (__uniq$9.tag === "EST$Out$ok") {
          const __uniq$11 = IO$println$__at__$main$spec__0(main$__closed__14);
          return __uniq$11;
        } else if (__uniq$9.tag === "EST$Out$error") {
          return __uniq$9;
        }
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const testArrayIndex = (/* obj */ __uniq$2, /* tobj */ __uniq$3) => testArrayIndex$__redArg(__uniq$2, __uniq$3);

main();
