// Generated by Lean ES6 emitter
import { lean_float_add, lean_float_div, lean_float_mul, lean_float_sub, lean_float_to_string } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Float.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const localTest$__closed__2 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 110;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const localTest$__closed__0 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 990;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const test2$__closed__0 = lean_float_sub(localTest$__closed__0, localTest$__closed__2);
export const fn$__closed__0 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 0;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const fn = (/* tobj */ __uniq$2) => fn$__closed__0;
export const localTest$__closed__1 = fn({ tag: "PUnit$unit" });
export const localTest$__closed__3 = (() => {
  const __uniq$1 = localTest$__closed__2;
  const __uniq$2 = localTest$__closed__1;
  const __uniq$3 = localTest$__closed__0;
  const __uniq$4 = { tag: "Rec$mk" };
  __uniq$4._1 = __uniq$3;
  __uniq$4._9 = __uniq$2;
  __uniq$4._17 = __uniq$1;
  return __uniq$4;
})();
export const extern = () => localTest$__closed__3;
export const externTest = (/* obj */ __uniq$1) => __uniq$1(extern());
export const test2 = () => test2$__closed__0;
export const test1$__closed__0 = lean_float_add(localTest$__closed__0, localTest$__closed__2);
export const test1 = () => test1$__closed__0;
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* Float */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(lean_float_to_string(__uniq$1) + String.fromCodePoint(10));
export const test3$__closed__0 = lean_float_mul(localTest$__closed__0, localTest$__closed__2);
export const test3 = () => test3$__closed__0;
export const test4$__closed__0 = lean_float_div(localTest$__closed__0, localTest$__closed__2);
export const test4 = () => test4$__closed__0;
export const test5 = () => {
  const __uniq$1 = extern();
  const __uniq$2 = __uniq$1._1;
  const __uniq$3 = __uniq$1._17;
  const __uniq$4 = lean_float_add(__uniq$2, __uniq$3);
  return __uniq$4;
};
export const test6 = () => {
  const __uniq$1 = extern();
  const __uniq$2 = __uniq$1._1;
  const __uniq$3 = __uniq$1._17;
  const __uniq$4 = lean_float_sub(__uniq$2, __uniq$3);
  return __uniq$4;
};
export const test7 = () => {
  const __uniq$1 = extern();
  const __uniq$2 = __uniq$1._1;
  const __uniq$3 = __uniq$1._17;
  const __uniq$4 = lean_float_mul(__uniq$2, __uniq$3);
  return __uniq$4;
};
export const test8 = () => {
  const __uniq$1 = extern();
  const __uniq$2 = __uniq$1._1;
  const __uniq$3 = __uniq$1._17;
  const __uniq$4 = lean_float_div(__uniq$2, __uniq$3);
  return __uniq$4;
};
export const main = () => {
  const __uniq$2 = test1();
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$4 = test2();
    const __uniq$5 = IO$println$__at__$main$spec__0(__uniq$4);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$6 = test3();
      const __uniq$7 = IO$println$__at__$main$spec__0(__uniq$6);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$8 = test4();
        const __uniq$9 = IO$println$__at__$main$spec__0(__uniq$8);
        if (__uniq$9.tag === "EST$Out$ok") {
          const __uniq$10 = test5();
          const __uniq$11 = IO$println$__at__$main$spec__0(__uniq$10);
          if (__uniq$11.tag === "EST$Out$ok") {
            const __uniq$12 = test6();
            const __uniq$13 = IO$println$__at__$main$spec__0(__uniq$12);
            if (__uniq$13.tag === "EST$Out$ok") {
              const __uniq$14 = test7();
              const __uniq$15 = IO$println$__at__$main$spec__0(__uniq$14);
              if (__uniq$15.tag === "EST$Out$ok") {
                const __uniq$16 = test8();
                const __uniq$17 = IO$println$__at__$main$spec__0(__uniq$16);
                return __uniq$17;
              } else if (__uniq$15.tag === "EST$Out$error") {
                return __uniq$15;
              }
            } else if (__uniq$13.tag === "EST$Out$error") {
              return __uniq$13;
            }
          } else if (__uniq$11.tag === "EST$Out$error") {
            return __uniq$11;
          }
        } else if (__uniq$9.tag === "EST$Out$error") {
          return __uniq$9;
        }
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const localTest = (/* obj */ __uniq$1) => __uniq$1(localTest$__closed__3);

main();
