// Generated by Lean ES6 emitter
import { Std$Format$pretty } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Format/Basic.js";
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Repr$addAppParen } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const Test$Foo$elim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const instReprTest$repr$__closed__3 = { tag: "Std$Format$text", _1: "Test.Bar" };
export const Test$ctorElim = (/* tobj */ __uniq$2, /* UInt8 */ __uniq$3, /* tobj */ __uniq$5) => __uniq$5;
export const Test$Qux$elim = (/* UInt8 */ __uniq$2, /* tobj */ __uniq$4) => __uniq$4;
export const Test$ctorIdx = (/* UInt8 */ __uniq$1) => {
  if (__uniq$1 === 0) {
    return 0;
  } else if (__uniq$1 === 1) {
    return 1;
  } else if (__uniq$1 === 2) {
    return 2;
  } else if (__uniq$1 === 3) {
    return 3;
  }
};
export const Test$toCtorIdx = (/* UInt8 */ __uniq$1) => Test$ctorIdx(__uniq$1);
export const Test$ctorElim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const Test$Qux$elim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const Test$Baz$elim = (/* UInt8 */ __uniq$2, /* tobj */ __uniq$4) => __uniq$4;
export const instReprTest$repr$__closed__1 = { tag: "Std$Format$text", _1: "Test.Foo" };
export const instReprTest$repr$__closed__5 = { tag: "Std$Format$text", _1: "Test.Baz" };
export const instReprTest$repr$__closed__7 = { tag: "Std$Format$text", _1: "Test.Qux" };
export const instReprTest$repr = (/* UInt8 */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1 === 0) {
    if (1024 <= __uniq$2) {
      const __uniq$7 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 1, _2: instReprTest$repr$__closed__1 } };
      __uniq$7._2 = 0;
      const __uniq$8 = Repr$addAppParen(__uniq$7, __uniq$2);
      return __uniq$8;
    } else {
      const __uniq$7 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 2, _2: instReprTest$repr$__closed__1 } };
      __uniq$7._2 = 0;
      const __uniq$8 = Repr$addAppParen(__uniq$7, __uniq$2);
      return __uniq$8;
    }
  } else if (__uniq$1 === 1) {
    if (1024 <= __uniq$2) {
      const __uniq$14 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 1, _2: instReprTest$repr$__closed__3 } };
      __uniq$14._2 = 0;
      const __uniq$15 = Repr$addAppParen(__uniq$14, __uniq$2);
      return __uniq$15;
    } else {
      const __uniq$14 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 2, _2: instReprTest$repr$__closed__3 } };
      __uniq$14._2 = 0;
      const __uniq$15 = Repr$addAppParen(__uniq$14, __uniq$2);
      return __uniq$15;
    }
  } else if (__uniq$1 === 2) {
    if (1024 <= __uniq$2) {
      const __uniq$21 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 1, _2: instReprTest$repr$__closed__5 } };
      __uniq$21._2 = 0;
      const __uniq$22 = Repr$addAppParen(__uniq$21, __uniq$2);
      return __uniq$22;
    } else {
      const __uniq$21 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 2, _2: instReprTest$repr$__closed__5 } };
      __uniq$21._2 = 0;
      const __uniq$22 = Repr$addAppParen(__uniq$21, __uniq$2);
      return __uniq$22;
    }
  } else if (__uniq$1 === 3) {
    if (1024 <= __uniq$2) {
      const __uniq$28 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 1, _2: instReprTest$repr$__closed__7 } };
      __uniq$28._2 = 0;
      const __uniq$29 = Repr$addAppParen(__uniq$28, __uniq$2);
      return __uniq$29;
    } else {
      const __uniq$28 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: 2, _2: instReprTest$repr$__closed__7 } };
      __uniq$28._2 = 0;
      const __uniq$29 = Repr$addAppParen(__uniq$28, __uniq$2);
      return __uniq$29;
    }
  }
};
export const main$__closed__0 = instReprTest$repr(0, 0);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => {
  const __uniq$3 = 120;
  const __uniq$4 = 0;
  const __uniq$5 = Std$Format$pretty(__uniq$1, __uniq$3, __uniq$4, __uniq$4);
  const __uniq$6 = 10;
  const __uniq$7 = __uniq$5 + String.fromCodePoint(__uniq$6);
  const __uniq$8 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$7);
  return __uniq$8;
};
export const main$__closed__1 = instReprTest$repr(1, 0);
export const main$__closed__2 = instReprTest$repr(2, 0);
export const main$__closed__3 = instReprTest$repr(3, 0);
export const main = () => {
  const __uniq$2 = main$__closed__0;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__1);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__0(main$__closed__2);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__0(main$__closed__3);
        return __uniq$9;
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const instReprTest = () => instReprTest$repr;
export const Test$Foo$elim = (/* UInt8 */ __uniq$2, /* tobj */ __uniq$4) => __uniq$4;
export const Test$Baz$elim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const Test$Bar$elim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const Test$Bar$elim = (/* UInt8 */ __uniq$2, /* tobj */ __uniq$4) => __uniq$4;

main();
