// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_array_push, lean_array_to_list } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const fromString = (/* obj */ __uniq$1) => __uniq$1 === "foo" ? { tag: "Option$some", _1: 0 } : __uniq$1 === "bar" ? { tag: "Option$some", _1: 1 } : __uniq$1 === "baz" ? { tag: "Option$some", _1: 2 } : __uniq$1 === "qux" ? { tag: "Option$some", _1: 3 } : { tag: "Option$none" };
export const test2 = (/* tobj */ __uniq$1) => 42 < __uniq$1 ? "Hello, World!" : "";
export const List$foldl$__at__$List$toString$__at__$IO$println$__at__$main$spec__2$spec__3$spec__4 = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => {
  while (true) {
    if (__uniq$2.tag === "List$nil") {
      return __uniq$1;
    } else if (__uniq$2.tag === "List$cons") {
      const __uniq$3 = __uniq$2._1;
      const __uniq$4 = __uniq$2._2;
      const __uniq$6 = __uniq$1 + ", ";
      __uniq$1 = __uniq$6 + __uniq$3;
      __uniq$2 = __uniq$4;
      continue;
    }
  }
};
export const List$toString$__at__$IO$println$__at__$main$spec__2$spec__3 = (/* tobj */ __uniq$1) => {
  if (__uniq$1.tag === "List$nil") {
    return "[]";
  } else if (__uniq$1.tag === "List$cons") {
    return __uniq$1._2.tag === "List$nil" ? "[" + __uniq$1._1 + "]" : List$foldl$__at__$List$toString$__at__$IO$println$__at__$main$spec__2$spec__3$spec__4("[" + __uniq$1._1, __uniq$1._2) + String.fromCodePoint(93);
  }
};
export const test1 = (/* obj */ __uniq$1) => __uniq$1._1;
export const TestEnum$Bar$elim = (/* UInt8 */ __uniq$2, /* tobj */ __uniq$4) => __uniq$4;
export const TestEnum$Baz$elim = (/* UInt8 */ __uniq$2, /* tobj */ __uniq$4) => __uniq$4;
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__3 = (/* UInt8 */ __uniq$1) => {
  if (__uniq$1) {
    const __uniq$5 = "true" + String.fromCodePoint(10);
    const __uniq$6 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$5);
    return __uniq$6;
  } else {
    const __uniq$5 = "false" + String.fromCodePoint(10);
    const __uniq$6 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$5);
    return __uniq$6;
  }
};
export const TestEnum$ctorIdx = (/* UInt8 */ __uniq$1) => {
  if (__uniq$1 === 0) {
    return 0;
  } else if (__uniq$1 === 1) {
    return 1;
  } else if (__uniq$1 === 2) {
    return 2;
  } else if (__uniq$1 === 3) {
    return 3;
  }
};
export const TestEnum$Foo$elim = (/* UInt8 */ __uniq$2, /* tobj */ __uniq$4) => __uniq$4;
export const TestEnum$Baz$elim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const TestEnum$Foo$elim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const IO$println$__at__$main$spec__1 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main$__closed__0 = test2(2);
export const test3 = (/* tobj */ __uniq$1) => {
  const __uniq$12 = 42;
  const __uniq$13 = __uniq$12 < __uniq$1;
  if (__uniq$13) {
    const __uniq$9 = lean_array_push([], "Hello" + ", World");
    const __uniq$10 = lean_array_push(__uniq$9, "Hello" + ", Universe");
    return __uniq$10;
  } else {
    const __uniq$9 = lean_array_push([], "Default" + ", World");
    const __uniq$10 = lean_array_push(__uniq$9, "Default" + ", Universe");
    return __uniq$10;
  }
};
export const main$__closed__1 = test3(3);
export const IO$println$__at__$main$spec__2 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0("#" + List$toString$__at__$IO$println$__at__$main$spec__2$spec__3(lean_array_to_list(__uniq$1)) + String.fromCodePoint(10));
export const main$__closed__2 = (x_1, x_2) => x_1 + x_2;
export const test4 = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => {
  const __uniq$10 = 42;
  const __uniq$11 = __uniq$10 < __uniq$2;
  if (__uniq$11) {
    const __uniq$8 = __uniq$1("Hello" + ", World", "Hello" + ", Universe");
    return __uniq$8;
  } else {
    const __uniq$8 = __uniq$1("Default" + ", World", "Default" + ", Universe");
    return __uniq$8;
  }
};
export const main$__closed__3 = test4(main$__closed__2, 4);
export const test6 = (/* obj */ __uniq$1) => {
  const __uniq$2 = fromString(__uniq$1);
  if (__uniq$2.tag === "Option$none") {
    return 0;
  } else if (__uniq$2.tag === "Option$some") {
    if (__uniq$2._1 === 0) {
      return 1;
    } else if (__uniq$2._1 === 1) {
      return 2;
    } else if (__uniq$2._1 === 2) {
      return 3;
    } else if (__uniq$2._1 === 3) {
      return 4;
    }
  }
};
export const main$__closed__5 = test6("6");
export const main = () => {
  const __uniq$2 = "b";
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__1(1);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__0(main$__closed__0);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__2(main$__closed__1);
        if (__uniq$9.tag === "EST$Out$ok") {
          const __uniq$11 = IO$println$__at__$main$spec__0(main$__closed__3);
          if (__uniq$11.tag === "EST$Out$ok") {
            const __uniq$13 = IO$println$__at__$main$spec__3(0);
            if (__uniq$13.tag === "EST$Out$ok") {
              const __uniq$15 = IO$println$__at__$main$spec__1(main$__closed__5);
              return __uniq$15;
            } else if (__uniq$13.tag === "EST$Out$error") {
              return __uniq$13;
            }
          } else if (__uniq$11.tag === "EST$Out$error") {
            return __uniq$11;
          }
        } else if (__uniq$9.tag === "EST$Out$error") {
          return __uniq$9;
        }
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const TestEnum$Qux$elim = (/* UInt8 */ __uniq$2, /* tobj */ __uniq$4) => __uniq$4;
export const TestEnum$Qux$elim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const known1 = () => "b";
export const TestEnum$Bar$elim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const TestEnum$ctorElim = (/* tobj */ __uniq$2, /* UInt8 */ __uniq$3, /* tobj */ __uniq$5) => __uniq$5;
export const test5 = (/* tobj */ __uniq$1) => 0;
export const TestEnum$toCtorIdx = (/* UInt8 */ __uniq$1) => TestEnum$ctorIdx(__uniq$1);
export const TestEnum$ctorElim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;

main();
