// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const Test$Foo$elim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const fromString = (/* obj */ __uniq$1) => __uniq$1 === "foo" ? { tag: "Option$some", _1: 0 } : __uniq$1 === "bar" ? { tag: "Option$some", _1: 1 } : __uniq$1 === "baz" ? { tag: "Option$some", _1: 2 } : __uniq$1 === "qux" ? { tag: "Option$some", _1: 3 } : { tag: "Option$none" };
export const Test$ctorElim = (/* tobj */ __uniq$2, /* UInt8 */ __uniq$3, /* tobj */ __uniq$5) => __uniq$5;
export const Test$Qux$elim = (/* UInt8 */ __uniq$2, /* tobj */ __uniq$4) => __uniq$4;
export const Test$ctorIdx = (/* UInt8 */ __uniq$1) => {
  if (__uniq$1 === 0) {
    return 0;
  } else if (__uniq$1 === 1) {
    return 1;
  } else if (__uniq$1 === 2) {
    return 2;
  } else if (__uniq$1 === 3) {
    return 3;
  }
};
export const Test$toCtorIdx = (/* UInt8 */ __uniq$1) => Test$ctorIdx(__uniq$1);
export const Test$ctorElim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const Test$Qux$elim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const Test$Baz$elim = (/* UInt8 */ __uniq$2, /* tobj */ __uniq$4) => __uniq$4;
export const test = (/* obj */ __uniq$1) => {
  const __uniq$2 = fromString(__uniq$1);
  if (__uniq$2.tag === "Option$none") {
    return 0;
  } else if (__uniq$2.tag === "Option$some") {
    if (__uniq$2._1 === 0) {
      return 1;
    } else if (__uniq$2._1 === 1) {
      return 2;
    } else if (__uniq$2._1 === 2) {
      return 3;
    } else if (__uniq$2._1 === 3) {
      return 4;
    }
  }
};
export const main$__closed__0 = test("foo");
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main$__closed__1 = test("bar");
export const main$__closed__2 = test("baz");
export const main$__closed__3 = test("qux");
export const main$__closed__5 = test("wat");
export const main = () => {
  const __uniq$2 = main$__closed__0;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__1);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__0(main$__closed__2);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__0(main$__closed__3);
        if (__uniq$9.tag === "EST$Out$ok") {
          const __uniq$11 = IO$println$__at__$main$spec__0(main$__closed__5);
          return __uniq$11;
        } else if (__uniq$9.tag === "EST$Out$error") {
          return __uniq$9;
        }
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const Test$Baz$elim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const Test$Foo$elim = (/* UInt8 */ __uniq$2, /* tobj */ __uniq$4) => __uniq$4;
export const Test$Bar$elim$__redArg = (/* tobj */ __uniq$1) => __uniq$1;
export const Test$Bar$elim = (/* UInt8 */ __uniq$2, /* tobj */ __uniq$4) => __uniq$4;

main();
