// Generated by Lean ES6 emitter
import { lean_uint32_to_nat } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test1 = (/* UInt32 */ __uniq$1) => lean_uint32_to_nat(__uniq$1);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main = () => IO$println$__at__$main$spec__0(97);

main();
