// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { lean_int_ediv } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/DivMod/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test2 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1 - __uniq$2;
export const test1 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1 + __uniq$2;
export const main$__closed__11 = lean_int_ediv(10, 20);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const IO$println$__at__$main$spec__1 = (/* UInt8 */ __uniq$1) => {
  if (__uniq$1) {
    const __uniq$5 = "true" + String.fromCodePoint(10);
    const __uniq$6 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$5);
    return __uniq$6;
  } else {
    const __uniq$5 = "false" + String.fromCodePoint(10);
    const __uniq$6 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$5);
    return __uniq$6;
  }
};
export const test4 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1 === __uniq$2 ? 0 : 1;
export const main$__closed__5 = test4(10, 20);
export const main = () => {
  const __uniq$2 = 10 + 20;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(10 - 20);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__1(10 === 20);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__1(main$__closed__5);
        if (__uniq$9.tag === "EST$Out$ok") {
          const __uniq$11 = IO$println$__at__$main$spec__1(10 < 20);
          if (__uniq$11.tag === "EST$Out$ok") {
            const __uniq$13 = IO$println$__at__$main$spec__1(20 < 10);
            if (__uniq$13.tag === "EST$Out$ok") {
              const __uniq$15 = IO$println$__at__$main$spec__1(10 <= 20);
              if (__uniq$15.tag === "EST$Out$ok") {
                const __uniq$17 = IO$println$__at__$main$spec__1(20 <= 10);
                if (__uniq$17.tag === "EST$Out$ok") {
                  const __uniq$19 = IO$println$__at__$main$spec__0(10 * 20);
                  if (__uniq$19.tag === "EST$Out$ok") {
                    const __uniq$21 = IO$println$__at__$main$spec__0(main$__closed__11);
                    if (__uniq$21.tag === "EST$Out$ok") {
                      const __uniq$23 = IO$println$__at__$main$spec__0(-10);
                      return __uniq$23;
                    } else if (__uniq$21.tag === "EST$Out$error") {
                      return __uniq$21;
                    }
                  } else if (__uniq$19.tag === "EST$Out$error") {
                    return __uniq$19;
                  }
                } else if (__uniq$17.tag === "EST$Out$error") {
                  return __uniq$17;
                }
              } else if (__uniq$15.tag === "EST$Out$error") {
                return __uniq$15;
              }
            } else if (__uniq$13.tag === "EST$Out$error") {
              return __uniq$13;
            }
          } else if (__uniq$11.tag === "EST$Out$error") {
            return __uniq$11;
          }
        } else if (__uniq$9.tag === "EST$Out$error") {
          return __uniq$9;
        }
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const test3 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1 === __uniq$2;
export const test7 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1 <= __uniq$2;
export const test8 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$2 <= __uniq$1;
export const test9 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1 * __uniq$2;
export const test6 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$2 < __uniq$1;
export const test11 = (/* tobj */ __uniq$1) => -__uniq$1;
export const test5 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$1 < __uniq$2;
export const test10 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => lean_int_ediv(__uniq$1, __uniq$2);

main();
