// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_array_get_borrowed, lean_array_push } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test2$__redArg = (/* tobj */ __uniq$1, /* obj */ __uniq$2) => lean_array_get_borrowed(__uniq$1, __uniq$2, 2);
export const test2 = (/* tobj */ __uniq$2, /* obj */ __uniq$3) => test2$__redArg(__uniq$2, __uniq$3);
export const test1$__redArg = (/* obj */ __uniq$1) => __uniq$1.length;
export const test1 = (/* obj */ __uniq$2) => test1$__redArg(__uniq$2);
export const test4$__redArg = (/* tobj */ __uniq$1, /* obj */ __uniq$2) => lean_array_get_borrowed(__uniq$1, __uniq$2, 2);
export const main$__closed__0 = lean_array_push(lean_array_push(lean_array_push(lean_array_push([], 1), 2), 3), 4);
export const main$__closed__1 = test1$__redArg(main$__closed__0);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main$__closed__2 = lean_array_get_borrowed(0, main$__closed__0, 2);
export const IO$println$__at__$main$spec__1 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const test3$__redArg = (/* obj */ __uniq$1) => __uniq$1.length;
export const main$__closed__3 = test3$__redArg(main$__closed__0);
export const main = () => {
  const __uniq$2 = main$__closed__1;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__1(main$__closed__2);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__0(main$__closed__3);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$8 = IO$println$__at__$main$spec__1(main$__closed__2);
        return __uniq$8;
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const test3 = (/* obj */ __uniq$2) => test3$__redArg(__uniq$2);
export const test4 = (/* tobj */ __uniq$2, /* obj */ __uniq$3) => test4$__redArg(__uniq$2, __uniq$3);

main();
