// Generated by Lean ES6 emitter
import { String$decLE, lean_string_dec_lt } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/String/Basic.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test2 = (/* obj */ __uniq$1, /* obj */ __uniq$2) => __uniq$1 === __uniq$2 ? 0 : 1;
export const test1 = (/* obj */ __uniq$1, /* obj */ __uniq$2) => __uniq$1 === __uniq$2;
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* UInt8 */ __uniq$1) => {
  if (__uniq$1) {
    const __uniq$5 = "true" + String.fromCodePoint(10);
    const __uniq$6 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$5);
    return __uniq$6;
  } else {
    const __uniq$5 = "false" + String.fromCodePoint(10);
    const __uniq$6 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$5);
    return __uniq$6;
  }
};
export const main$__closed__1 = (() => {
  const __uniq$1 = "a";
  const __uniq$2 = test2(__uniq$1, __uniq$1);
  return __uniq$2;
})();
export const main$__closed__5 = (() => {
  const __uniq$1 = "a";
  const __uniq$2 = __uniq$1 <= __uniq$1;
  return __uniq$2;
})();
export const IO$println$__at__$main$spec__1 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main = () => {
  const __uniq$2 = 1;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__1);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__0("a" < "b");
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__0("b" < "a");
        if (__uniq$9.tag === "EST$Out$ok") {
          const __uniq$11 = IO$println$__at__$main$spec__0(main$__closed__5);
          if (__uniq$11.tag === "EST$Out$ok") {
            const __uniq$12 = IO$println$__at__$main$spec__0(main$__closed__5);
            if (__uniq$12.tag === "EST$Out$ok") {
              const __uniq$14 = IO$println$__at__$main$spec__1("ab");
              return __uniq$14;
            } else if (__uniq$12.tag === "EST$Out$error") {
              return __uniq$12;
            }
          } else if (__uniq$11.tag === "EST$Out$error") {
            return __uniq$11;
          }
        } else if (__uniq$9.tag === "EST$Out$error") {
          return __uniq$9;
        }
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const test3 = (/* obj */ __uniq$1, /* obj */ __uniq$2) => __uniq$1 < __uniq$2;
export const test7 = (/* obj */ __uniq$1, /* obj */ __uniq$2) => __uniq$1 + __uniq$2;
export const test6 = (/* obj */ __uniq$1, /* obj */ __uniq$2) => __uniq$2 <= __uniq$1;
export const test5 = (/* obj */ __uniq$1, /* obj */ __uniq$2) => __uniq$1 <= __uniq$2;
export const test4 = (/* obj */ __uniq$1, /* obj */ __uniq$2) => __uniq$2 < __uniq$1;

main();
