// Generated by Lean ES6 emitter
import { Std$Format$fill, Std$Format$pretty } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Format/Basic.js";
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Bool$repr$__redArg } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Repr.js";
import { lean_string_length } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/String/Bootstrap.js";
import { lean_array_push, lean_array_to_list, lean_uint32_dec_eq, lean_uint32_dec_le, lean_uint32_dec_lt } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test2$__lam__0 = (/* UInt32 */ __uniq$1, /* UInt32 */ __uniq$2) => __uniq$1 === __uniq$2 ? 0 : 1;
export const test4$__lam__0 = (/* UInt32 */ __uniq$1, /* UInt32 */ __uniq$2) => __uniq$2 < __uniq$1;
export const charValues$__boxed__const__2 = () => 97;
export const charValues$__boxed__const__1 = () => 98;
export const charValues = (/* obj */ __uniq$1) => lean_array_push(lean_array_push(lean_array_push([], __uniq$1(charValues$__boxed__const__2(), charValues$__boxed__const__2())), __uniq$1(charValues$__boxed__const__2(), charValues$__boxed__const__1())), __uniq$1(charValues$__boxed__const__1(), charValues$__boxed__const__2()));
export const test4$__closed__1 = charValues(test4$__lam__0);
export const test2$__closed__1 = charValues(test2$__lam__0);
export const test2 = () => test2$__closed__1;
export const test6$__lam__0 = (/* UInt32 */ __uniq$1, /* UInt32 */ __uniq$2) => __uniq$2 <= __uniq$1;
export const Array$repr$__at__$main$spec__0$__closed__5 = lean_string_length("#[");
export const test1$__closed__1 = charValues(lean_uint32_dec_eq);
export const test1 = () => test1$__closed__1;
export const List$foldl$__at__$List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1$spec__4 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  while (true) {
    if (__uniq$3.tag === "List$nil") {
      return __uniq$2;
    } else if (__uniq$3.tag === "List$cons") {
      const __uniq$4 = __uniq$3._1;
      const __uniq$5 = __uniq$3._2;
      {
        const __uniq$14 = { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 };
        {
          const __uniq$10 = Bool$repr$__redArg(__uniq$4);
          const _tmp_0 = __uniq$1;
          __uniq$1 = _tmp_0;
          __uniq$2 = { tag: "Std$Format$append", _1: __uniq$14, _2: __uniq$10 };
          __uniq$3 = __uniq$5;
          continue;
        }
      }
    }
  }
};
export const List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  if (__uniq$3.tag === "List$nil") {
    return __uniq$2;
  } else if (__uniq$3.tag === "List$cons") {
    const __uniq$10 = Bool$repr$__redArg(__uniq$3._1);
    const __uniq$12 = List$foldl$__at__$List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1$spec__4(__uniq$1, { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 }, _2: __uniq$10 }, __uniq$3._2);
    return __uniq$12;
  }
};
export const Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1.tag === "List$nil") {
    return { tag: "Std$Format$nil" };
  } else if (__uniq$1.tag === "List$cons") {
    return __uniq$1._2.tag === "List$nil" ? Bool$repr$__redArg(__uniq$1._1) : List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1(__uniq$2, Bool$repr$__redArg(__uniq$1._1), __uniq$1._2);
  }
};
export const Array$repr$__at__$main$spec__0 = (/* obj */ __uniq$1) => __uniq$1.length === 0 ? { tag: "Std$Format$text", _1: "#[]" } : Std$Format$fill({ tag: "Std$Format$nest", _1: Array$repr$__at__$main$spec__0$__closed__5, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$text", _1: "#[" }, _2: Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0(lean_array_to_list(__uniq$1), { tag: "Std$Format$append", _1: { tag: "Std$Format$text", _1: "," }, _2: { tag: "Std$Format$line" } }) }, _2: { tag: "Std$Format$text", _1: "]" } } });
export const main$__closed__0 = Array$repr$__at__$main$spec__0(test1());
export const IO$print$__at__$IO$println$__at__$main$spec__1$spec__2 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__1 = (/* tobj */ __uniq$1) => {
  const __uniq$3 = 120;
  const __uniq$4 = 0;
  const __uniq$5 = Std$Format$pretty(__uniq$1, __uniq$3, __uniq$4, __uniq$4);
  const __uniq$6 = 10;
  const __uniq$7 = __uniq$5 + String.fromCodePoint(__uniq$6);
  const __uniq$8 = IO$print$__at__$IO$println$__at__$main$spec__1$spec__2(__uniq$7);
  return __uniq$8;
};
export const main$__closed__1 = Array$repr$__at__$main$spec__0(test2());
export const test3$__closed__1 = charValues(lean_uint32_dec_lt);
export const test3 = () => test3$__closed__1;
export const main$__closed__2 = Array$repr$__at__$main$spec__0(test3());
export const test4 = () => test4$__closed__1;
export const main$__closed__3 = Array$repr$__at__$main$spec__0(test4());
export const test5$__closed__1 = charValues(lean_uint32_dec_le);
export const test5 = () => test5$__closed__1;
export const main$__closed__4 = Array$repr$__at__$main$spec__0(test5());
export const test6$__closed__1 = charValues(test6$__lam__0);
export const test6 = () => test6$__closed__1;
export const main$__closed__5 = Array$repr$__at__$main$spec__0(test6());
export const main = () => {
  const __uniq$2 = main$__closed__0;
  const __uniq$3 = IO$println$__at__$main$spec__1(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__1(main$__closed__1);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__1(main$__closed__2);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__1(main$__closed__3);
        if (__uniq$9.tag === "EST$Out$ok") {
          const __uniq$11 = IO$println$__at__$main$spec__1(main$__closed__4);
          if (__uniq$11.tag === "EST$Out$ok") {
            const __uniq$13 = IO$println$__at__$main$spec__1(main$__closed__5);
            return __uniq$13;
          } else if (__uniq$11.tag === "EST$Out$error") {
            return __uniq$11;
          }
        } else if (__uniq$9.tag === "EST$Out$error") {
          return __uniq$9;
        }
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};

main();
