// Generated by Lean ES6 emitter
import { lean_float_add, lean_float_beq, lean_float_decLe, lean_float_decLt, lean_float_div, lean_float_mul, lean_float_negate, lean_float_sub, lean_float_to_string } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Float.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const main$__closed__11 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 30;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const main$__closed__14 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 100;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const main$__closed__15 = lean_float_div(main$__closed__14, main$__closed__11);
export const main$__closed__16 = lean_float_to_string(main$__closed__15);
export const main$__closed__1 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 20;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const main$__closed__0 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 10;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const test13 = (/* Float */ __uniq$1, /* Float */ __uniq$2, /* Float */ __uniq$3) => lean_float_div(__uniq$1, lean_float_div(__uniq$2, __uniq$3));
export const main$__closed__22 = test13(main$__closed__0, main$__closed__1, main$__closed__11);
export const main$__closed__23 = lean_float_to_string(main$__closed__22);
export const test2 = (/* Float */ __uniq$1, /* Float */ __uniq$2) => lean_float_sub(__uniq$1, __uniq$2);
export const test1 = (/* Float */ __uniq$1, /* Float */ __uniq$2) => lean_float_add(__uniq$1, __uniq$2);
export const main$__closed__17 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = 1;
  const __uniq$3 = 50;
  const __uniq$4 = __uniq$3 * (10 ** (__uniq$2 ? -__uniq$1 : __uniq$1));
  return __uniq$4;
})();
export const test12 = (/* Float */ __uniq$1, /* Float */ __uniq$2, /* Float */ __uniq$3) => lean_float_sub(__uniq$1, lean_float_sub(__uniq$2, __uniq$3));
export const main$__closed__20 = test12(main$__closed__0, main$__closed__1, main$__closed__11);
export const main$__closed__2 = lean_float_add(main$__closed__0, main$__closed__1);
export const main$__closed__3 = lean_float_to_string(main$__closed__2);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main$__closed__4 = lean_float_sub(main$__closed__0, main$__closed__1);
export const main$__closed__5 = lean_float_to_string(main$__closed__4);
export const main$__closed__6 = (() => {
  const __uniq$1 = main$__closed__0;
  const __uniq$2 = __uniq$1 === __uniq$1;
  return __uniq$2;
})();
export const IO$println$__at__$main$spec__1 = (/* UInt8 */ __uniq$1) => {
  if (__uniq$1) {
    const __uniq$5 = "true" + String.fromCodePoint(10);
    const __uniq$6 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$5);
    return __uniq$6;
  } else {
    const __uniq$5 = "false" + String.fromCodePoint(10);
    const __uniq$6 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$5);
    return __uniq$6;
  }
};
export const test4 = (/* Float */ __uniq$1, /* Float */ __uniq$2) => __uniq$1 === __uniq$2 ? 0 : 1;
export const main$__closed__7 = (() => {
  const __uniq$1 = main$__closed__0;
  const __uniq$2 = test4(__uniq$1, __uniq$1);
  return __uniq$2;
})();
export const main$__closed__10 = (() => {
  const __uniq$1 = main$__closed__0;
  const __uniq$2 = __uniq$1 <= __uniq$1;
  return __uniq$2;
})();
export const main$__closed__12 = lean_float_mul(main$__closed__1, main$__closed__11);
export const main$__closed__13 = lean_float_to_string(main$__closed__12);
export const main$__closed__18 = lean_float_negate(main$__closed__17);
export const main$__closed__19 = lean_float_to_string(main$__closed__18);
export const main$__closed__21 = lean_float_to_string(main$__closed__20);
export const main = () => {
  const __uniq$2 = main$__closed__3;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__5);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__1(main$__closed__6);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$9 = IO$println$__at__$main$spec__1(main$__closed__7);
        if (__uniq$9.tag === "EST$Out$ok") {
          const __uniq$11 = IO$println$__at__$main$spec__1(main$__closed__0 < main$__closed__1);
          if (__uniq$11.tag === "EST$Out$ok") {
            const __uniq$13 = IO$println$__at__$main$spec__1(main$__closed__1 < main$__closed__0);
            if (__uniq$13.tag === "EST$Out$ok") {
              const __uniq$15 = IO$println$__at__$main$spec__1(main$__closed__10);
              if (__uniq$15.tag === "EST$Out$ok") {
                const __uniq$16 = IO$println$__at__$main$spec__1(main$__closed__10);
                if (__uniq$16.tag === "EST$Out$ok") {
                  const __uniq$18 = IO$println$__at__$main$spec__0(main$__closed__13);
                  if (__uniq$18.tag === "EST$Out$ok") {
                    const __uniq$20 = IO$println$__at__$main$spec__0(main$__closed__16);
                    if (__uniq$20.tag === "EST$Out$ok") {
                      const __uniq$22 = IO$println$__at__$main$spec__0(main$__closed__19);
                      if (__uniq$22.tag === "EST$Out$ok") {
                        const __uniq$24 = IO$println$__at__$main$spec__0(main$__closed__21);
                        if (__uniq$24.tag === "EST$Out$ok") {
                          const __uniq$26 = IO$println$__at__$main$spec__0(main$__closed__23);
                          return __uniq$26;
                        } else if (__uniq$24.tag === "EST$Out$error") {
                          return __uniq$24;
                        }
                      } else if (__uniq$22.tag === "EST$Out$error") {
                        return __uniq$22;
                      }
                    } else if (__uniq$20.tag === "EST$Out$error") {
                      return __uniq$20;
                    }
                  } else if (__uniq$18.tag === "EST$Out$error") {
                    return __uniq$18;
                  }
                } else if (__uniq$16.tag === "EST$Out$error") {
                  return __uniq$16;
                }
              } else if (__uniq$15.tag === "EST$Out$error") {
                return __uniq$15;
              }
            } else if (__uniq$13.tag === "EST$Out$error") {
              return __uniq$13;
            }
          } else if (__uniq$11.tag === "EST$Out$error") {
            return __uniq$11;
          }
        } else if (__uniq$9.tag === "EST$Out$error") {
          return __uniq$9;
        }
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const test3 = (/* Float */ __uniq$1, /* Float */ __uniq$2) => __uniq$1 === __uniq$2;
export const test7 = (/* Float */ __uniq$1, /* Float */ __uniq$2) => __uniq$1 <= __uniq$2;
export const test8 = (/* Float */ __uniq$1, /* Float */ __uniq$2) => __uniq$2 <= __uniq$1;
export const test9 = (/* Float */ __uniq$1, /* Float */ __uniq$2) => lean_float_mul(__uniq$1, __uniq$2);
export const test6 = (/* Float */ __uniq$1, /* Float */ __uniq$2) => __uniq$2 < __uniq$1;
export const test11 = (/* Float */ __uniq$1) => lean_float_negate(__uniq$1);
export const test5 = (/* Float */ __uniq$1, /* Float */ __uniq$2) => __uniq$1 < __uniq$2;
export const test10 = (/* Float */ __uniq$1, /* Float */ __uniq$2) => lean_float_div(__uniq$1, __uniq$2);

main();
