// Generated by Lean ES6 emitter
export const bit2 = (a, b) => UInt32_lor(a, b);
export const bit3 = (a, b) => UInt32_shiftLeft(a, b);
export const main__closed_8 = UInt32_xor(15, 12);
export const main__closed_10 = UInt32_complement(3);
export const main__closed_11 = UInt32_toNat(main__closed_10);
export const bit7 = (a) => UInt32_complement(a);
export const bit5 = (a, b) => UInt32_xor(a, b);
export const main__closed_9 = UInt32_toNat(main__closed_8);
export const main__closed_0 = UInt32_land(1023, 8);
export const main__closed_1 = UInt32_toNat(main__closed_0);
export const IO_print__at__IO_println__at__main_spec_0_spec_0 = (s /* world */) => IO_getStdout()._5(s);
export const IO_println__at__main_spec_0 = (s /* world */) => IO_print__at__IO_println__at__main_spec_0_spec_0(String(s) + String.fromCodePoint(10));
export const main__closed_2 = UInt32_lor(16, 15);
export const main__closed_3 = UInt32_toNat(main__closed_2);
export const main__closed_4 = UInt32_shiftLeft(1023, 2);
export const main__closed_5 = UInt32_toNat(main__closed_4);
export const main__closed_6 = UInt32_shiftRight(1023, 2);
export const main__closed_7 = UInt32_toNat(main__closed_6);
export const main = (/* world */) => {
  const _x_3 = IO_println__at__main_spec_0(main__closed_1);
  if (_x_3.tag === "EST_Out_ok") {
    const _x_5 = IO_println__at__main_spec_0(main__closed_3);
    if (_x_5.tag === "EST_Out_ok") {
      const _x_7 = IO_println__at__main_spec_0(main__closed_5);
      if (_x_7.tag === "EST_Out_ok") {
        const _x_9 = IO_println__at__main_spec_0(main__closed_7);
        if (_x_9.tag === "EST_Out_ok") {
          const _x_11 = IO_println__at__main_spec_0(main__closed_9);
          if (_x_11.tag === "EST_Out_ok") {
            const _x_13 = IO_println__at__main_spec_0(main__closed_11);
            return _x_13;
          } else if (_x_11.tag === "EST_Out_error") {
            return _x_11;
          }
        } else if (_x_9.tag === "EST_Out_error") {
          return _x_9;
        }
      } else if (_x_7.tag === "EST_Out_error") {
        return _x_7;
      }
    } else if (_x_5.tag === "EST_Out_error") {
      return _x_5;
    }
  } else if (_x_3.tag === "EST_Out_error") {
    return _x_3;
  }
};
export const bit1 = (a, b) => UInt32_land(a, b);
export const bit4 = (a, b) => UInt32_shiftRight(a, b);
