// Generated by Lean ES6 emitter
import { lean_uint32_complement, lean_uint32_land, lean_uint32_lor, lean_uint32_shift_left, lean_uint32_shift_right, lean_uint32_xor } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/UInt/Basic.js";
import { lean_uint32_add } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/UInt/BasicAux.js";
import { lean_uint32_to_nat } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test2$__closed__0 = lean_uint32_lor(16, 15);
export const test4$__closed__0 = lean_uint32_complement(1023);
export const test4$__closed__1 = lean_uint32_add(test4$__closed__0, 1);
export const test2 = () => test2$__closed__0;
export const test5$__closed__0 = lean_uint32_xor(15, 12);
export const test1$__closed__0 = lean_uint32_land(1023, 8);
export const test1 = () => test1$__closed__0;
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* UInt32 */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(lean_uint32_to_nat(__uniq$1)) + String.fromCodePoint(10));
export const test3$__closed__0 = lean_uint32_shift_left(1023, 2);
export const test3 = () => test3$__closed__0;
export const test4$__closed__2 = lean_uint32_shift_right(test4$__closed__1, 2);
export const test4 = () => test4$__closed__2;
export const test5 = () => test5$__closed__0;
export const test6 = () => test4$__closed__2;
export const test7$__closed__0 = lean_uint32_complement(3);
export const test7$__closed__1 = lean_uint32_add(test7$__closed__0, 1);
export const test7$__closed__2 = lean_uint32_complement(test7$__closed__1);
export const test7 = () => test7$__closed__2;
export const main = () => {
  const __uniq$2 = test1();
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$4 = test2();
    const __uniq$5 = IO$println$__at__$main$spec__0(__uniq$4);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$6 = test3();
      const __uniq$7 = IO$println$__at__$main$spec__0(__uniq$6);
      if (__uniq$7.tag === "EST$Out$ok") {
        const __uniq$8 = test4();
        const __uniq$9 = IO$println$__at__$main$spec__0(__uniq$8);
        if (__uniq$9.tag === "EST$Out$ok") {
          const __uniq$10 = test5();
          const __uniq$11 = IO$println$__at__$main$spec__0(__uniq$10);
          if (__uniq$11.tag === "EST$Out$ok") {
            const __uniq$12 = test6();
            const __uniq$13 = IO$println$__at__$main$spec__0(__uniq$12);
            if (__uniq$13.tag === "EST$Out$ok") {
              const __uniq$14 = test7();
              const __uniq$15 = IO$println$__at__$main$spec__0(__uniq$14);
              return __uniq$15;
            } else if (__uniq$13.tag === "EST$Out$error") {
              return __uniq$13;
            }
          } else if (__uniq$11.tag === "EST$Out$error") {
            return __uniq$11;
          }
        } else if (__uniq$9.tag === "EST$Out$error") {
          return __uniq$9;
        }
      } else if (__uniq$7.tag === "EST$Out$error") {
        return __uniq$7;
      }
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};

main();
