// Generated by Lean ES6 emitter
import { Std$Format$pretty } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Format/Basic.js";
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { Repr$addAppParen } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Repr.js";
import { lean_string_length } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/String/Bootstrap.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test1 = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$2 === 42 ? __uniq$2 + 1 : __uniq$1({ tag: "PUnit$unit" })._3;
export const instReprRec$repr$__redArg$__closed__5 = { tag: "Std$Format$text", _1: " := " };
export const instReprRec$repr$__redArg$__closed__9 = lean_string_length("{ ");
export const instReprRec$repr$__redArg$__closed__11 = { tag: "Std$Format$text", _1: "{ " };
export const instReprRec$repr$__redArg$__closed__12 = { tag: "Std$Format$text", _1: " }" };
export const instReprRec$repr$__redArg$__closed__14 = { tag: "Std$Format$text", _1: "c" };
export const instReprRec$repr$__redArg$__closed__17 = { tag: "Std$Format$text", _1: "," };
export const instReprRec$repr$__redArg$__closed__19 = { tag: "Std$Format$text", _1: "b" };
export const instReprRec$repr$__redArg = (/* obj */ __uniq$1) => {
  const __uniq$2 = __uniq$1._1;
  const __uniq$3 = __uniq$1._2;
  const __uniq$4 = __uniq$1._3;
  const __uniq$5 = instReprRec$repr$__redArg$__closed__5;
  const __uniq$6 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$nil" }, _2: { tag: "Std$Format$text", _1: "a" } }, _2: instReprRec$repr$__redArg$__closed__5 };
  const __uniq$7 = 5;
  const __uniq$65 = 0;
  const __uniq$66 = 0;
  const __uniq$67 = __uniq$2 < __uniq$66;
  if (__uniq$67) {
    const __uniq$70 = String(__uniq$2);
    const __uniq$72 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$70 }, __uniq$65);
    {
      const __uniq$47 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$72 } };
      __uniq$47._2 = 0;
      const __uniq$51 = { tag: "Std$Format$line" };
      const __uniq$55 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$6, _2: __uniq$47 }, _2: instReprRec$repr$__redArg$__closed__17 }, _2: __uniq$51 }, _2: instReprRec$repr$__redArg$__closed__19 }, _2: __uniq$5 };
      if (__uniq$3 < 0) {
        const __uniq$61 = String(__uniq$3);
        const __uniq$63 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$61 }, 0);
        {
          const __uniq$28 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$63 } };
          __uniq$28._2 = 0;
          const __uniq$34 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$55, _2: __uniq$28 }, _2: instReprRec$repr$__redArg$__closed__17 }, _2: __uniq$51 }, _2: instReprRec$repr$__redArg$__closed__14 }, _2: __uniq$5 };
          if (__uniq$4 < 0) {
            const __uniq$40 = String(__uniq$4);
            const __uniq$42 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$40 }, 0);
            {
              const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$42 } };
              __uniq$12._2 = 0;
              const __uniq$20 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprRec$repr$__redArg$__closed__9, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprRec$repr$__redArg$__closed__11, _2: { tag: "Std$Format$append", _1: __uniq$34, _2: __uniq$12 } }, _2: instReprRec$repr$__redArg$__closed__12 } } };
              __uniq$20._2 = 0;
              return __uniq$20;
            }
          } else {
            const __uniq$38 = String(__uniq$4);
            {
              const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$38 } } };
              __uniq$12._2 = 0;
              const __uniq$20 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprRec$repr$__redArg$__closed__9, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprRec$repr$__redArg$__closed__11, _2: { tag: "Std$Format$append", _1: __uniq$34, _2: __uniq$12 } }, _2: instReprRec$repr$__redArg$__closed__12 } } };
              __uniq$20._2 = 0;
              return __uniq$20;
            }
          }
        }
      } else {
        const __uniq$59 = String(__uniq$3);
        {
          const __uniq$28 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$59 } } };
          __uniq$28._2 = 0;
          const __uniq$34 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$55, _2: __uniq$28 }, _2: instReprRec$repr$__redArg$__closed__17 }, _2: __uniq$51 }, _2: instReprRec$repr$__redArg$__closed__14 }, _2: __uniq$5 };
          if (__uniq$4 < 0) {
            const __uniq$40 = String(__uniq$4);
            const __uniq$42 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$40 }, 0);
            {
              const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$42 } };
              __uniq$12._2 = 0;
              const __uniq$20 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprRec$repr$__redArg$__closed__9, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprRec$repr$__redArg$__closed__11, _2: { tag: "Std$Format$append", _1: __uniq$34, _2: __uniq$12 } }, _2: instReprRec$repr$__redArg$__closed__12 } } };
              __uniq$20._2 = 0;
              return __uniq$20;
            }
          } else {
            const __uniq$38 = String(__uniq$4);
            {
              const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$38 } } };
              __uniq$12._2 = 0;
              const __uniq$20 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprRec$repr$__redArg$__closed__9, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprRec$repr$__redArg$__closed__11, _2: { tag: "Std$Format$append", _1: __uniq$34, _2: __uniq$12 } }, _2: instReprRec$repr$__redArg$__closed__12 } } };
              __uniq$20._2 = 0;
              return __uniq$20;
            }
          }
        }
      }
    }
  } else {
    const __uniq$68 = String(__uniq$2);
    {
      const __uniq$47 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$68 } } };
      __uniq$47._2 = 0;
      const __uniq$51 = { tag: "Std$Format$line" };
      const __uniq$55 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$6, _2: __uniq$47 }, _2: instReprRec$repr$__redArg$__closed__17 }, _2: __uniq$51 }, _2: instReprRec$repr$__redArg$__closed__19 }, _2: __uniq$5 };
      if (__uniq$3 < 0) {
        const __uniq$61 = String(__uniq$3);
        const __uniq$63 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$61 }, 0);
        {
          const __uniq$28 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$63 } };
          __uniq$28._2 = 0;
          const __uniq$34 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$55, _2: __uniq$28 }, _2: instReprRec$repr$__redArg$__closed__17 }, _2: __uniq$51 }, _2: instReprRec$repr$__redArg$__closed__14 }, _2: __uniq$5 };
          if (__uniq$4 < 0) {
            const __uniq$40 = String(__uniq$4);
            const __uniq$42 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$40 }, 0);
            {
              const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$42 } };
              __uniq$12._2 = 0;
              const __uniq$20 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprRec$repr$__redArg$__closed__9, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprRec$repr$__redArg$__closed__11, _2: { tag: "Std$Format$append", _1: __uniq$34, _2: __uniq$12 } }, _2: instReprRec$repr$__redArg$__closed__12 } } };
              __uniq$20._2 = 0;
              return __uniq$20;
            }
          } else {
            const __uniq$38 = String(__uniq$4);
            {
              const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$38 } } };
              __uniq$12._2 = 0;
              const __uniq$20 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprRec$repr$__redArg$__closed__9, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprRec$repr$__redArg$__closed__11, _2: { tag: "Std$Format$append", _1: __uniq$34, _2: __uniq$12 } }, _2: instReprRec$repr$__redArg$__closed__12 } } };
              __uniq$20._2 = 0;
              return __uniq$20;
            }
          }
        }
      } else {
        const __uniq$59 = String(__uniq$3);
        {
          const __uniq$28 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$59 } } };
          __uniq$28._2 = 0;
          const __uniq$34 = { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$55, _2: __uniq$28 }, _2: instReprRec$repr$__redArg$__closed__17 }, _2: __uniq$51 }, _2: instReprRec$repr$__redArg$__closed__14 }, _2: __uniq$5 };
          if (__uniq$4 < 0) {
            const __uniq$40 = String(__uniq$4);
            const __uniq$42 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$40 }, 0);
            {
              const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: __uniq$42 } };
              __uniq$12._2 = 0;
              const __uniq$20 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprRec$repr$__redArg$__closed__9, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprRec$repr$__redArg$__closed__11, _2: { tag: "Std$Format$append", _1: __uniq$34, _2: __uniq$12 } }, _2: instReprRec$repr$__redArg$__closed__12 } } };
              __uniq$20._2 = 0;
              return __uniq$20;
            }
          } else {
            const __uniq$38 = String(__uniq$4);
            {
              const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: __uniq$7, _2: { tag: "Std$Format$text", _1: __uniq$38 } } };
              __uniq$12._2 = 0;
              const __uniq$20 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: instReprRec$repr$__redArg$__closed__9, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: instReprRec$repr$__redArg$__closed__11, _2: { tag: "Std$Format$append", _1: __uniq$34, _2: __uniq$12 } }, _2: instReprRec$repr$__redArg$__closed__12 } } };
              __uniq$20._2 = 0;
              return __uniq$20;
            }
          }
        }
      }
    }
  }
};
export const instReprRec$repr = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => instReprRec$repr$__redArg(__uniq$1);
export const main$__lam__0$__closed__0 = (() => {
  const __uniq$1 = 0;
  const __uniq$2 = { tag: "Rec$mk", _1: __uniq$1, _2: __uniq$1, _3: __uniq$1 };
  return __uniq$2;
})();
export const main$__lam__0 = (/* tagged */ __uniq$1) => main$__lam__0$__closed__0;
export const main$__closed__1 = test1(main$__lam__0, 42);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main$__lam__1 = (/* tobj */ __uniq$1) => __uniq$1 + 1;
export const test7 = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => {
  const __uniq$3 = __uniq$1(__uniq$2);
  const __uniq$4 = 1;
  const __uniq$5 = __uniq$3 + __uniq$4;
  const __uniq$6 = 2;
  const __uniq$7 = __uniq$3 - __uniq$6;
  const __uniq$8 = { tag: "Rec$mk", _1: __uniq$5, _2: __uniq$7, _3: __uniq$3 };
  return __uniq$8;
};
export const main$__closed__4 = test7(main$__lam__1, 10);
export const main$__closed__5 = instReprRec$repr$__redArg(main$__closed__4);
export const IO$println$__at__$main$spec__1 = (/* tobj */ __uniq$1) => {
  const __uniq$3 = 120;
  const __uniq$4 = 0;
  const __uniq$5 = Std$Format$pretty(__uniq$1, __uniq$3, __uniq$4, __uniq$4);
  const __uniq$6 = 10;
  const __uniq$7 = __uniq$5 + String.fromCodePoint(__uniq$6);
  const __uniq$8 = IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$7);
  return __uniq$8;
};
export const main = () => {
  const __uniq$2 = main$__closed__1;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__1(main$__closed__5);
    return __uniq$5;
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const instReprRec = () => instReprRec$repr;

main();
