// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const instInhabitedT2$default = () => 0;
export const instInhabitedT2 = () => instInhabitedT2$default();
export const test3 = (/* tobj */ __uniq$1) => __uniq$1 < 100 ? __uniq$1 : test1({ tag: "PUnit$unit" })._1;
export const test1 = (/* tagged */ __uniq$1) => ({ tag: "T1$mk", _1: test3(42), _2: test2({ tag: "PUnit$unit" }) });
export const test2 = (/* tagged */ __uniq$1) => test1({ tag: "PUnit$unit" })._1;
export const main$__closed__0 = test3(42);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main$__closed__2 = test3(99);
export const main = () => {
  const __uniq$2 = main$__closed__0;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__2);
    return __uniq$5;
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const instInhabitedT1$default$__closed__1 = (() => {
  const __uniq$1 = 0;
  const __uniq$2 = { tag: "T1$mk", _1: __uniq$1, _2: __uniq$1 };
  return __uniq$2;
})();
export const instInhabitedT1$default = () => instInhabitedT1$default$__closed__1;
export const instInhabitedT1 = () => instInhabitedT1$default();

main();
