// Generated by Lean ES6 emitter
import { lean_array_size, lean_array_uget_borrowed } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Array/Basic.js";
import { lean_usize_add, lean_usize_dec_lt } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/UInt/BasicAux.js";
import { lean_array_push } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
import { lean_st_mk_ref, lean_st_ref_get, lean_st_ref_set } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/ST.js";
export const main$__lam__0 = (/* tobj */ __uniq$1) => __uniq$1 + 1;
export const __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$test1$spec__0$__redArg = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* obj */ __uniq$3, /* USize */ __uniq$4, /* USize */ __uniq$5, /* tagged */ __uniq$6) => {
  while (true) {
    const __uniq$8 = __uniq$5 < __uniq$4;
    if (__uniq$8) {
      const __uniq$10 = lean_st_ref_get(__uniq$1);
      const __uniq$11 = lean_array_uget_borrowed(__uniq$3, __uniq$5);
      const __uniq$12 = __uniq$2(__uniq$11);
      const __uniq$13 = lean_array_push(__uniq$10, __uniq$12);
      const __uniq$14 = lean_st_ref_set(__uniq$1, __uniq$13);
      const __uniq$17 = lean_usize_add(__uniq$5, 1);
      const _tmp_0 = __uniq$1;
      const _tmp_1 = __uniq$2;
      const _tmp_2 = __uniq$3;
      const _tmp_3 = __uniq$4;
      __uniq$1 = _tmp_0;
      __uniq$2 = _tmp_1;
      __uniq$3 = _tmp_2;
      __uniq$4 = _tmp_3;
      __uniq$5 = __uniq$17;
      __uniq$6 = { tag: "PUnit$unit" };
      continue;
    } else {
      return { tag: "EST$Out$ok", _1: __uniq$6 };
    }
  }
};
export const test1$__redArg = (/* tobj */ __uniq$1, /* obj */ __uniq$2) => {
  const __uniq$4 = [];
  const __uniq$5 = lean_st_mk_ref(__uniq$4);
  const __uniq$6 = { tag: "PUnit$unit" };
  const __uniq$7 = lean_array_size(__uniq$2);
  const __uniq$8 = 0;
  const __uniq$9 = __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$test1$spec__0$__redArg(__uniq$5, __uniq$1, __uniq$2, __uniq$7, __uniq$8, __uniq$6);
  if (__uniq$9.tag === "EST$Out$ok") {
    return { tag: "EST$Out$ok", _1: __uniq$6 };
  } else if (__uniq$9.tag === "EST$Out$error") {
    return __uniq$9;
  }
};
export const test1 = (/* tobj */ __uniq$3, /* obj */ __uniq$4) => test1$__redArg(__uniq$3, __uniq$4);
export const main$__closed__1 = lean_array_push(lean_array_push(lean_array_push([], 1), 2), 3);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main = () => {
  const __uniq$2 = main$__lam__0;
  const __uniq$3 = main$__closed__1;
  const __uniq$4 = test1$__redArg(__uniq$2, __uniq$3);
  if (__uniq$4.tag === "EST$Out$ok") {
    const __uniq$6 = IO$println$__at__$main$spec__0("ok");
    return __uniq$6;
  } else if (__uniq$4.tag === "EST$Out$error") {
    return __uniq$4;
  }
};
export const __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$test1$spec__0 = (/* tobj */ __uniq$3, /* tobj */ __uniq$4, /* obj */ __uniq$5, /* USize */ __uniq$6, /* USize */ __uniq$7, /* tagged */ __uniq$8) => __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$test1$spec__0$__redArg(__uniq$3, __uniq$4, __uniq$5, __uniq$6, __uniq$7, __uniq$8);

main();
