// Generated by Lean ES6 emitter
import { lean_array_size, lean_array_uget_borrowed } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Array/Basic.js";
import { Std$Format$fill, Std$Format$pretty } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Format/Basic.js";
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { lean_string_length } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/String/Bootstrap.js";
import { lean_usize_add, lean_usize_dec_lt } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/UInt/BasicAux.js";
import { lean_array_push, lean_array_to_list } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const main$__lam__0 = (/* tobj */ __uniq$1) => __uniq$1 + 1;
export const __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$test2$spec__0$__redArg = (/* obj */ __uniq$1, /* USize */ __uniq$2, /* USize */ __uniq$3, /* obj */ __uniq$4) => {
  while (true) {
    const __uniq$5 = __uniq$3 < __uniq$2;
    if (__uniq$5) {
      const __uniq$6 = lean_array_uget_borrowed(__uniq$1, __uniq$3);
      const __uniq$7 = lean_array_push(__uniq$4, __uniq$6);
      const __uniq$9 = lean_usize_add(__uniq$3, 1);
      const _tmp_0 = __uniq$1;
      const _tmp_1 = __uniq$2;
      __uniq$1 = _tmp_0;
      __uniq$2 = _tmp_1;
      __uniq$3 = __uniq$9;
      __uniq$4 = __uniq$7;
      continue;
    } else {
      return __uniq$4;
    }
  }
};
export const __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$test2$spec__1$__redArg = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* USize */ __uniq$3, /* USize */ __uniq$4, /* obj */ __uniq$5) => {
  while (true) {
    const __uniq$6 = __uniq$4 < __uniq$3;
    if (__uniq$6) {
      const __uniq$7 = lean_array_uget_borrowed(__uniq$2, __uniq$4);
      const __uniq$8 = __uniq$1(__uniq$7);
      const __uniq$9 = lean_array_size(__uniq$8);
      const __uniq$11 = __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$test2$spec__0$__redArg(__uniq$8, __uniq$9, 0, __uniq$5);
      const __uniq$13 = lean_usize_add(__uniq$4, 1);
      const _tmp_0 = __uniq$1;
      const _tmp_1 = __uniq$2;
      const _tmp_2 = __uniq$3;
      __uniq$1 = _tmp_0;
      __uniq$2 = _tmp_1;
      __uniq$3 = _tmp_2;
      __uniq$4 = __uniq$13;
      __uniq$5 = __uniq$11;
      continue;
    } else {
      return __uniq$5;
    }
  }
};
export const test2$__redArg = (/* obj */ __uniq$1, /* obj */ __uniq$2) => __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$test2$spec__1$__redArg(__uniq$1, __uniq$2, lean_array_size(__uniq$2), 0, []);
export const test2 = (/* obj */ __uniq$3, /* obj */ __uniq$4) => test2$__redArg(__uniq$3, __uniq$4);
export const __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$test1$spec__0$__redArg = (/* tobj */ __uniq$1, /* obj */ __uniq$2, /* USize */ __uniq$3, /* USize */ __uniq$4, /* obj */ __uniq$5) => {
  while (true) {
    const __uniq$6 = __uniq$4 < __uniq$3;
    if (__uniq$6) {
      const __uniq$7 = lean_array_uget_borrowed(__uniq$2, __uniq$4);
      const __uniq$8 = __uniq$1(__uniq$7);
      const __uniq$9 = lean_array_push(__uniq$5, __uniq$8);
      const __uniq$11 = lean_usize_add(__uniq$4, 1);
      const _tmp_0 = __uniq$1;
      const _tmp_1 = __uniq$2;
      const _tmp_2 = __uniq$3;
      __uniq$1 = _tmp_0;
      __uniq$2 = _tmp_1;
      __uniq$3 = _tmp_2;
      __uniq$4 = __uniq$11;
      __uniq$5 = __uniq$9;
      continue;
    } else {
      return __uniq$5;
    }
  }
};
export const test1$__redArg = (/* tobj */ __uniq$1, /* obj */ __uniq$2) => __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$test1$spec__0$__redArg(__uniq$1, __uniq$2, lean_array_size(__uniq$2), 0, []);
export const test1 = (/* tobj */ __uniq$3, /* obj */ __uniq$4) => test1$__redArg(__uniq$3, __uniq$4);
export const __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$test2$spec__1 = (/* obj */ __uniq$3, /* obj */ __uniq$4, /* USize */ __uniq$5, /* USize */ __uniq$6, /* obj */ __uniq$7) => __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$test2$spec__1$__redArg(__uniq$3, __uniq$4, __uniq$5, __uniq$6, __uniq$7);
export const Array$repr$__at__$main$spec__0$__closed__5 = lean_string_length("#[");
export const main$__closed__1 = lean_array_push(lean_array_push(lean_array_push([], 1), 2), 3);
export const main$__closed__2 = test1$__redArg(main$__lam__0, main$__closed__1);
export const Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$__lam__0 = (/* tobj */ __uniq$1) => ({ tag: "Std$Format$text", _1: String(__uniq$1) });
export const List$foldl$__at__$List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1$spec__4 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  while (true) {
    if (__uniq$3.tag === "List$nil") {
      return __uniq$2;
    } else if (__uniq$3.tag === "List$cons") {
      const __uniq$4 = __uniq$3._1;
      const __uniq$5 = __uniq$3._2;
      {
        const __uniq$14 = { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 };
        {
          const __uniq$9 = String(__uniq$4);
          const _tmp_0 = __uniq$1;
          __uniq$1 = _tmp_0;
          __uniq$2 = { tag: "Std$Format$append", _1: __uniq$14, _2: { tag: "Std$Format$text", _1: __uniq$9 } };
          __uniq$3 = __uniq$5;
          continue;
        }
      }
    }
  }
};
export const List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  if (__uniq$3.tag === "List$nil") {
    return __uniq$2;
  } else if (__uniq$3.tag === "List$cons") {
    const __uniq$9 = String(__uniq$3._1);
    const __uniq$12 = List$foldl$__at__$List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1$spec__4(__uniq$1, { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 }, _2: { tag: "Std$Format$text", _1: __uniq$9 } }, __uniq$3._2);
    return __uniq$12;
  }
};
export const Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1.tag === "List$nil") {
    return { tag: "Std$Format$nil" };
  } else if (__uniq$1.tag === "List$cons") {
    return __uniq$1._2.tag === "List$nil" ? Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$__lam__0(__uniq$1._1) : List$foldl$__at__$Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$spec__1(__uniq$2, Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0$__lam__0(__uniq$1._1), __uniq$1._2);
  }
};
export const Array$repr$__at__$main$spec__0 = (/* obj */ __uniq$1) => __uniq$1.length === 0 ? { tag: "Std$Format$text", _1: "#[]" } : Std$Format$fill({ tag: "Std$Format$nest", _1: Array$repr$__at__$main$spec__0$__closed__5, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$text", _1: "#[" }, _2: Std$Format$joinSep$__at__$Array$repr$__at__$main$spec__0$spec__0(lean_array_to_list(__uniq$1), { tag: "Std$Format$append", _1: { tag: "Std$Format$text", _1: "," }, _2: { tag: "Std$Format$line" } }) }, _2: { tag: "Std$Format$text", _1: "]" } } });
export const main$__closed__3 = Array$repr$__at__$main$spec__0(main$__closed__2);
export const IO$print$__at__$IO$println$__at__$main$spec__1$spec__2 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__1 = (/* tobj */ __uniq$1) => {
  const __uniq$3 = 120;
  const __uniq$4 = 0;
  const __uniq$5 = Std$Format$pretty(__uniq$1, __uniq$3, __uniq$4, __uniq$4);
  const __uniq$6 = 10;
  const __uniq$7 = __uniq$5 + String.fromCodePoint(__uniq$6);
  const __uniq$8 = IO$print$__at__$IO$println$__at__$main$spec__1$spec__2(__uniq$7);
  return __uniq$8;
};
export const main$__lam__1 = (/* tobj */ __uniq$1) => lean_array_push(lean_array_push([], __uniq$1), __uniq$1);
export const main$__closed__5 = test2$__redArg(main$__lam__1, main$__closed__1);
export const main$__closed__6 = Array$repr$__at__$main$spec__0(main$__closed__5);
export const main = () => {
  const __uniq$2 = main$__closed__3;
  const __uniq$3 = IO$println$__at__$main$spec__1(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__1(main$__closed__6);
    return __uniq$5;
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$test1$spec__0 = (/* tobj */ __uniq$3, /* obj */ __uniq$4, /* USize */ __uniq$5, /* USize */ __uniq$6, /* obj */ __uniq$7) => __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$test1$spec__0$__redArg(__uniq$3, __uniq$4, __uniq$5, __uniq$6, __uniq$7);
export const __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$test2$spec__0 = (/* obj */ __uniq$2, /* USize */ __uniq$3, /* USize */ __uniq$4, /* obj */ __uniq$5) => __private$Init$Data$Array$Basic$0$Array$forIn_u39_Unsafe$loop$__at__$test2$spec__0$__redArg(__uniq$2, __uniq$3, __uniq$4, __uniq$5);

main();
