// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
import { lean_st_mk_ref, lean_st_ref_get, lean_st_ref_set } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/ST.js";
export const test1$__lam__0 = (/* tobj */ __uniq$1) => ({ tag: "EST$Out$ok", _1: lean_st_ref_get(__uniq$1) });
export const test2$__lam__1 = (/* tobj */ __uniq$1) => ({ tag: "EST$Out$ok", _1: lean_st_ref_get(__uniq$1) });
export const test2$__lam__0 = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => {
  const __uniq$4 = __uniq$1();
  if (__uniq$4.tag === "EST$Out$ok") {
    const __uniq$10 = lean_st_ref_set(__uniq$2, __uniq$4._1 + 1);
    return { tag: "EST$Out$ok", _1: __uniq$10 };
  } else if (__uniq$4.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$4._1 };
  }
};
export const whileE = (/* obj */ __uniq$1, /* obj */ __uniq$2) => {
  while (true) {
    const __uniq$4 = __uniq$1();
    if (__uniq$4.tag === "EST$Out$ok") {
      if (__uniq$4._1) {
        const __uniq$11 = __uniq$2();
        if (__uniq$11.tag === "EST$Out$ok") {
          const _tmp_0 = __uniq$1;
          const _tmp_1 = __uniq$2;
          __uniq$1 = _tmp_0;
          __uniq$2 = _tmp_1;
          continue;
        } else if (__uniq$11.tag === "EST$Out$error") {
          return __uniq$11;
        }
      } else {
        return { tag: "EST$Out$ok", _1: { tag: "PUnit$unit" } };
      }
    } else if (__uniq$4.tag === "EST$Out$error") {
      return { tag: "EST$Out$error", _1: __uniq$4._1 };
    }
  }
};
export const test2$__lam__2 = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => {
  const __uniq$4 = __uniq$1();
  if (__uniq$4.tag === "EST$Out$ok") {
    const __uniq$10 = lean_st_ref_set(__uniq$2, __uniq$4._1 + 2);
    return { tag: "EST$Out$ok", _1: __uniq$10 };
  } else if (__uniq$4.tag === "EST$Out$error") {
    return { tag: "EST$Out$error", _1: __uniq$4._1 };
  }
};
export const test2 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  const __uniq$4 = test1$__lam__0.length - 1 === 0 ? () => test1$__lam__0(__uniq$1) : test1$__lam__0.length - 1 === 1 ? (x_1) => test1$__lam__0(__uniq$1, x_1) : test1$__lam__0.length - 1 === 2 ? (x_1, x_2) => test1$__lam__0(__uniq$1, x_1, x_2) : (x_1, x_2, x_3) => test1$__lam__0(__uniq$1, x_1, x_2, x_3);
  const __uniq$5 = test2$__lam__1.length - 1 === 0 ? () => test2$__lam__1(__uniq$2) : test2$__lam__1.length - 1 === 1 ? (x_1) => test2$__lam__1(__uniq$2, x_1) : test2$__lam__1.length - 1 === 2 ? (x_1, x_2) => test2$__lam__1(__uniq$2, x_1, x_2) : (x_1, x_2, x_3) => test2$__lam__1(__uniq$2, x_1, x_2, x_3);
  const __uniq$6 = test2$__lam__0.length - 2 === 0 ? () => test2$__lam__0(__uniq$5, __uniq$2) : test2$__lam__0.length - 2 === 1 ? (x_1) => test2$__lam__0(__uniq$5, __uniq$2, x_1) : test2$__lam__0.length - 2 === 2 ? (x_1, x_2) => test2$__lam__0(__uniq$5, __uniq$2, x_1, x_2) : (x_1, x_2, x_3) => test2$__lam__0(__uniq$5, __uniq$2, x_1, x_2, x_3);
  const __uniq$7 = whileE(__uniq$4, __uniq$6);
  if (__uniq$7.tag === "EST$Out$ok") {
    const __uniq$8 = test2$__lam__2.length - 2 === 0 ? () => test2$__lam__2(__uniq$5, __uniq$2) : test2$__lam__2.length - 2 === 1 ? (x_1) => test2$__lam__2(__uniq$5, __uniq$2, x_1) : test2$__lam__2.length - 2 === 2 ? (x_1, x_2) => test2$__lam__2(__uniq$5, __uniq$2, x_1, x_2) : (x_1, x_2, x_3) => test2$__lam__2(__uniq$5, __uniq$2, x_1, x_2, x_3);
    const __uniq$9 = whileE(__uniq$4, __uniq$8);
    return __uniq$9;
  } else if (__uniq$7.tag === "EST$Out$error") {
    return __uniq$7;
  }
};
export const test1$__lam__1 = (/* tobj */ __uniq$1) => {
  const __uniq$3 = lean_st_ref_get(__uniq$1);
  const __uniq$4 = 1;
  const __uniq$5 = __uniq$3 + __uniq$4;
  const __uniq$6 = lean_st_ref_set(__uniq$1, __uniq$5);
  const __uniq$7 = lean_st_ref_get(__uniq$1);
  const __uniq$8 = 2;
  const __uniq$9 = __uniq$7 + __uniq$8;
  const __uniq$10 = lean_st_ref_set(__uniq$1, __uniq$9);
  const __uniq$11 = { tag: "EST$Out$ok", _1: __uniq$10 };
  return __uniq$11;
};
export const test1 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => whileE(test1$__lam__0.length - 1 === 0 ? () => test1$__lam__0(__uniq$1) : test1$__lam__0.length - 1 === 1 ? (x_1) => test1$__lam__0(__uniq$1, x_1) : test1$__lam__0.length - 1 === 2 ? (x_1, x_2) => test1$__lam__0(__uniq$1, x_1, x_2) : (x_1, x_2, x_3) => test1$__lam__0(__uniq$1, x_1, x_2, x_3), test1$__lam__1.length - 1 === 0 ? () => test1$__lam__1(__uniq$2) : test1$__lam__1.length - 1 === 1 ? (x_1) => test1$__lam__1(__uniq$2, x_1) : test1$__lam__1.length - 1 === 2 ? (x_1, x_2) => test1$__lam__1(__uniq$2, x_1, x_2) : (x_1, x_2, x_3) => test1$__lam__1(__uniq$2, x_1, x_2, x_3));
export const test4$__lam__1 = (/* tobj */ __uniq$1) => {
  const __uniq$3 = lean_st_ref_get(__uniq$1);
  const __uniq$4 = 10;
  const __uniq$5 = __uniq$3 < __uniq$4;
  return __uniq$5 ? { tag: "EST$Out$ok", _1: lean_st_ref_set(__uniq$1, __uniq$3 + 1) } : { tag: "EST$Out$ok", _1: lean_st_ref_set(__uniq$1, __uniq$3 + 2) };
};
export const test3$__lam__1 = (/* tobj */ __uniq$1) => {
  const __uniq$3 = lean_st_ref_get(__uniq$1);
  const __uniq$4 = 10;
  const __uniq$5 = __uniq$3 < __uniq$4;
  return __uniq$5 ? { tag: "EST$Out$ok", _1: lean_st_ref_set(__uniq$1, __uniq$3 + 1) } : { tag: "EST$Out$ok", _1: { tag: "PUnit$unit" } };
};
export const test3 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => whileE(test1$__lam__0.length - 1 === 0 ? () => test1$__lam__0(__uniq$1) : test1$__lam__0.length - 1 === 1 ? (x_1) => test1$__lam__0(__uniq$1, x_1) : test1$__lam__0.length - 1 === 2 ? (x_1, x_2) => test1$__lam__0(__uniq$1, x_1, x_2) : (x_1, x_2, x_3) => test1$__lam__0(__uniq$1, x_1, x_2, x_3), test3$__lam__1.length - 1 === 0 ? () => test3$__lam__1(__uniq$2) : test3$__lam__1.length - 1 === 1 ? (x_1) => test3$__lam__1(__uniq$2, x_1) : test3$__lam__1.length - 1 === 2 ? (x_1, x_2) => test3$__lam__1(__uniq$2, x_1, x_2) : (x_1, x_2, x_3) => test3$__lam__1(__uniq$2, x_1, x_2, x_3));
export const test4 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => whileE(test1$__lam__0.length - 1 === 0 ? () => test1$__lam__0(__uniq$1) : test1$__lam__0.length - 1 === 1 ? (x_1) => test1$__lam__0(__uniq$1, x_1) : test1$__lam__0.length - 1 === 2 ? (x_1, x_2) => test1$__lam__0(__uniq$1, x_1, x_2) : (x_1, x_2, x_3) => test1$__lam__0(__uniq$1, x_1, x_2, x_3), test4$__lam__1.length - 1 === 0 ? () => test4$__lam__1(__uniq$2) : test4$__lam__1.length - 1 === 1 ? (x_1) => test4$__lam__1(__uniq$2, x_1) : test4$__lam__1.length - 1 === 2 ? (x_1, x_2) => test4$__lam__1(__uniq$2, x_1, x_2) : (x_1, x_2, x_3) => test4$__lam__1(__uniq$2, x_1, x_2, x_3));
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main = () => {
  const __uniq$2 = 0;
  const __uniq$3 = __uniq$2;
  const __uniq$4 = lean_st_mk_ref(__uniq$3);
  const __uniq$5 = 0;
  const __uniq$6 = lean_st_mk_ref(__uniq$5);
  const __uniq$7 = test1(__uniq$4, __uniq$6);
  if (__uniq$7.tag === "EST$Out$ok") {
    const __uniq$8 = test2(__uniq$4, __uniq$6);
    if (__uniq$8.tag === "EST$Out$ok") {
      const __uniq$9 = test3(__uniq$4, __uniq$6);
      if (__uniq$9.tag === "EST$Out$ok") {
        const __uniq$10 = test4(__uniq$4, __uniq$6);
        if (__uniq$10.tag === "EST$Out$ok") {
          const __uniq$11 = lean_st_ref_get(__uniq$6);
          const __uniq$12 = IO$println$__at__$main$spec__0(__uniq$11);
          return __uniq$12;
        } else if (__uniq$10.tag === "EST$Out$error") {
          return __uniq$10;
        }
      } else if (__uniq$9.tag === "EST$Out$error") {
        return __uniq$9;
      }
    } else if (__uniq$8.tag === "EST$Out$error") {
      return __uniq$8;
    }
  } else if (__uniq$7.tag === "EST$Out$error") {
    return __uniq$7;
  }
};

main();
