// Generated by Lean ES6 emitter
import { Std$Format$pretty } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Format/Basic.js";
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { List$reverse$__redArg } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/List/Basic.js";
import { Repr$addAppParen, String$quote } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Repr.js";
import { lean_string_length } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/String/Bootstrap.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg$__closed__7 = { tag: "Std$Format$text", _1: "(" };
export const Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg$__closed__3 = { tag: "Std$Format$append", _1: { tag: "Std$Format$text", _1: "," }, _2: { tag: "Std$Format$line" } };
export const List$foldl$__at__$Std$Format$joinSep$__at__$Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$spec__1$spec__4 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  while (true) {
    if (__uniq$3.tag === "List$nil") {
      return __uniq$2;
    } else if (__uniq$3.tag === "List$cons") {
      const __uniq$4 = __uniq$3._1;
      const __uniq$5 = __uniq$3._2;
      {
        const __uniq$12 = { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 };
        {
          const _tmp_0 = __uniq$1;
          __uniq$1 = _tmp_0;
          __uniq$2 = { tag: "Std$Format$append", _1: __uniq$12, _2: __uniq$4 };
          __uniq$3 = __uniq$5;
          continue;
        }
      }
    }
  }
};
export const Std$Format$joinSep$__at__$Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$spec__1 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1.tag === "List$nil") {
    return { tag: "Std$Format$nil" };
  } else if (__uniq$1.tag === "List$cons") {
    return __uniq$1._2.tag === "List$nil" ? __uniq$1._1 : List$foldl$__at__$Std$Format$joinSep$__at__$Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$spec__1$spec__4(__uniq$2, __uniq$1._1, __uniq$1._2);
  }
};
export const Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg$__closed__5 = lean_string_length("(");
export const Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg$__closed__8 = { tag: "Std$Format$text", _1: ")" };
export const Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg = (/* obj */ __uniq$1) => {
  const __uniq$2 = __uniq$1._1;
  const __uniq$3 = __uniq$1._2;
  const __uniq$35 = true;
  {
    const __uniq$6 = String$quote(__uniq$2);
    const __uniq$33 = { tag: "List$cons", _1: { tag: "Std$Format$text", _1: __uniq$6 }, _2: { tag: "List$nil" } };
    {
      if (__uniq$3 < 0) {
        const __uniq$29 = String(__uniq$3);
        const __uniq$31 = Repr$addAppParen({ tag: "Std$Format$text", _1: __uniq$29 }, 0);
        {
          const __uniq$12 = List$reverse$__redArg({ tag: "List$cons", _1: __uniq$31, _2: __uniq$33 });
          const __uniq$14 = Std$Format$joinSep$__at__$Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$spec__1(__uniq$12, Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg$__closed__3);
          const __uniq$22 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg$__closed__5, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg$__closed__7, _2: __uniq$14 }, _2: Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg$__closed__8 } } };
          __uniq$22._2 = 0;
          return __uniq$22;
        }
      } else {
        const __uniq$27 = String(__uniq$3);
        {
          const __uniq$12 = List$reverse$__redArg({ tag: "List$cons", _1: { tag: "Std$Format$text", _1: __uniq$27 }, _2: __uniq$33 });
          const __uniq$14 = Std$Format$joinSep$__at__$Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$spec__1(__uniq$12, Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg$__closed__3);
          const __uniq$22 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg$__closed__5, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg$__closed__7, _2: __uniq$14 }, _2: Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg$__closed__8 } } };
          __uniq$22._2 = 0;
          return __uniq$22;
        }
      }
    }
  }
};
export const List$filterTR$loop$__at__$poke$spec__0 = (/* obj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  while (true) {
    if (__uniq$2.tag === "List$nil") {
      const __uniq$4 = List$reverse$__redArg(__uniq$3);
      return __uniq$4;
    } else if (__uniq$2.tag === "List$cons") {
      const __uniq$5 = __uniq$2._1;
      const __uniq$6 = __uniq$2._2;
      {
        const __uniq$10 = __uniq$5._1 === __uniq$1;
        if (__uniq$10) {
          const _tmp_0 = __uniq$1;
          const _tmp_2 = __uniq$3;
          __uniq$1 = _tmp_0;
          __uniq$2 = __uniq$6;
          __uniq$3 = _tmp_2;
          continue;
        } else {
          const __uniq$14 = { tag: "List$cons", _1: __uniq$5, _2: __uniq$3 };
          {
            const _tmp_0 = __uniq$1;
            __uniq$1 = _tmp_0;
            __uniq$2 = __uniq$6;
            __uniq$3 = __uniq$14;
            continue;
          }
        }
      }
    }
  }
};
export const poke = (/* obj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => ({ tag: "List$cons", _1: { tag: "Prod$mk", _1: __uniq$1, _2: __uniq$2 }, _2: List$filterTR$loop$__at__$poke$spec__0(__uniq$1, __uniq$3, { tag: "List$nil" }) });
export const test3$__closed__2 = poke("a", 1, { tag: "List$nil" });
export const test3$__closed__5 = poke("b", 2, test3$__closed__2);
export const deleteKey = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => List$filterTR$loop$__at__$poke$spec__0(__uniq$1, __uniq$2, { tag: "List$nil" });
export const test5$__closed__0 = deleteKey("a", test3$__closed__5);
export const IO$print$__at__$IO$println$__at__$main$spec__1$spec__3 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const List$repr$__at__$main$spec__0$__redArg$__closed__4 = lean_string_length("[");
export const List$foldl$__at__$List$foldl$__at__$Std$Format$joinSep$__at__$List$repr$__at__$main$spec__0$spec__1$spec__3$spec__7 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  while (true) {
    if (__uniq$3.tag === "List$nil") {
      return __uniq$2;
    } else if (__uniq$3.tag === "List$cons") {
      const __uniq$4 = __uniq$3._1;
      const __uniq$5 = __uniq$3._2;
      {
        const __uniq$13 = { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 };
        {
          const __uniq$9 = Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg(__uniq$4);
          const _tmp_0 = __uniq$1;
          __uniq$1 = _tmp_0;
          __uniq$2 = { tag: "Std$Format$append", _1: __uniq$13, _2: __uniq$9 };
          __uniq$3 = __uniq$5;
          continue;
        }
      }
    }
  }
};
export const List$foldl$__at__$Std$Format$joinSep$__at__$List$repr$__at__$main$spec__0$spec__1$spec__3 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  if (__uniq$3.tag === "List$nil") {
    return __uniq$2;
  } else if (__uniq$3.tag === "List$cons") {
    const __uniq$9 = Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg(__uniq$3._1);
    const __uniq$11 = List$foldl$__at__$List$foldl$__at__$Std$Format$joinSep$__at__$List$repr$__at__$main$spec__0$spec__1$spec__3$spec__7(__uniq$1, { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: __uniq$2, _2: __uniq$1 }, _2: __uniq$9 }, __uniq$3._2);
    return __uniq$11;
  }
};
export const Std$Format$joinSep$__at__$List$repr$__at__$main$spec__0$spec__1 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1.tag === "List$nil") {
    return { tag: "Std$Format$nil" };
  } else if (__uniq$1.tag === "List$cons") {
    return __uniq$1._2.tag === "List$nil" ? Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg(__uniq$1._1) : List$foldl$__at__$Std$Format$joinSep$__at__$List$repr$__at__$main$spec__0$spec__1$spec__3(__uniq$2, Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg(__uniq$1._1), __uniq$1._2);
  }
};
export const List$repr$__at__$main$spec__0$__redArg = (/* tobj */ __uniq$1) => {
  if (__uniq$1.tag === "List$nil") {
    return { tag: "Std$Format$text", _1: "[]" };
  } else {
    const __uniq$4 = Std$Format$joinSep$__at__$List$repr$__at__$main$spec__0$spec__1(__uniq$1, Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg$__closed__3);
    const __uniq$12 = { tag: "Std$Format$group", _1: { tag: "Std$Format$nest", _1: List$repr$__at__$main$spec__0$__redArg$__closed__4, _2: { tag: "Std$Format$append", _1: { tag: "Std$Format$append", _1: { tag: "Std$Format$text", _1: "[" }, _2: __uniq$4 }, _2: { tag: "Std$Format$text", _1: "]" } } } };
    __uniq$12._2 = 0;
    return __uniq$12;
  }
};
export const main$__closed__0 = List$repr$__at__$main$spec__0$__redArg({ tag: "List$nil" });
export const IO$println$__at__$main$spec__1 = (/* tobj */ __uniq$1) => {
  const __uniq$3 = 120;
  const __uniq$4 = 0;
  const __uniq$5 = Std$Format$pretty(__uniq$1, __uniq$3, __uniq$4, __uniq$4);
  const __uniq$6 = 10;
  const __uniq$7 = __uniq$5 + String.fromCodePoint(__uniq$6);
  const __uniq$8 = IO$print$__at__$IO$println$__at__$main$spec__1$spec__3(__uniq$7);
  return __uniq$8;
};
export const test3$__closed__8 = poke("c", 3, test3$__closed__5);
export const test3 = () => test3$__closed__8;
export const main$__closed__1 = List$repr$__at__$main$spec__0$__redArg(test3());
export const test5$__closed__1 = deleteKey("b", test5$__closed__0);
export const test5 = () => test5$__closed__1;
export const main$__closed__2 = List$repr$__at__$main$spec__0$__redArg(test5());
export const main = () => {
  const __uniq$2 = main$__closed__0;
  const __uniq$3 = IO$println$__at__$main$spec__1(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__1(main$__closed__1);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__1(main$__closed__2);
      return __uniq$7;
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const List$repr$__at__$main$spec__0 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => List$repr$__at__$main$spec__0$__redArg(__uniq$1);
export const Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => Prod$repr$__at__$List$repr$__at__$main$spec__0$spec__0$__redArg(__uniq$1);
export const test1 = () => ({ tag: "List$nil" });

main();
