// Generated by Lean ES6 emitter
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const test1 = (/* tobj */ __uniq$1) => {
  while (true) {
    const __uniq$2 = 0;
    const __uniq$3 = __uniq$1 === __uniq$2;
    if (__uniq$3) {
      return __uniq$2;
    } else {
      const __uniq$5 = __uniq$1 > 1 ? __uniq$1 - 1 : 0;
      if (__uniq$5 === __uniq$2) {
        return 1;
      } else {
        const __uniq$7 = __uniq$5 > 1 ? __uniq$5 - 1 : 0;
        if (__uniq$7 === __uniq$2) {
          return 2;
        } else {
          __uniq$1 = (__uniq$7 > 1 ? __uniq$7 - 1 : 0) + 1;
          continue;
        }
      }
    }
  }
};
export const main$__closed__0 = test1(9);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main = () => IO$println$__at__$main$spec__0(main$__closed__0);

main();
