// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { lean_array_fget_borrowed, lean_array_push } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const main$__lam__0 = (/* tobj */ __uniq$1) => __uniq$1 < 10;
export const main$__closed__9 = lean_array_push(lean_array_push(lean_array_push(lean_array_push([], 1), 2), 11), 3);
export const main$__closed__5 = lean_array_push(lean_array_push(lean_array_push([], 1), 2), 3);
export const span$go = (/* obj */ __uniq$1, /* obj */ __uniq$2, /* tobj */ __uniq$3) => {
  while (true) {
    const __uniq$4 = __uniq$2.length;
    const __uniq$5 = __uniq$3 < __uniq$4;
    if (__uniq$5) {
      const __uniq$7 = lean_array_fget_borrowed(__uniq$2, __uniq$3);
      const __uniq$8 = __uniq$1(__uniq$7);
      if (__uniq$8) {
        const __uniq$12 = __uniq$3 + 1;
        const _tmp_0 = __uniq$1;
        const _tmp_1 = __uniq$2;
        __uniq$1 = _tmp_0;
        __uniq$2 = _tmp_1;
        __uniq$3 = __uniq$12;
        continue;
      } else {
        return { tag: "Option$some", _1: __uniq$3 };
      }
    } else {
      return { tag: "Option$none" };
    }
  }
};
export const span = (/* obj */ __uniq$1, /* obj */ __uniq$2) => span$go(__uniq$1, __uniq$2, 0);
export const main$__closed__6 = span(main$__lam__0, main$__closed__5);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main$__closed__10 = span(main$__lam__0, main$__closed__9);
export const main = () => {
  const __uniq$11 = main$__closed__10;
  if (__uniq$11.tag === "Option$none") {
    const __uniq$13 = IO$println$__at__$main$spec__0("none");
    if (__uniq$13.tag === "EST$Out$ok") {
      if (main$__closed__6.tag === "Option$none") {
        const __uniq$4 = IO$println$__at__$main$spec__0("none");
        return __uniq$4;
      } else if (main$__closed__6.tag === "Option$some") {
        const __uniq$7 = String(main$__closed__6._1);
        const __uniq$9 = IO$println$__at__$main$spec__0("some " + __uniq$7);
        return __uniq$9;
      }
    } else if (__uniq$13.tag === "EST$Out$error") {
      return __uniq$13;
    }
  } else if (__uniq$11.tag === "Option$some") {
    const __uniq$16 = String(__uniq$11._1);
    const __uniq$18 = IO$println$__at__$main$spec__0("some " + __uniq$16);
    if (__uniq$18.tag === "EST$Out$ok") {
      if (main$__closed__6.tag === "Option$none") {
        const __uniq$4 = IO$println$__at__$main$spec__0("none");
        return __uniq$4;
      } else if (main$__closed__6.tag === "Option$some") {
        const __uniq$7 = String(main$__closed__6._1);
        const __uniq$9 = IO$println$__at__$main$spec__0("some " + __uniq$7);
        return __uniq$9;
      }
    } else if (__uniq$18.tag === "EST$Out$error") {
      return __uniq$18;
    }
  }
};

main();
