// Generated by Lean ES6 emitter
import { lean_array_uget_borrowed } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Array/Basic.js";
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_usize_add, lean_usize_of_nat } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/UInt/BasicAux.js";
import { lean_array_push } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Prelude.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test$spec__0 = (/* obj */ __uniq$1, /* USize */ __uniq$2, /* USize */ __uniq$3, /* tobj */ __uniq$4) => {
  while (true) {
    const __uniq$5 = __uniq$2 === __uniq$3;
    if (__uniq$5) {
      return __uniq$4;
    } else {
      const __uniq$6 = lean_array_uget_borrowed(__uniq$1, __uniq$2);
      const __uniq$7 = __uniq$4 + __uniq$6;
      const __uniq$9 = lean_usize_add(__uniq$2, 1);
      const _tmp_0 = __uniq$1;
      const _tmp_2 = __uniq$3;
      __uniq$1 = _tmp_0;
      __uniq$2 = __uniq$9;
      __uniq$3 = _tmp_2;
      __uniq$4 = __uniq$7;
      continue;
    }
  }
};
export const test$__lam__0 = (/* tobj */ __uniq$1, /* tobj */ __uniq$2, /* tobj */ __uniq$3) => {
  const __uniq$4 = 0;
  const __uniq$5 = 0;
  const __uniq$6 = 19;
  const __uniq$7 = [];
  const __uniq$8 = lean_array_push(__uniq$7, __uniq$1);
  const __uniq$9 = lean_array_push(__uniq$8, __uniq$2);
  const __uniq$10 = lean_array_push(__uniq$9, __uniq$3);
  const __uniq$11 = lean_array_push(__uniq$10, __uniq$2);
  const __uniq$12 = lean_array_push(__uniq$11, __uniq$3);
  const __uniq$13 = lean_array_push(__uniq$12, __uniq$2);
  const __uniq$14 = lean_array_push(__uniq$13, __uniq$3);
  const __uniq$15 = lean_array_push(__uniq$14, __uniq$2);
  const __uniq$16 = lean_array_push(__uniq$15, __uniq$3);
  const __uniq$17 = lean_array_push(__uniq$16, __uniq$2);
  const __uniq$18 = lean_array_push(__uniq$17, __uniq$3);
  const __uniq$19 = lean_array_push(__uniq$18, __uniq$2);
  const __uniq$20 = lean_array_push(__uniq$19, __uniq$3);
  const __uniq$21 = lean_array_push(__uniq$20, __uniq$2);
  const __uniq$22 = lean_array_push(__uniq$21, __uniq$3);
  const __uniq$23 = lean_array_push(__uniq$22, __uniq$2);
  const __uniq$24 = lean_array_push(__uniq$23, __uniq$3);
  const __uniq$25 = lean_array_push(__uniq$24, __uniq$2);
  const __uniq$26 = lean_array_push(__uniq$25, __uniq$3);
  const __uniq$27 = __uniq$26.length;
  const __uniq$28 = __uniq$4 < __uniq$27;
  return __uniq$28 ? __uniq$27 <= __uniq$27 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test$spec__0(__uniq$26, 0, lean_usize_of_nat(__uniq$27), __uniq$5) : __uniq$28 ? __private$Init$Data$Array$Basic$0$Array$foldlMUnsafe$fold$__at__$test$spec__0(__uniq$26, 0, lean_usize_of_nat(__uniq$27), __uniq$5) : __uniq$5 : __uniq$5;
};
export const test = (/* tobj */ __uniq$1, /* tobj */ __uniq$2) => test$__lam__0(__uniq$1, __uniq$1, __uniq$2) + test$__lam__0(__uniq$1, __uniq$2, __uniq$1);
export const main$__closed__2 = test(1, 2);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* tobj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(String(__uniq$1) + String.fromCodePoint(10));
export const main = () => IO$println$__at__$main$spec__0(main$__closed__2);

main();
