// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
import { lean_st_mk_ref, lean_st_ref_get, lean_st_ref_set } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/ST.js";
export const main$__lam__0 = (/* tobj */ __uniq$1) => __uniq$1;
export const test = (/* tobj */ __uniq$1) => {
  const __uniq$3 = 0;
  const __uniq$4 = lean_st_mk_ref(__uniq$3);
  const __uniq$5 = __uniq$1(__uniq$4);
  const __uniq$6 = lean_st_ref_get(__uniq$5);
  const __uniq$7 = 1;
  const __uniq$8 = __uniq$6 + __uniq$7;
  const __uniq$9 = lean_st_ref_set(__uniq$5, __uniq$8);
  const __uniq$10 = lean_st_ref_get(__uniq$4);
  const __uniq$11 = __uniq$10 + __uniq$7;
  const __uniq$12 = lean_st_ref_set(__uniq$4, __uniq$11);
  const __uniq$13 = { tag: "EST$Out$ok", _1: __uniq$12 };
  return __uniq$13;
};
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main = () => {
  const __uniq$2 = main$__lam__0;
  const __uniq$3 = test(__uniq$2);
  const __uniq$4 = "ok";
  const __uniq$5 = IO$println$__at__$main$spec__0(__uniq$4);
  return __uniq$5;
};

main();
