// Generated by Lean ES6 emitter
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const Fun$ctorElim$__redArg = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => __uniq$2(__uniq$1._1, __uniq$1._2);
export const Fun$Abs$elim = (/* obj */ __uniq$2, /* tobj */ __uniq$4) => Fun$ctorElim$__redArg(__uniq$2, __uniq$4);
export const rewriteBottomUp$__lam__0 = (/* obj */ __uniq$1, /* obj */ __uniq$2) => __uniq$1(__uniq$2);
export const rewriteBottomUpM$__redArg$__lam__0 = (/* tobj */ __uniq$1, /* obj */ __uniq$2) => __uniq$1(__uniq$2);
export const traverseFun1$__redArg$__lam__0 = (/* obj */ __uniq$1, /* obj */ __uniq$2) => ({ tag: "Fun$Abs", _1: __uniq$1, _2: __uniq$2 });
export const traverseFun1$__redArg$__lam__1 = (/* obj */ __uniq$1, /* obj */ __uniq$2) => ({ tag: "Fun$App", _1: __uniq$1, _2: __uniq$2 });
export const traverseFun1$__redArg$__lam__2 = (/* tobj */ __uniq$1, /* obj */ __uniq$2, /* tagged */ __uniq$3) => __uniq$1(__uniq$2);
export const traverseFun1$__redArg = (/* obj */ __uniq$1, /* tobj */ __uniq$2, /* obj */ __uniq$3) => {
  if (__uniq$3.tag === "Fun$Abs") {
    const __uniq$8 = traverseFun1$__redArg$__lam__0.length - 1 === 0 ? () => traverseFun1$__redArg$__lam__0(__uniq$3._1) : traverseFun1$__redArg$__lam__0.length - 1 === 1 ? (x_1) => traverseFun1$__redArg$__lam__0(__uniq$3._1, x_1) : traverseFun1$__redArg$__lam__0.length - 1 === 2 ? (x_1, x_2) => traverseFun1$__redArg$__lam__0(__uniq$3._1, x_1, x_2) : (x_1, x_2, x_3) => traverseFun1$__redArg$__lam__0(__uniq$3._1, x_1, x_2, x_3);
    const __uniq$9 = __uniq$2(__uniq$3._2);
    const __uniq$10 = __uniq$1._1._1(__uniq$8, __uniq$9);
    return __uniq$10;
  } else if (__uniq$3.tag === "Fun$App") {
    const __uniq$17 = traverseFun1$__redArg$__lam__2.length - 2 === 0 ? () => traverseFun1$__redArg$__lam__2(__uniq$2, __uniq$3._2) : traverseFun1$__redArg$__lam__2.length - 2 === 1 ? (x_1) => traverseFun1$__redArg$__lam__2(__uniq$2, __uniq$3._2, x_1) : traverseFun1$__redArg$__lam__2.length - 2 === 2 ? (x_1, x_2) => traverseFun1$__redArg$__lam__2(__uniq$2, __uniq$3._2, x_1, x_2) : (x_1, x_2, x_3) => traverseFun1$__redArg$__lam__2(__uniq$2, __uniq$3._2, x_1, x_2, x_3);
    const __uniq$18 = __uniq$2(__uniq$3._1);
    const __uniq$19 = __uniq$1._1._1(traverseFun1$__redArg$__lam__1, __uniq$18);
    const __uniq$20 = __uniq$1._3(__uniq$19, __uniq$17);
    return __uniq$20;
  }
};
export const rewriteBottomUpM$__redArg = (/* obj */ __uniq$1, /* tobj */ __uniq$2, /* obj */ __uniq$3) => __uniq$1._2(traverseFun1$__redArg(__uniq$1._1, rewriteBottomUpM$__redArg.length - 2 === 0 ? () => rewriteBottomUpM$__redArg(__uniq$1, __uniq$2) : rewriteBottomUpM$__redArg.length - 2 === 1 ? (x_1) => rewriteBottomUpM$__redArg(__uniq$1, __uniq$2, x_1) : rewriteBottomUpM$__redArg.length - 2 === 2 ? (x_1, x_2) => rewriteBottomUpM$__redArg(__uniq$1, __uniq$2, x_1, x_2) : (x_1, x_2, x_3) => rewriteBottomUpM$__redArg(__uniq$1, __uniq$2, x_1, x_2, x_3), __uniq$3), rewriteBottomUpM$__redArg$__lam__0.length - 1 === 0 ? () => rewriteBottomUpM$__redArg$__lam__0(__uniq$2) : rewriteBottomUpM$__redArg$__lam__0.length - 1 === 1 ? (x_1) => rewriteBottomUpM$__redArg$__lam__0(__uniq$2, x_1) : rewriteBottomUpM$__redArg$__lam__0.length - 1 === 2 ? (x_1, x_2) => rewriteBottomUpM$__redArg$__lam__0(__uniq$2, x_1, x_2) : (x_1, x_2, x_3) => rewriteBottomUpM$__redArg$__lam__0(__uniq$2, x_1, x_2, x_3));
export const Fun$ctorIdx = (/* obj */ __uniq$1) => {
  if (__uniq$1.tag === "Fun$Abs") {
    return 0;
  } else if (__uniq$1.tag === "Fun$App") {
    return 1;
  }
};
export const traverseFun1 = (/* obj */ __uniq$2, /* tobj */ __uniq$3, /* obj */ __uniq$4) => traverseFun1$__redArg(__uniq$2, __uniq$3, __uniq$4);
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main = () => IO$println$__at__$main$spec__0("ok");
export const Fun$App$elim$__redArg = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => Fun$ctorElim$__redArg(__uniq$1, __uniq$2);
export const Fun$App$elim = (/* obj */ __uniq$2, /* tobj */ __uniq$4) => Fun$ctorElim$__redArg(__uniq$2, __uniq$4);
export const rewriteBottomUpM = (/* obj */ __uniq$2, /* tobj */ __uniq$3, /* obj */ __uniq$4) => rewriteBottomUpM$__redArg(__uniq$2, __uniq$3, __uniq$4);
export const Fun$Abs$elim$__redArg = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => Fun$ctorElim$__redArg(__uniq$1, __uniq$2);
export const traverseFun1$__at__$rewriteBottomUpM$__at__$rewriteBottomUp$spec__0$spec__0 = (/* obj */ __uniq$1, /* obj */ __uniq$2) => {
  if (__uniq$2.tag === "Fun$Abs") {
    const __uniq$7 = __uniq$1(__uniq$2._2);
    return { tag: "Fun$Abs", _1: __uniq$2._1, _2: __uniq$7 };
  } else if (__uniq$2.tag === "Fun$App") {
    const __uniq$15 = __uniq$1(__uniq$2._1);
    const __uniq$16 = __uniq$1(__uniq$2._2);
    return { tag: "Fun$App", _1: __uniq$15, _2: __uniq$16 };
  }
};
export const rewriteBottomUpM$__at__$rewriteBottomUp$spec__0 = (/* obj */ __uniq$1, /* obj */ __uniq$2) => __uniq$1(traverseFun1$__at__$rewriteBottomUpM$__at__$rewriteBottomUp$spec__0$spec__0(rewriteBottomUpM$__at__$rewriteBottomUp$spec__0$__lam__0.length - 1 === 0 ? () => rewriteBottomUpM$__at__$rewriteBottomUp$spec__0$__lam__0(__uniq$1) : rewriteBottomUpM$__at__$rewriteBottomUp$spec__0$__lam__0.length - 1 === 1 ? (x_1) => rewriteBottomUpM$__at__$rewriteBottomUp$spec__0$__lam__0(__uniq$1, x_1) : rewriteBottomUpM$__at__$rewriteBottomUp$spec__0$__lam__0.length - 1 === 2 ? (x_1, x_2) => rewriteBottomUpM$__at__$rewriteBottomUp$spec__0$__lam__0(__uniq$1, x_1, x_2) : (x_1, x_2, x_3) => rewriteBottomUpM$__at__$rewriteBottomUp$spec__0$__lam__0(__uniq$1, x_1, x_2, x_3), __uniq$2));
export const rewriteBottomUpM$__at__$rewriteBottomUp$spec__0$__lam__0 = (/* obj */ __uniq$1, /* obj */ __uniq$2) => rewriteBottomUpM$__at__$rewriteBottomUp$spec__0(__uniq$1, __uniq$2);
export const rewriteBottomUp = (/* obj */ __uniq$1, /* obj */ __uniq$2) => rewriteBottomUpM$__at__$rewriteBottomUp$spec__0(rewriteBottomUp$__lam__0.length - 1 === 0 ? () => rewriteBottomUp$__lam__0(__uniq$1) : rewriteBottomUp$__lam__0.length - 1 === 1 ? (x_1) => rewriteBottomUp$__lam__0(__uniq$1, x_1) : rewriteBottomUp$__lam__0.length - 1 === 2 ? (x_1, x_2) => rewriteBottomUp$__lam__0(__uniq$1, x_1, x_2) : (x_1, x_2, x_3) => rewriteBottomUp$__lam__0(__uniq$1, x_1, x_2, x_3), __uniq$2);
export const Fun$ctorElim = (/* tobj */ __uniq$2, /* obj */ __uniq$3, /* tobj */ __uniq$5) => Fun$ctorElim$__redArg(__uniq$3, __uniq$5);

main();
