// Generated by Lean ES6 emitter
import { lean_nat_to_int } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Basic.js";
import { Int$repr } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/Data/Int/Repr.js";
import { lean_get_stdout } from "/home/srghma/projects/lean4/build/release/stage1/bin/../src/lean/Init/System/IO.js";
export const Variant$ctorElim$__redArg = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => {
  if (__uniq$1.tag === "Variant$foo") {
    const __uniq$4 = __uniq$2(__uniq$1._1);
    return __uniq$4;
  } else if (__uniq$1.tag === "Variant$bar") {
    const __uniq$7 = __uniq$2(__uniq$1._1);
    return __uniq$7;
  } else if (__uniq$1.tag === "Variant$baz") {
    const __uniq$9 = __uniq$2(__uniq$1._1);
    return __uniq$9;
  }
};
export const Variant$foo$elim = (/* obj */ __uniq$2, /* tobj */ __uniq$4) => Variant$ctorElim$__redArg(__uniq$2, __uniq$4);
export const Variant$ctorElim = (/* tobj */ __uniq$2, /* obj */ __uniq$3, /* tobj */ __uniq$5) => Variant$ctorElim$__redArg(__uniq$3, __uniq$5);
export const test1 = (/* obj */ __uniq$1) => {
  if (__uniq$1.tag === "Variant$foo") {
    const __uniq$3 = String(__uniq$1._1);
    return __uniq$3;
  } else if (__uniq$1.tag === "Variant$bar") {
    return __uniq$1._1 ? "true" : "false";
  } else if (__uniq$1.tag === "Variant$baz") {
    return __uniq$1._1;
  }
};
export const Variant$ctorIdx = (/* obj */ __uniq$1) => {
  if (__uniq$1.tag === "Variant$foo") {
    return 0;
  } else if (__uniq$1.tag === "Variant$bar") {
    return 1;
  } else if (__uniq$1.tag === "Variant$baz") {
    return 2;
  }
};
export const main$__closed__2 = test1({ tag: "Variant$foo", _1: 42 });
export const IO$print$__at__$IO$println$__at__$main$spec__0$spec__0 = (/* obj */ __uniq$1) => lean_get_stdout()._5(__uniq$1);
export const IO$println$__at__$main$spec__0 = (/* obj */ __uniq$1) => IO$print$__at__$IO$println$__at__$main$spec__0$spec__0(__uniq$1 + String.fromCodePoint(10));
export const main$__closed__3 = (() => {
  const __uniq$1 = 1;
  const __uniq$2 = { tag: "Variant$bar" };
  __uniq$2._1 = __uniq$1;
  return __uniq$2;
})();
export const main$__closed__4 = test1(main$__closed__3);
export const main$__closed__7 = test1({ tag: "Variant$baz", _1: "hi" });
export const main = () => {
  const __uniq$2 = main$__closed__2;
  const __uniq$3 = IO$println$__at__$main$spec__0(__uniq$2);
  if (__uniq$3.tag === "EST$Out$ok") {
    const __uniq$5 = IO$println$__at__$main$spec__0(main$__closed__4);
    if (__uniq$5.tag === "EST$Out$ok") {
      const __uniq$7 = IO$println$__at__$main$spec__0(main$__closed__7);
      return __uniq$7;
    } else if (__uniq$5.tag === "EST$Out$error") {
      return __uniq$5;
    }
  } else if (__uniq$3.tag === "EST$Out$error") {
    return __uniq$3;
  }
};
export const Variant$bar$elim$__redArg = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => Variant$ctorElim$__redArg(__uniq$1, __uniq$2);
export const Variant$bar$elim = (/* obj */ __uniq$2, /* tobj */ __uniq$4) => Variant$ctorElim$__redArg(__uniq$2, __uniq$4);
export const Variant$foo$elim$__redArg = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => Variant$ctorElim$__redArg(__uniq$1, __uniq$2);
export const Variant$baz$elim = (/* obj */ __uniq$2, /* tobj */ __uniq$4) => Variant$ctorElim$__redArg(__uniq$2, __uniq$4);
export const Variant$baz$elim$__redArg = (/* obj */ __uniq$1, /* tobj */ __uniq$2) => Variant$ctorElim$__redArg(__uniq$1, __uniq$2);

main();
